### ISSUE TITLE
554 Crashing on 32bit Android

### ISSUE THREAD

**Issue by urthling** [airsdk/Adobe-Runtime-Support#1014]
An aab & 32bit apk build is crashing a few seconds after the App opens on a 32bit Android (Moto E(4) 7.1.1)
`minSdkVersion="15" targetSdkVersion="30"`

This was running without issue with 476 and below -- I can't roll back to confirm that since updating ANEes to be compatible with 533+

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke interface method 'android.os.IBinder android.view.IWindow.asBinder()' on a null object reference
android.os.Parcel.readException (Parcel.java:1698)
android.os.Parcel.readException (Parcel.java:1645)
android.view.IWindowSession$Stub$Proxy.finishDrawing (IWindowSession.java:1202)
android.view.SurfaceView.updateWindow (SurfaceView.java:652)
android.view.SurfaceView$3.onPreDraw (SurfaceView.java:161)
android.view.ViewTreeObserver.dispatchOnPreDraw (ViewTreeObserver.java:944)
android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2223)
android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1272)
android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:6408)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:874)
android.view.Choreographer.doCallbacks (Choreographer.java:686)
android.view.Choreographer.doFrame (Choreographer.java:621)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:860)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6196)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:888)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:778)

```

**Comment by ajwfrost** [comment]
Are you able to provide a full logcat output for this? The above has nothing in it that looks to be related to AIR, it's all internal Android functionality..
thanks

**Comment by urthling** [comment]
My bad -- ok, here we go:
```

07-27 22:15:08.930  1546  3400 I ActivityManager: Start proc 22229:com.myapp/u0a311 for broadcast com.myapp/com.distriqt.extension.beacon.services.StartupBroadcastReceiver
07-27 22:15:09.916 22229 22229 I BeaconManager: BeaconManager started up on pid 22229 named 'com.myapp' for application package 'com.myapp'.  isMainProcess=true
07-27 22:15:10.050 22229 22333 I FA      :   adb shell setprop debug.firebase.analytics.app com.myapp
07-27 22:15:58.980  1546  1584 I ActivityManager: Killing 22229:com.myapp/u0a311 (adj 906): empty #13
07-27 22:16:21.745 23058 23058 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
07-27 22:16:21.756 23058 23058 D AndroidRuntime: CheckJNI is OFF
07-27 22:16:22.120 23058 23058 D AndroidRuntime: Calling main entry com.android.commands.pm.Pm
07-27 22:16:22.125 23058 23058 I AndroidRuntime: VM exiting with result code 0.
07-27 22:22:34.369 23365 23384 W PackageParser: Ignoring duplicate uses-permissions/uses-permissions-sdk-m: com.google.android.c2dm.permission.RECEIVE in package: com.myapp at: Binary XML file line #764
07-27 22:22:36.583 23365 23383 I Finsky  : [2924] afnx.c(3): Verify: Verification package=com.myapp, id=28 response=0
07-27 22:22:36.620 23365 23384 W PackageParser: Ignoring duplicate uses-permissions/uses-permissions-sdk-m: com.google.android.c2dm.permission.RECEIVE in package: com.myapp at: Binary XML file line #764
07-27 22:22:36.869  1546  1626 W PackageParser: Ignoring duplicate uses-permissions/uses-permissions-sdk-m: com.google.android.c2dm.permission.RECEIVE in package: com.myapp at: Binary XML file line #764
07-27 22:22:36.951  1546  1626 I PackageManager.DexOptimizer: Running dexopt (dex2oat) on: /data/app/vmdl2007561098.tmp/base.apk pkg=com.myapp isa=arm vmSafeMode=false debuggable=false target-filter=interpret-only oatDir = /data/app/vmdl2007561098.tmp/oat sharedLibraries=null
07-27 22:22:45.851  1546  1584 I ActivityManager: Force stopping com.myapp appid=10311 user=-1: installPackageLI
07-27 22:22:46.121  1546  1626 I PackageManager: Package com.myapp codePath changed from /data/app/com.myapp-2 to /data/app/com.myapp-1; Retaining data and using new
07-27 22:22:46.122  1546  1626 W PackageManager: Code path for com.myapp changing from /data/app/com.myapp-2 to /data/app/com.myapp-1
07-27 22:22:46.122  1546  1626 W PackageManager: Resource path for com.myapp changing from /data/app/com.myapp-2 to /data/app/com.myapp-1
07-27 22:22:46.278  1546  1626 W PackageManager: Unknown permission android.permission.FOREGROUND_SERVICE in package com.myapp
07-27 22:22:46.278  1546  1626 W PackageManager: Unknown permission com.google.android.apps.photos.permission.GOOGLE_PHOTOS in package com.myapp
07-27 22:22:46.278  1546  1626 W PackageManager: Unknown permission android.permission.USE_BIOMETRIC in package com.myapp
07-27 22:22:46.279  1546  1626 W PackageManager: Not granting permission com.google.android.providers.gsf.permission.WRITE_GSERVICES to package com.myapp (protectionLevel=18 flags=0x3808be44)
07-27 22:22:46.279  1546  1626 W PackageManager: Unknown permission com.sec.android.provider.badge.permission.READ in package com.myapp
07-27 22:22:46.279  1546  1626 W PackageManager: Unknown permission com.sec.android.provider.badge.permission.WRITE in package com.myapp
07-27 22:22:46.279  1546  1626 W PackageManager: Unknown permission com.htc.launcher.permission.READ_SETTINGS in package com.myapp
07-27 22:22:46.279  1546  1626 W PackageManager: Unknown permission com.htc.launcher.permission.UPDATE_SHORTCUT in package com.myapp
07-27 22:22:46.279  1546  1626 W PackageManager: Unknown permission com.sonyericsson.home.permission.BROADCAST_BADGE in package com.myapp
07-27 22:22:46.279  1546  1626 W PackageManager: Unknown permission com.sonymobile.home.permission.PROVIDER_INSERT_BADGE in package com.myapp
07-27 22:22:46.279  1546  1626 W PackageManager: Unknown permission com.anddoes.launcher.permission.UPDATE_COUNT in package com.myapp
07-27 22:22:46.279  1546  1626 W PackageManager: Unknown permission com.majeur.launcher.permission.UPDATE_BADGE in package com.myapp
07-27 22:22:46.279  1546  1626 W PackageManager: Unknown permission com.huawei.android.launcher.permission.CHANGE_BADGE in package com.myapp
07-27 22:22:46.279  1546  1626 W PackageManager: Unknown permission com.huawei.android.launcher.permission.READ_SETTINGS in package com.myapp
07-27 22:22:46.279  1546  1626 W PackageManager: Unknown permission com.huawei.android.launcher.permission.WRITE_SETTINGS in package com.myapp
07-27 22:22:46.279  1546  1626 W PackageManager: Unknown permission android.permission.READ_APP_BADGE in package com.myapp
07-27 22:22:46.279  1546  1626 W PackageManager: Unknown permission com.oppo.launcher.permission.READ_SETTINGS in package com.myapp
07-27 22:22:46.279  1546  1626 W PackageManager: Unknown permission com.oppo.launcher.permission.WRITE_SETTINGS in package com.myapp
07-27 22:22:46.279  1546  1626 W PackageManager: Unknown permission me.everything.badger.permission.BADGE_COUNT_READ in package com.myapp
07-27 22:22:46.279  1546  1626 W PackageManager: Unknown permission me.everything.badger.permission.BADGE_COUNT_WRITE in package com.myapp
07-27 22:22:46.440 29554 23486 I IntentFilterIntentOp: Verifying IntentFilter. verificationId:8 scheme:"https" hosts:"blu.la link.blu.la/e link.blu.la/i link.blu.la/u link.myapp.com/e link.myapp.com/i link.myapp.com/s link.myapp.com/u" package:"com.myapp". [CONTEXT service_id=244 ]
07-27 22:22:46.598  1546  1626 I ActivityManager: Force stopping com.myapp appid=10311 user=0: pkg removed
07-27 22:22:46.625  2300  2300 D BluetoothMapAppObserver: The removed package is: com.myapp
07-27 22:22:46.626  2300  2300 D BluetoothMapAppObserver: The installed package is: com.myapp
07-27 22:22:46.713  1546 23503 D PackageController.doInBackground(): : Package com.myapp, package state=0, action=android.intent.action.PACKAGE_ADDED
07-27 22:22:46.716  1546 23503 D PackageController.doInBackground(): : Package com.myapp does NOT conflict with any policy.
07-27 22:22:46.772  1546 23504 D PackageController.doInBackground(): : Package com.myapp, package state=0, action=android.intent.action.PACKAGE_REPLACED
07-27 22:22:46.772  1546 23504 D PackageController.doInBackground(): : Package com.myapp does NOT conflict with any policy.
07-27 22:22:46.776 23365 23365 I Finsky  : [1] VerifyInstallTask.mz(6): Verification complete: id=28, package_name=com.myapp
07-27 22:22:46.785 23365 23365 I Finsky  : [1] tsn.n(-1): Invalidating cached PackageState for com.myapp
07-27 22:22:46.804 23365 23365 I Finsky  : [1] nrw.mt(2): Installer: package com.myapp was removed. replacing: true
07-27 22:22:46.816 23365 23365 I Finsky  : [1] nsi.N(18): Installer: Notifying status update. package=com.myapp, status=UNINSTALLED
07-27 22:22:46.829 23365 23483 I Finsky  : [2988] gin.a(16): Cancelled 0 ongoing asset module downloads for package com.myapp due to a concurrent app update.
07-27 22:22:46.862 23365 23386 I Finsky  : [2927] fti.a(5): AIM: AppInfoManager-Perf > OnDeviceAppInfo > cacheHitCount=0, cacheMissCount=1. Missed  in cache (limit 10) : [com.myapp]
07-27 22:22:46.939 23365 23463 I Finsky  : [2975] ofk.G(2): IQ: Notifying installation update. package=com.myapp, status=UNINSTALLED
07-27 22:22:48.500 23593 23610 V VZWAVSService: com.myapp
07-27 22:22:48.517 23365 23365 I Finsky  : [1] tsn.n(-1): Invalidating cached PackageState for com.myapp
07-27 22:22:48.565 23365 23483 I Finsky  : [2988] gin.a(24): Asset module broadcast after update successful for package com.myapp. 0 sessions broadcast.
07-27 22:22:48.584 23365 23395 I Finsky  : [2936] fti.a(5): AIM: AppInfoManager-Perf > OnDeviceAppInfo > cacheHitCount=0, cacheMissCount=1. Missed  in cache (limit 10) : [com.myapp]
07-27 22:22:48.603 23556 23556 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
07-27 22:22:48.611 23556 23556 D AndroidRuntime: CheckJNI is OFF
07-27 22:22:48.925 23556 23556 D AndroidRuntime: Calling main entry com.android.commands.am.Am
07-27 22:22:48.932  1546  3396 I ActivityManager: START u0 {act=android.intent.action.MAIN flg=0x10000000 cmp=com.myapp/.AppEntry} from uid 2000 on display 0
07-27 22:22:48.960 23556 23556 D AndroidRuntime: Shutting down VM
07-27 22:22:49.067  1546 26912 I ActivityManager: Start proc 23660:com.myapp/u0a311 for activity com.myapp/.AppEntry
07-27 22:22:49.269 23593 23681 V VZWAVSService: com.myapp
07-27 22:22:49.598   575   575 D SFPerfTracer:        layers: (5:8) (StatusBar (0xaf694000): 25:6078) (com.android.systemui.ImageWallpaper (0xaf54bc00): 25:3486) (DimLayerController/Stack=0 (0xaf697c00): 0:196)* (animation background stackId=1 (0xaf696800): 1:36)* (com.motorola.launcher3/com.android.launcher3.GoogleNowPanel (0xaf293800): 25:1294) (com.motorola.launcher3/com.android.launcher3.GoogleNowPanel (0xaf291000): 25:732)* (NavigationBar (0xaf292400): 25:84) (Starting com.myapp (0xaf294c00): 25:30) 
07-27 22:22:50.110 23660 23719 I FA      :   adb shell setprop debug.firebase.analytics.app com.myapp
07-27 22:22:51.032 23593 23753 V VZWAVSService: com.myapp
07-27 22:23:06.940 23660 23660 I com.myapp:  ================================================ Capabilities.manufacturer ====================== Android Linux -- assetScale: 2
07-27 22:23:07.046 23660 23660 D AndroidRuntime: Shutting down VM
07-27 22:23:07.439 23660 23660 E AndroidRuntime: FATAL EXCEPTION: main
07-27 22:23:07.439 23660 23660 E AndroidRuntime: Process: com.myapp, PID: 23660
07-27 22:23:07.439 23660 23660 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'android.os.IBinder android.view.IWindow.asBinder()' on a null object reference
07-27 22:23:07.439 23660 23660 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1698)
07-27 22:23:07.439 23660 23660 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1645)
07-27 22:23:07.439 23660 23660 E AndroidRuntime: 	at android.view.IWindowSession$Stub$Proxy.finishDrawing(IWindowSession.java:1202)
07-27 22:23:07.439 23660 23660 E AndroidRuntime: 	at android.view.SurfaceView.updateWindow(SurfaceView.java:652)
07-27 22:23:07.439 23660 23660 E AndroidRuntime: 	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:161)
07-27 22:23:07.439 23660 23660 E AndroidRuntime: 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
07-27 22:23:07.439 23660 23660 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2223)
07-27 22:23:07.439 23660 23660 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1272)
07-27 22:23:07.439 23660 23660 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6408)
07-27 22:23:07.439 23660 23660 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
07-27 22:23:07.439 23660 23660 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
07-27 22:23:07.439 23660 23660 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:621)
07-27 22:23:07.439 23660 23660 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
07-27 22:23:07.439 23660 23660 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
07-27 22:23:07.439 23660 23660 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-27 22:23:07.439 23660 23660 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
07-27 22:23:07.439 23660 23660 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6196)
07-27 22:23:07.439 23660 23660 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-27 22:23:07.439 23660 23660 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
07-27 22:23:07.439 23660 23660 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
07-27 22:23:07.441  1546  1567 W ActivityManager:   Force finishing activity com.myapp/.AppEntry
07-27 22:23:07.948  1546  1584 W ActivityManager: Activity pause timeout for ActivityRecord{ac171b2 u0 com.myapp/.AppEntry t1355 f}
07-27 22:23:07.983  1546  1584 I WindowManager: Failed to capture screenshot of Token{6add503 ActivityRecord{ac171b2 u0 com.myapp/.AppEntry t1355 f}} appWin=Window{aa9f6af u0 SurfaceView - com.myapp/com.myapp.AppEntry} drawState=3
07-27 22:23:08.047   575   575 D SFPerfTracer:        layers: (4:16) (StatusBar (0xaf694000): 19:6124) (com.android.systemui.ImageWallpaper (0xaf54bc00): 19:3525)* (DimLayerController/Stack=0 (0xaf697c00): 9:205) (animation background stackId=1 (0xaf696800): 0:37)* (com.motorola.launcher3/com.android.launcher3.GoogleNowPanel (0xaf293800): 19:1333)* (com.motorola.launcher3/com.android.launcher3.GoogleNowPanel (0xaf291000): 19:771)* (NavigationBar (0xaf292400): 19:123) (Starting com.myapp (0xaf294c00): 19:69)* (com.myapp/com.myapp.AppEntry (0xaf548000): 19:37)* (SurfaceView - com.myapp/com.myapp.AppEntry (0xaf695400): 19:34)* (SurfaceView - com.myapp/com.myapp.AppEntry (0xb0b48400): 19:34)* (SurfaceView - com.myapp/com.myapp.AppEntry (0xaf54a800): 19:35)* (SurfaceView - com.myapp/com.myapp.AppEntry (0xaf549400): 19:35)* (SurfaceView - com.myapp/com.myapp.AppEntry (0xb0b4ac00): 0:3)- (SurfaceView - com.myapp/com.myapp.AppEntry (0xb0b49800): 0:3)- (Application Error: com.myapp (0xb0b49800): 19:26) 
07-27 22:23:16.431  1546  1546 E JobServiceContext: Time-out while trying to bind bb7ae5c #u0a311/627781264 com.myapp/com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService, dropping.
07-27 22:23:18.282  1546  1584 W ActivityManager: Activity destroy timeout for ActivityRecord{ac171b2 u0 com.myapp/.AppEntry t1355 f}
07-27 22:23:36.432  1546  1584 W ActivityManager: Timeout executing service: ServiceRecord{4a36be4 u0 com.myapp/com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService}
07-27 22:23:36.474  1546  1584 I ActivityManager: Crashing app skipping ANR: ProcessRecord{6feb95b 23660:com.myapp/u0a311} executing service com.myapp/com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService
07-27 22:24:29.887   575   575 D SFPerfTracer:        layers: (6:14) (StatusBar (0xaf694000): 1:6191) (com.android.systemui.ImageWallpaper (0xaf54bc00): 0:3557) (DimLayerController/Stack=0 (0xaf697c00): 0:205) (animation background stackId=1 (0xaf696800): 0:37)* (com.motorola.launcher3/com.android.launcher3.GoogleNowPanel (0xaf293800): 0:1371) (com.motorola.launcher3/com.android.launcher3.GoogleNowPanel (0xaf291000): 0:803)* (NavigationBar (0xaf292400): 0:155) (Starting com.myapp (0xaf294c00): 0:94)- (com.myapp/com.myapp.AppEntry (0xaf548000): 0:67)- (SurfaceView - com.myapp/com.myapp.AppEntry (0xaf695400): 0:62)- (SurfaceView - com.myapp/com.myapp.AppEntry (0xb0b48400): 0:62)- (SurfaceView - com.myapp/com.myapp.AppEntry (0xaf54a800): 0:64)- (SurfaceView - com.myapp/com.myapp.AppEntry (0xaf549400): 0:64)- (Application Error: com.myapp (0xb0b49800): 0:58) 

```

**Comment by urthling** [comment]
Ah, is this to do with blackScreenHelper function?  I've been using the Application ANE from Distriqt for quite some time, but just recently implemented the method to help with Android not returning from sleep properly, and the screen remaining black. 

The workaround I had in my App seemed to be good until recently (not sure which build this crept back in)  -- I was going to bring this up as a separate post but figured this workaround would suffice for now, I know you guys have a lot on with getting this release done before the August deadline..

I'm going to remove reference to this function and try again..

**Comment by urthling** [comment]
Ah -- sure enough -- it's a call to the `Application.service.blackScreenHelper()`  @marchbold -- Looks like this is crashing my 32bit Android device -- I'll open an issue under the ANE and reference this post.

Sorry @ajwfrost - thank you so checking in on this one, apologies for not narrowing this down before posting here.  That said, Android not returning from sleep properly, and the screen remaining black is definitely an old air bug, so with any luck you'll have time to tackle it.  I'll create a better post, and reference some old posts that discuss the issue and the workarounds seemed to have worked - until recently that is.

**Comment by ajwfrost** [comment]
@urthling thanks: regarding the black screen issue, we're looking into that currently and seeing what we can do with the EGL contexts to try to prevent this - or at least to ensure the application can restore itself properly..

I'm still curious as to why the call stack is fully within the Android system code, there is no hint that the call was made from AIR or an ANE, other than the fact it's the same PID! and the "shutting down VM" output comes a few times in that log..

Curious as to how this is also reported from the same process as the error in that first log:
`adb shell setprop debug.firebase.analytics.app com.myapp`
@marchbold would be interested in your thoughts!

**Comment by marchbold** [comment]
I think this crash is due to calling the `blackScreenHelper()` before AIR is completely initialised. We do say in the docs not to call this on the first activate event as it will crash like this at that point.

**Comment by urthling** [comment]
Yes, this was my bad!  I can confirm, I'm now not calling this function on the first Activate event, all is well.

Excellent to know you guys are working on a solution to the Black Screen though!  Apologies again for taking time.

**Comment by raresn** [comment]
@ajwfrost  Wondering if we can do something about the blackScreenHelper to have it integrated in AIR? We now use it in each android app, cannot go without it.

**Comment by marchbold** [comment]
@ajwfrost I believe it is AIR crashing due to something we do, my guess is the surface view is still initialising and when we play with it, it breaks this process and the main app crashes. 

The helper just basically finds the surface view, removes it and adds it, but I guess that messes up the initialisation.
