### ISSUE TITLE
I can't install aab. AIR SDK 33.1.1.575

### ISSUE THREAD

**Issue by Dima107** [airsdk/Adobe-Runtime-Support#1065]
I built aab in same way as I did with with AIR SDK 554
Then I tried to build *.apks file.
I've got error
`[BT:0.10.3] Error: An error occurred when processing the bundle 'motoX3M.aab'.
java.io.UncheckedIOException: An error occurred when processing the bundle 'motoX3M.aab'.
        at com.android.tools.build.bundletool.commands.BuildApksManager.execute(BuildApksManager.java:113)
        at com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:524)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:74)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)
Caused by: java.util.zip.ZipException: invalid CEN header (bad signature)
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1573)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1527)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1280)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1243)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:732)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:841)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:191)
        at com.android.tools.build.bundletool.commands.BuildApksManager.execute(BuildApksManager.java:109)
        ... 3 more`
        
        JDK version "11.0.11"

**Comment by Dima107** [comment]
Thank you, It works
