### ISSUE TITLE
Android App Bundle crashes when launching in device after updating in playstore

### ISSUE THREAD

**Issue by Gokulv617** [airsdk/Adobe-Runtime-Support#1097]
AIR 33.1.1.575
Adobe Animate
Using DISTRIQT ANE's

I successfully deployed .aab format to playstore and it got live minutes before. When I update and launch the app it crashes immediately. Please let me know what went wrong. I can share the .aab file if you need.

```
2021-08-21 10:09:04.690 30410-30410/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: air.com.hfg.reverie.escape.room.mystery.brain.adventure.door, PID: 30410
    java.lang.NoSuchFieldError: No static field common_google_play_services_unknown_issue of type I in class Lcom/google/android/gms/common/R$string; or its superclasses (declaration of 'com.google.android.gms.common.R$string' appears in base.apk)
        at com.google.android.gms.common.internal.StringResourceValueReader.<init>(com.google.android.gms:play-services-basement@@17.5.0:4)
        at com.google.firebase.FirebaseOptions.fromResource(FirebaseOptions.java:156)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:243)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:51)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2429)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2399)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:45)
        at android.app.ActivityThread.installProvider(ActivityThread.java:8069)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7605)
        at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7489)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7446)
        at android.app.ActivityThread.access$1500(ActivityThread.java:301)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2148)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8512)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
2021-08-21 10:09:04.694 1016-4441/? W/ActivityManager: crash : air.com.hfg.reverie.escape.room.mystery.brain.adventure.door,10605
2021-08-21 10:09:04.695 1016-4441/? W/ActivityTaskManager:   Force finishing activity air.com.hfg.reverie.escape.room.mystery.brain.adventure.door/.AIRAppEntry
```

Full log is attached below,
[Logs.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/7024873/Logs.txt)

ANE's used:
```
com.distriqt.Core
com.distriqt.playservices.AdsIdentifier
com.distriqt.Adverts
com.distriqt.playservices.Base
com.distriqt.playservices.Ads
androidx.appcompat
androidx.browser
androidx.core
androidx.constraintlayout
androidx.vectordrawable
com.google.code.gson
com.distriqt.InAppBilling
com.google.protobuflite
com.google.firebase.core
com.distriqt.Firebase
androidx.multidex
com.distriqt.CustomResources
com.distriqt.playservices.Drive
com.distriqt.playservices.Games
com.distriqt.playservices.Auth
com.distriqt.GameServices
com.distriqt.PushNotifications
com.google.android.datatransport
com.google.dagger
androidx.cardview
androidx.room
androidx.work
com.distriqt.playservices.CloudMessaging
```

**Comment by marchbold** [comment]
Make sure you have the latest play services, there was an issue with Aab and an earlier release.

**Comment by Gokulv617** [comment]
I was using the latest ANE's. But now it shows yesterday you have updated the dependencies. I mean,

- ANE-AndroidSupport
- ANE-Core
- ANE-GooglePlayServices

is that all ?

**Comment by Gokulv617** [comment]
Thanks ! After updating the ANE's it is solved now
