### ISSUE TITLE
fdb: Unexpected error while processing command, in DebugCLI.setInitialSourceFile

### ISSUE THREAD

**Issue by j3k0** [airsdk/Adobe-Runtime-Support#1232]
## Problem Description

The app connects to the debugger, but the latest fails (from the stacktrace, it looks like the problem is with loading source files).

```
$ fdb
Adobe fdb (Flash Player Debugger) [build development]
Copyright (c) 2004-2007 Adobe, Inc. All rights reserved.
(fdb) r
Waiting for Player to connect
Player connected; session starting.
Unexpected error while processing command.
For diagnostic purposes stack trace follows:
java.lang.NullPointerException
        at flex.tools.debugger.cli.DebugCLI.setInitialSourceFile(DebugCLI.java:5108)
        at flex.tools.debugger.cli.DebugCLI.doRun(DebugCLI.java:5032)
        at flex.tools.debugger.cli.DebugCLI.processLine(DebugCLI.java:7052)
        at flex.tools.debugger.cli.DebugCLI.process(DebugCLI.java:828)
        at flex.tools.debugger.cli.DebugCLI.execute(DebugCLI.java:669)
        at flex.tools.debugger.cli.DebugCLI.main(DebugCLI.java:461)
```

* SDK `33.1.1.633` 
* Environment: Android (not tested on iOS)

**Comment by ajwfrost** [comment]
Thanks for the detailed investigation! We'll have to look into this and see if we can reproduce it with the different optimize settings. I would have thought that things might have been the other way round i.e. including the optimization step would cause issues..

Can I check, are you just using the full AIR SDK on its own, or is this Flex-based i.e. a Flex SDK plus the stripped-back AIR SDK overlay?

thanks

**Comment by j3k0** [comment]
> Are you just using the full AIR SDK on its own

Yes, full AIR SDK, on its own. `33.1.1.633`.

To compile the SWF, we're using `mxmlc` on the command-line with an `mxmlc-config.xml` file which I can provide if needed. Same for `adt`, it's used from the command-line and I can provide the application descriptor.

**Comment by BMGMobile** [comment]
We are seeing this as well with 64-bit Android builds on the full AIR SDK versions `33.1.1.743` and `33.1.1.929`. We are compiling through Haxe and packaging this with the command line `adt -package -target apk-debug -arch armv8`.

**Comment by BMGMobile** [comment]
This turned out to be a problem with using an older version of BlueStacks for us. `33.1.1.743` is working correctly with the latest BlueStacks 5.
