### ISSUE TITLE
IntelliJ Won't Package Android AIR Application

### ISSUE THREAD

**Issue by RossD20Studios** [airsdk/Adobe-Runtime-Support#1249]
## Problem Description

Describe your problem in detail. Include the following information:

IntelliJ fails to package Android AIR application.
Using AIR SDK 33.1.1.620
Using IntelliJ 2021.2.2 (Ultimate Edition) with Flash/Flex Plugin

## Steps to Reproduce

1. Create a new Pure ActionScript Project with Mobile Build target, Android selected
2. Allow IntelliJ to create a default application (Main.as)
3. Package the application for Android

**Error produced is as follows:**
Failed to package AIR application Android.apk:  dx tool failed:Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/tools/r8/D8 : Unsupported major.minor version 52.0 at java.lang.ClassLoader.defineClass1(Native Method) at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637) at java.lang.ClassLoader.defineClass(ClassLoader.java:621) at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141) at java.net.URLClassLoader.defineClass(URLClassLoader.java:283) at java.net.URLCl...  [Full error message] [ADT command line]

## Known Workarounds

No known workarounds. I discovered this error attempting to publish my actual project for mobile, and found that the error occurs even in the simplest case of a new project.
IntelliJ will compile and allow you to debug the application in the mobile simulator. The bug is specific to packaging the app for release and debugging on device.

**Comment by marchbold** [comment]
You should use Java 8 for Android applications, this is a requirement of Android :)

**Comment by Mintonist** [comment]
I have this kind of errors:

`unexpected failure: Unable to run java: com.adobe.air.ADTException: gradle tool failed: Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01<br>Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01<br>Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01<br>Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01<br>Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01<br>FAILURE: Build failed with an exception.<br>* What went wrong:<br>Could not determine the dependencies of task ':app:bundleReleaseResources'.<br>> Installed Build Tools revision 31.0.0 is corrupted. Remove and install again using the SDK Manager.<br>* Try:<br>Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.<br>* Get more help at https://help.gradle.org<br>BUILD FAILED in 20s<br>java.io.IOException: Unable to run java: com.adobe.air.ADTException: gradle tool failed: Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01<br>Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01<br>Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01<br>Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01<br>Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01<br>FAILURE: Build failed with an exception.<br>* What went wrong:<br>Could not determine the dependencies of task ':app:bundleReleaseResources'.<br>> Installed Build Tools revision 31.0.0 is corrupted. Remove and install again using the SDK Manager.<br>* Try:<br>Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.<br>* Get more help at https://help.gradle.org<br>BUILD FAILED in 20s<br> at com.adobe.air.apk.AABOutputStream.buildGradle(AABOutputStream.java)<br> at com.adobe.air.apk.AABPackager.renameOutput(AABPackager.java)<br> at com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)<br> at com.adobe.air.apk.AABPackager.createPackage(AABPackager.java)<br> at com.adobe.air.ADT.parseArgsAndGo(ADT.java)<br> at com.adobe.air.ADT.run(ADT.java)<br> at com.adobe.air.ADT.main(ADT.java)`

**Comment by ajwfrost** [comment]
@Mintonist this is because those build tools drop support for dx.jar which is required by the Android Gradle plug-in version we're using .. see https://github.com/airsdk/Adobe-Runtime-Support/discussions/1184#discussioncomment-1374145 for a patch to restore it, but for our next release we've updated the Gradle/plug-in version requirements so that this error goes away.
