### ISSUE TITLE
Play Store Black Screen at open App.

### ISSUE THREAD

**Issue by neckish** [airsdk/Adobe-Runtime-Support#1347]
## Problem Description

When I install my app from Play Store on some devices It shows a black screen that gets stocked.
 

* Which AIR SDK did you use?  33.1.1.633
* Describe the affected environment: Android vs. iOS, all devices vs. just specific models. Android some models. One is attached.
![image](https://user-images.githubusercontent.com/12134502/141046821-4521fee0-fe2f-4c95-9d51-e34ccd2f333b.png)

The error was described to me. At first look, it was a webView Problem with an ANE from distriqt (NativeWebView) so I updated the ANE and try again with the abb compile but the same error happened. Then I try to install the APK directly to the device and it worked, but with the app from Play Store, the issue continue.

This is the log from the device after installing from Play Store:

[logcat.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/7509746/logcat.txt)

## Steps to Reproduce

try to install this app. [https://play.google.com/store/apps/details?id=air.plus.eszential.ipad]

Thanks for the help

**Comment by neckish** [comment]
Hi, I'm also getting this from the Store:

API
Ljava/io/FileDescriptor;->descriptor:I

StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ljava/io/FileDescriptor;->descriptor:I
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ljava/io/FileDescriptor;->descriptor:I
	at android.os.StrictMode.lambda$static$1(StrictMode.java:407)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at com.adobe.air.Entrypoints.EntryMainWrapper(Native Method)
	at com.adobe.air.Entrypoints.EntryMain(Entrypoints.java:143)
	at com.adobe.air.AndroidActivityWrapper.LaunchApplication(AndroidActivityWrapper.java:1221)
	at com.adobe.air.AndroidActivityWrapper.launchApplication(AndroidActivityWrapper.java:1508)
	at com.adobe.air.AndroidActivityWrapper.onSurfaceInitialized(AndroidActivityWrapper.java:1494)
	at com.adobe.air.AIRWindowSurfaceView.surfaceChanged(AIRWindowSurfaceView.java:802)
	at android.view.SurfaceView.updateSurface(SurfaceView.java:942)
	at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:215)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1102)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3310)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2200)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9037)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
	at android.view.Choreographer.doCallbacks(Choreographer.java:797)
	at android.view.Choreographer.doFrame(Choreographer.java:732)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8016)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ljava/io/FileDescriptor;->descriptor:I
	at android.os.StrictMode.lambda$static$1(StrictMode.java:416)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at com.adobe.air.Entrypoints.EntryMainWrapper(Native Method)
	at com.adobe.air.Entrypoints.EntryMain(Entrypoints.java:143)
	at com.adobe.air.AndroidActivityWrapper.LaunchApplication(AndroidActivityWrapper.java:1221)
	at com.adobe.air.AndroidActivityWrapper.launchApplication(AndroidActivityWrapper.java:1508)
	at com.adobe.air.AndroidActivityWrapper.onSurfaceInitialized(AndroidActivityWrapper.java:1494)
	at com.adobe.air.AIRWindowSurfaceView.surfaceChanged(AIRWindowSurfaceView.java:802)
	at android.view.SurfaceView.updateSurface(SurfaceView.java:1165)
	at android.view.SurfaceView.lambda$new$0$SurfaceView(SurfaceView.java:173)
	at android.view.-$$Lambda$SurfaceView$w68OV7dB_zKVNsA-r0IrAUtyWas.onPreDraw(Unknown Source:2)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3094)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8177)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:731)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)


StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ljava/io/FileDescriptor;->descriptor:I
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at com.adobe.air.Entrypoints.EntryMainWrapper(Native Method)
	at com.adobe.air.Entrypoints.EntryMain(Entrypoints.java:143)
	at com.adobe.air.AndroidActivityWrapper.LaunchApplication(AndroidActivityWrapper.java:1221)
	at com.adobe.air.AndroidActivityWrapper.launchApplication(AndroidActivityWrapper.java:1508)
	at com.adobe.air.AndroidActivityWrapper.onSurfaceInitialized(AndroidActivityWrapper.java:1494)
	at com.adobe.air.AIRWindowSurfaceView.surfaceChanged(AIRWindowSurfaceView.java:802)
	at android.view.SurfaceView.updateSurface(SurfaceView.java:682)
	at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:143)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2471)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1463)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by ajwfrost** [comment]
Hi

So if it worked with an APK build, but failed with AAB, then it is likely something to do with resources I suspect. In the log file it's showing a message:
```
11-09 18:28:06.180 23399 23399 W FirebaseApp: Default FirebaseApp failed to initialize because no default options were found. This usually means that com.google.gms:google-services was not applied to your gradle project.\
11-09 18:28:06.180 23399 23399 I FirebaseInitProvider: FirebaseApp initialization unsuccessful\
```

@marchbold are you able to comment on this? Wondering if the firebase settings aren't being picked up properly which is just preventing things from progressing...

**Comment by marchbold** [comment]
This is very possibly a resources issue. Are you using Firebase in your app? If so how are you providing the resources, are you using the old resources ANE approach or the resdir?

**Comment by neckish** [comment]
> This is very possibly a resources issue. Are you using Firebase in your app? If so how are you providing the resources, are you using the old resources ANE approach or the resdir?
> 
> If you are using the ANE you need to make sure you have updated it recently so the resources are included for all architectures.

Hi, I´m using Firebase for push notifications with Onesignal with ANEs. The res directory is only used for one signal resource like icons.

> If you are using the ANE you need to make sure you have updated it recently so the resources are included for all architectures. What do you mean by this?

<img width="347" alt="Captura de Pantalla 2021-11-10 a la(s) 18 37 51" src="https://user-images.githubusercontent.com/12134502/141215976-98bf3f3f-d85e-473c-8396-5d0902f4a2ca.png">
<img width="713" alt="Captura de Pantalla 2021-11-10 a la(s) 18 43 26" src="https://user-images.githubusercontent.com/12134502/141216420-c9b1ad8c-2628-429d-8a6c-a763e9ca7b28.png">

**Comment by marchbold** [comment]
Yeah okay, you don't need specific Firebase configuration for OneSignal it does it the manual way so those messages about Firebase default configuration missing are normal and won't cause a black screen.

**Comment by neckish** [comment]
> Yeah okay, you don't need specific Firebase configuration for OneSignal it does it the manual way so those messages about Firebase default configuration missing are normal and won't cause a black screen.

Ok, thanks. The tricky part is that the black screen only happens when you download the App from Play Store. When you install the APK directly to the device it works perfectly.

**Comment by marchbold** [comment]
What about when you install from the bundle? 

https://airsdk.dev/docs/tutorials/platform/android/packaging-android-app-bundles#testing

**Comment by neckish** [comment]
> What about when you install from the bundle?
> 
> https://airsdk.dev/docs/tutorials/platform/android/packaging-android-app-bundles#testing

Let me try this and I get back to you. thanks.

**Comment by neckish** [comment]
> What about when you install from the bundle?
> 
> https://airsdk.dev/docs/tutorials/platform/android/packaging-android-app-bundles#testing

Hi, I try to install to the device using this: 
`bundletool install-apks --apks=bundleQuery.apks
The APKs have been extracted in the directory: /var/folders/b7/k32rlpv101jc0fgt4nt1wc1c0000gn/T/10508316264048914945`

The install works perfectly, but the same issue once I open the app it gets to a black screen.

Here is the Log:
[LogCatQuery11Nov21.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/7523991/LogCatQuery11Nov21.txt)

Here is a video.
https://user-images.githubusercontent.com/12134502/141387766-249c1d50-774f-48d1-8c87-7b3195fdd6ad.mp4

Let me know if you need anything else. Thanks for the help.

**Comment by neckish** [comment]
Here is the aab compile:

[aab compile](https://kypquery.com/contents/data/QueryAppAAB.zip)

**Comment by ajwfrost** [comment]
Hi

I can't see anything wrong with this or anything jumping out in the log file .. can I please check, are you able to provide the AAB file built with "aab-debug"? 

Just wondering, if you set the "KeepAndroidStudioOutput" flag to true in the AIR SDK lib\adt.cfg file, it should then be possible to open the resulting folder in Android Studio. I would be interested if an APK built using this method would end up also causing a problem...

thanks

**Comment by neckish** [comment]
Hi, the problem was an old ANE that was incompatible with this aab compile. I remove this ANE and it works fine. Thanks for the help.
