### ISSUE TITLE
DiskReadViolation sqlite

### ISSUE THREAD

**Issue by ventr1x** [airsdk/Adobe-Runtime-Support#1364]
We're heavily using sqlite for about 6 years now with the exact same integration across all our apps.
Suddenly with .633 we experience the following issue.

**Environment**
- AIR SDK version: .633
- Device OS: Android 11
- Device version: Samsung S20+
- Development IDE: intellij
- Development OS: MacOS 11.3.1 (M1)
- Java: (AdoptOpenJDK)(build 1.8.0_292-b10)

```
11-16 15:45:03.702 23459 23523 D StrictMode: StrictMode policy violation: android.os.strictmode.DiskReadViolation
11-16 15:45:03.702 23459 23523 D StrictMode: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1596)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at android.database.sqlite.SQLiteConnection.applyBlockGuardPolicy(SQLiteConnection.java:1615)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1283)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:165)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:152)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:231)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:270)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at com.android.server.enterprise.storage.EdmStorageProviderBase.getValues(EdmStorageProviderBase.java:388)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at com.android.server.enterprise.storage.EdmStorageProviderBase.getValuesList(EdmStorageProviderBase.java:1124)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at com.android.server.enterprise.storage.EdmStorageProvider.getValuesList(EdmStorageProvider.java:312)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at com.android.server.enterprise.application.ApplicationPolicy.getContentValues(ApplicationPolicy.java:3818)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at com.android.server.enterprise.application.ApplicationPolicy.getApplicationStateEnabledAsUser(ApplicationPolicy.java:3785)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at com.android.server.enterprise.application.ApplicationPolicy.getApplicationStateEnabledAsUser(ApplicationPolicy.java:3727)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at com.android.server.pm.PackageManagerService.setEnabledSetting(PackageManagerService.java:25421)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at com.android.server.pm.PackageManagerService.setComponentEnabledSetting(PackageManagerService.java:25406)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3469)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:5281)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at android.os.Binder.execTransactInternal(Binder.java:1190)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at android.os.Binder.execTransact(Binder.java:1159)
11-16 15:45:03.702 23459 23523 D StrictMode: # via Binder call with stack:
11-16 15:45:03.702 23459 23523 D StrictMode: 	at android.os.StrictMode.readAndHandleBinderCallViolations(StrictMode.java:2358)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at android.os.Parcel.readExceptionCode(Parcel.java:2330)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at android.os.Parcel.readException(Parcel.java:2291)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at android.content.pm.IPackageManager$Stub$Proxy.setComponentEnabledSetting(IPackageManager.java:7378)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at android.app.ApplicationPackageManager.setComponentEnabledSetting(ApplicationPackageManager.java:3252)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at zrg.a(PG:1)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at zrg.a(PG:2)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at zrk.a(Unknown Source:85)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at bbyd.a(Unknown Source:14)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at bejv.a(Unknown Source:2)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at bejx.run(PG:9)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at azkz.run(PG:1)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at azjo.run(Unknown Source:24)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at java.lang.Thread.run(Thread.java:923)
```

We do not read anything while our app is running; but these only appear when testing our new app.
We preload all our data into objects and update the database in the background. So we have no idea where the read violation could come from but we feel that they might cause other queries to silently drop as we experience reports of random hangs in our apps.
We have some "choose your path" games that rely heavily on story progress being saved internally.

**Comment by ajwfrost** [comment]
Hi @ventr1x  - can I check if you've got any ANEs or similar, which may contain the obfuscated code above? Relevant lines extracted below:
```
11-16 15:45:03.702 23459 23523 D StrictMode: 	at android.app.ApplicationPackageManager.setComponentEnabledSetting(ApplicationPackageManager.java:3252)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at zrg.a(PG:1)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at zrg.a(PG:2)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at zrk.a(Unknown Source:85)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at bbyd.a(Unknown Source:14)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at bejv.a(Unknown Source:2)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at bejx.run(PG:9)
11-16 15:45:03.702 23459 23523 D StrictMode: 	at azkz.run(PG:1)
```

These aren't caused by the AIR runtime's use of sqlite, accessed via the ActionScript APIs, as these are handled within a C++ library, you should see libCore.so and lots of native function calls if there was a problem here rather than the above Java call stack.

So it looks like something else is being triggered, calling this `setComponentEnabledSetting` method, and that is triggering something behind the scenes where this strict-mode warning is coming out.

Do you see any adverse effects, missing data etc from your app? as normally these strict mode things are just warnings to help people prepare for future Android SDK/NDK changes...

You mention random hangs -> this was an issue in 33.1.1.633, see #1231 and #1277

thanks

**Comment by ventr1x** [comment]
I kind of thought so, as we are only reading from our DB at the start of the app.
But it was 3am so I was too tired too keep testing for yet another ANE bug that delays releases...
I highly suspect it's the Firebase ANEs that's causing these, but it does not seem to affect the app as far as we have tested.

**Comment by ajwfrost** [comment]
3am ... ouch!

Both Android and iOS are moving quite fast it seems, with big/breaking changes for applications that are as old as the AIR runtime, I'm looking forward to when we've managed to eliminate some of this 'technical debt' and things should get easier for us all.

thanks
