### ISSUE TITLE
Problem parsing the package

### ISSUE THREAD

**Issue by hadisn** [airsdk/Adobe-Runtime-Support#1370]
Hi, i use secureSWF from Kindi to encrypt apk file. With AIR33.1.1.345 everything works fine, but with newer sdk if I use secureSWF i can see error problem parsing the package.

I know that secureSWF software is outdated but it seems they won't release any updates, so is there someone have solution for this?

Thank you

**Comment by ajwfrost** [comment]
Hi - not sure what might have changed if you're still targeting APK creation.. depends a little on how they do things I guess because there's also the new requirement of having APK signature v2 in there. If it's just encrypting the swf file prior to packaging then it might have been okay, but if it was updating the APK itself and then reworking the signature, it may be a problem.

But, you may be able to solve it if you do have the APK as you can verify and re-sign using the apksigner tool that's part of the Android SDK tools?

Curious as to how this might work with Android App Bundles though ... or are they less of a problem anyway?

FYI we've just been playing with some encryption of a SWF; not the rest of the assets, but the SWF contents itself like you have different compression variants, there would be another variant which adds some obfuscation...

thanks

**Comment by hadisn** [comment]
Yes they updating apk and uses v1 signature scheme maybe that can be problem. Can you explain how to manually re-sign with apsigner tool?

Thank you

**Comment by MalacTheLittle** [comment]
> FYI we've just been playing with some encryption of a SWF; not the rest of the assets, but the SWF contents itself like you have different compression variants, there would be another variant which adds some obfuscation...

@ajwfrost This is great news :) Can you share some details how strong obfuscation will be? Will you have encrypted strings also?
I also used secureSWF, and there were some strong obfuscation levels even for breaking swf decompilers.

**Comment by hadisn** [comment]
Tried to resign with "apksigner sign --ks key.jks app.apk" Google Play doesn't show signature scheme v2 error but app cannot be installed on android device...

**Comment by hadisn** [comment]
I tried everything but not possible to get it work. These guys from Kindi are really irresponsible, they sell software and suddenly stop supporting it.

**Comment by MalacTheLittle** [comment]
@hadisn Just wondering, did you had app installed from Google Play while you were trying to install your apk to android device? I always need to deinstall it first to install .apk...

**Comment by hadisn** [comment]
![Screenshot_20211118-230159_My Files](https://user-images.githubusercontent.com/2553775/142503994-a94c18ba-5ac7-4ca4-b783-f0c86713d7e4.jpg)

I deinstalled it and transfer apk directly to device by usb cable, apk file which is not secured by secureSWF can be installed and it have icon as you can see on screenshot but all other can't be installed and have no icon.

Also file secured and not signed with apksigner can't be uploaded to Google Play due v2 signing scheme requirement, but another file signed with apksigner can be uploaded but doesn't work...

**Comment by MalacTheLittle** [comment]
secureSWF also has option to process swf files only. Did you try to process swf and package it to apk with `adt` command line?

**Comment by hadisn** [comment]
I don't know command to package it and add ane and all other files.

**Comment by MalacTheLittle** [comment]
You can find instructions [here](https://help.adobe.com/en_US/air/build/WS901d38e593cd1bac1e63e3d128cdca935b-8000.html), though here's my example:
`"C:\AIR_SDKs\AIR33.1.1.633\bin\adt" -package -target apk-captive-runtime -arch armv8 -storetype pkcs12 -keystore "certificate.p12" -storepass certificatePassword myApp.apk myApp-app.xml myApp.swf ...`
At `...` you add all dependencies for your app (.ane files, data files/folders, etc.)

**Comment by hadisn** [comment]
Oh thank you,  I forgot that i made .bat file for creating aab file with similiar command. I will let you know after testing...

**Comment by hadisn** [comment]
> You can find instructions [here](https://help.adobe.com/en_US/air/build/WS901d38e593cd1bac1e63e3d128cdca935b-8000.html), though here's my example: `"C:\AIR_SDKs\AIR33.1.1.633\bin\adt" -package -target apk-captive-runtime -arch armv8 -storetype pkcs12 -keystore "certificate.p12" -storepass certificatePassword myApp.apk myApp-app.xml myApp.swf ...` At `...` you add all dependencies for your app (.ane files, data files/folders, etc.)

It seems that your solution works. I will do more testing and reply here. 

Thank you

**Comment by MalacTheLittle** [comment]
Perfect! I'm glad it worked. I assumed it should since secureSWF obfuscates swf files from apk package because there lays your "open code". But for apk it needs to unpack swfs and pack em back again so probably has some problems with packing. And all you acctually need is obfuscated swf files from your app :)

**Comment by hadisn** [comment]
I released open testing and everything works fine for me but i see some errors in Google Play console, some of them are: 

Landroid/media/AudioTrack;->getLatency()I

Ljava/nio/Buffer;->address:J

Landroid/media/AudioManager;->getOutputLatency(I)I

Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J

Should I ignore these warnings?

**Comment by MalacTheLittle** [comment]
Not sure what type of and how strong obfuscation levels have you set in SecureSWF, but you can check wheter these errors are caused by SecureSWF by setting obfuscation levels to zero or even just upload unsecured app to Google Play.

**Comment by hadisn** [comment]
I am using same obfuscation levels as for all apps currently on Google Play, but i have another question :)

I am trying to package aab and when included ane files app crashes on start, without ane it works fine. 

Ane doesn't support x86 platform, so is there way to exclude x86 and x86_64 while packaging aab?

Thank you

**Comment by MalacTheLittle** [comment]
Sorry, can't help you with that. I'm still uploading two apk's to Play Console and will do that until aab becomes the only option :)

**Comment by hadisn** [comment]
Me too, but soon i think about upload new game...:)

**Comment by ajwfrost** [comment]
> Ane doesn't support x86 platform, so is there way to exclude x86 and x86_64 while packaging aab?

Currently not without going through an intermediate step. We were looking to add this possibility though so that you can choose what goes into the bundle..

To do it manually you would need to change the config file in the AIR SDK `lib\adt.cfg` so that it has `KeepAndroidStudioOutput=true` uncommented. Then you should end up with an `AndroidStudioProject` folder that's in the same location as your app descriptor file.

Within this will be the native libraries in `app\src\main\jniLibs` so you can delete the ones you don't want.

You may also need to add a section like the below into the `android {}` section of the `app\build.gradle` file (alongside `compileOptions`):
```
splits {
    abi {
        enable true
        reset()
        include 'armeabi-v7a', 'arm64-v8a'
        universalApk false
    }
}
```
(from https://stackoverflow.com/a/58077427)

**Comment by hadisn** [comment]
I did it, but how to package aab now? Everything changed in app\build.gradle resets to default when I start command to package aab?

**Comment by ajwfrost** [comment]
@hadisn once you've got this folder, you can open it using Android Studio and then Build -> "Build Bundle/APK" or "Generate Signed Bundle/APK"

thanks

**Comment by hadisn** [comment]
Thanks, i have got it work withoud AdMob ANE, but when ANE is included i got this error in android studio when debuging: 

E/AndroidRuntime: FATAL EXCEPTION: Thread-12
    Process: air.com.gamblershome.discovery, PID: 4727
    java.lang.NoClassDefFoundError: com.google.android.gms.common.R$string
        at com.google.android.gms.common.api.internal.GoogleServices.<init>(Unknown Source:3)
        at com.google.android.gms.common.api.internal.GoogleServices.initialize(Unknown Source:44)
        at com.google.android.gms.internal.measurement.zzx.zzf(com.google.android.gms:play-services-measurement-sdk-api@@17.1.0:44)
        at com.google.android.gms.internal.measurement.zzx.<init>(com.google.android.gms:play-services-measurement-sdk-api@@17.1.0:22)
        at com.google.android.gms.internal.measurement.zzx.zza(com.google.android.gms:play-services-measurement-sdk-api@@17.1.0:6)
        at com.google.android.gms.measurement.api.AppMeasurementSdk.getInstance(com.google.android.gms:play-services-measurement-sdk-api@@17.1.0:2)
        at com.google.android.gms.internal.ads.zzamm.zze(com.google.android.gms:play-services-ads-lite@@19.3.0:41)
        at com.google.android.gms.internal.ads.zzaml.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/pozirk/ads/admob/R$string;
        at com.google.android.gms.common.R$string.<clinit>(R.java:8)
        at com.google.android.gms.common.GooglePlayServicesUtilLight.isGooglePlayServicesAvailable(Unknown Source:8)
        at com.google.android.gms.common.GoogleApiAvailabilityLight.isGooglePlayServicesAvailable(Unknown Source:5)
        at com.google.android.gms.internal.ads.zzbat.zzd(com.google.android.gms:play-services-ads-lite@@19.3.0:67)
        at com.google.android.gms.internal.ads.zzwf.zzd(com.google.android.gms:play-services-ads-lite@@19.3.0:35)
        at com.google.android.gms.internal.ads.zzyv.zzg(com.google.android.gms:play-services-ads-lite@@19.3.0:160)
        at com.google.android.gms.internal.ads.zzyv.zza(com.google.android.gms:play-services-ads-lite@@19.3.0:18)
        at com.google.android.gms.ads.MobileAds.initialize(com.google.android.gms:play-services-ads-lite@@19.3.0:6)
        at com.google.android.gms.ads.MobileAds.initialize(com.google.android.gms:play-services-ads-lite@@19.3.0:8)
        at com.pozirk.ads.admob.manager.AdMobManager.<init>(AdMobManager.java:48)
        at com.pozirk.ads.admob.context.ExtensionContext.getAdMobMan(ExtensionContext.java:65)
        at com.pozirk.ads.admob.function.InitFunction.call(InitFunction.java:33)
        at com.adobe.air.Entrypoints.EntryMainWrapper(Native Method)
        at com.adobe.air.Entrypoints.EntryMain(Entrypoints.java:143)
        at com.adobe.air.AndroidActivityWrapper.LaunchApplication(AndroidActivityWrapper.java:1222)
        at com.adobe.air.AndroidActivityWrapper.launchApplication(AndroidActivityWrapper.java:1509)
        at com.adobe.air.AndroidActivityWrapper$1.run(AndroidActivityWrapper.java:1489)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.pozirk.ads.admob.R$string" on path: DexPathList[[zip file "/data/app/~~4OZcK8iAh64y0-lJnlBUsg==/air.com.gamblershome.discovery-mEbUN0SVx0kCMUctWEyJLw==/base.apk"],nativeLibraryDirectories=[/data/app/~~4OZcK8iAh64y0-lJnlBUsg==/air.com.gamblershome.discovery-mEbUN0SVx0kCMUctWEyJLw==/lib/arm64, /data/app/~~4OZcK8iAh64y0-lJnlBUsg==/air.com.gamblershome.discovery-mEbUN0SVx0kCMUctWEyJLw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.android.gms.common.R$string.<clinit>(R.java:8) 
        at com.google.android.gms.common.GooglePlayServicesUtilLight.isGooglePlayServicesAvailable(Unknown Source:8) 
        at com.google.android.gms.common.GoogleApiAvailabilityLight.isGooglePlayServicesAvailable(Unknown Source:5) 
        at com.google.android.gms.internal.ads.zzbat.zzd(com.google.android.gms:play-services-ads-lite@@19.3.0:67) 
        at com.google.android.gms.internal.ads.zzwf.zzd(com.google.android.gms:play-services-ads-lite@@19.3.0:35) 
        at com.google.android.gms.internal.ads.zzyv.zzg(com.google.android.gms:play-services-ads-lite@@19.3.0:160) 
        at com.google.android.gms.internal.ads.zzyv.zza(com.google.android.gms:play-services-ads-lite@@19.3.0:18) 
        at com.google.android.gms.ads.MobileAds.initialize(com.google.android.gms:play-services-ads-lite@@19.3.0:6) 
        at com.google.android.gms.ads.MobileAds.initialize(com.google.android.gms:play-services-ads-lite@@19.3.0:8) 
        at com.pozirk.ads.admob.manager.AdMobManager.<init>(AdMobManager.java:48) 
        at com.pozirk.ads.admob.context.ExtensionContext.getAdMobMan(ExtensionContext.java:65) 
        at com.pozirk.ads.admob.function.InitFunction.call(InitFunction.java:33) 
        at com.adobe.air.Entrypoints.EntryMainWrapper(Native Method) 
        at com.adobe.air.Entrypoints.EntryMain(Entrypoints.java:143) 
        at com.adobe.air.AndroidActivityWrapper.LaunchApplication(AndroidActivityWrapper.java:1222) 
        at com.adobe.air.AndroidActivityWrapper.launchApplication(AndroidActivityWrapper.java:1509) 
        at com.adobe.air.AndroidActivityWrapper$1.run(AndroidActivityWrapper.java:1489) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8633) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by ajwfrost** [comment]
@hadisn sorry for the delay -> when you see this:
```
java.lang.NoClassDefFoundError: com.google.android.gms.common.R$string
```
it's because the AAB format changed how resources were packaged in from ANEs, so I think you just need to get the latest version of the AdMob ANE to resolve this one...

thanks

**Comment by hadisn** [comment]
@ajwfrost thank you, I downloaded ANE and trying package it by myself because guys who nade it doesnt support it anymore, I figured that is problem with ANE but i dont know exactly where, hope I will solve this. If there is someone who is interested in this to help me, it would be good 🙂

**Comment by ajwfrost** [comment]
Ah - so actually if you have got this extracted into an Android Studio project, you may be able to solve it from there... as the ANEs will have been unpacked as part of that process... 

If you look in the AndroidStudioProject folder, do you see a subfolder called something like "com.google.android.gms.common", or other similarly named (com.google.android.something) folders?

There should then be, under these, a folder structure like "src\main\res\values" and then an XML file that contains the string values.

I think it may be that the top level folder name isn't quite right e.g. it may be called "com.google.android.common" and needs to be renamed to "com.google.android.gms.common" or similar...  If you do make any changes to that folder name, you need to also update the top-level 'settings.gradle' file where it lists the subfolders to include, and the 'app\build.gradle' file will have a depencency line for it starting `implementation project(":...")`

thanks

**Comment by hadisn** [comment]
Yes, I have opened it in  Android Studio and I will try your suggestion, thank you very much, I really appreciate your help.

**Comment by hadisn** [comment]
I can't find those folders, here is screenshot of project in android studio
![image](https://user-images.githubusercontent.com/2553775/143426719-22ce673f-18a5-482c-a501-965aca98c2d6.png)

**Comment by ajwfrost** [comment]
That looks like the Android Studio project for the ANE itself? (library project, plus some configuration that isn't something we generate). I had been meaning that if you use ADT to build your application, it should then generate the AndroidStudioProject folder and if you open that project in Android Studio, you should see the 'app' plus other folders that are created based on the included ANEs. 

thanks

**Comment by hadisn** [comment]
As I mentioned before, I successfully packaged application with android studio from "AndroidStudioProject" but without ANE, now trying to make ANE compatible with it...

Yes this is project for ANE (https://github.com/pozirk/ANEAdMob)

**Comment by ajwfrost** [comment]
Yes - so I had been responding to a notification I got via email but I can't see the post in this thread any more, something may have been going a bit funny with github (or emails) perhaps.. sorry if I misunderstood! I thought that you had packaged up a bundle with the ANE and were then getting a "class not found" error due to one of the resources from the ANE not being packaged into the app bundle properly..

There may be some guidance from the below site which could help particularly if there are issues with resources:
https://airsdk.dev/docs/tutorials/platform/android/custom-resources

thanks

**Comment by hadisn** [comment]
I never solved this, is there anyone who knows ANE that works with current Adobe Air SDK, now even apk crashes on startup with AIR 33.1.1.743.

I don't know what to do anymore, too much time i spend to this so I can't focus to developing game...

**Comment by mumeka** [comment]
I had this error when packaging aab: 
`
java.lang.NoClassDefFoundError: com.google.android.gms.common.R$string`

I solved it by updating following ane to newer version:
ANE-GooglePlayServices-26.5.0 (distriqt) to ANE-GooglePlayServices-27.0.2

Errorstack was indicating measurement API giving the error. It is part of GooglePlayServices ANE. So updating it fixed the error. I hope this will help someone else.

**Comment by marchbold** [comment]
@mumeka Yeah that issue was identified and fixed a while ago: https://github.com/airsdk/Adobe-Runtime-Support/issues/957 Always worth checking for the latest dependency extensions.
