### ISSUE TITLE
Having trouble loading a file on Android

### ISSUE THREAD

**Issue by coelhonix** [airsdk/Adobe-Runtime-Support#1388]
I'm trying to use Firebase TestLab to test our application. When TestLab runs a game loop test it sends a file url so we can use it to output our test results (content://com.google.samples.apps.gameloopmanager/files/results0.json). So on my actionscript we got:
`protected function loadLogJson(url:String):void`
`		{`
`			var urlLoader:URLLoader = new URLLoader();`
`			urlLoader.addEventListener(Event.COMPLETE, completeHandler);`
`			urlLoader.load(new URLRequest(url)); //url is content://com.google.samples.apps.gameloopmanager/files/results0.json`
`		}`

And it is resulting in the following error:

> Error #2044: Unhandled ioError:. text=Error #2032: Stream Error. URL: content://com.google.samples.apps.gameloopmanager/files/results0.json

Am I doing something wrong here?

**Comment by toysonlocation** [comment]
This is new to me, "content://"   What protocol is that?

**Comment by marchbold** [comment]
`content://` is an android scheme used to access content (files etc) via content providers. This is the more modern approach of accessing files on Android as it runs through the security / sharing model.

I know we use this a lot in our native extensions, but I'm not sure how AIR handles it currently. I can probably put together a quick ANE for you to load this content if it's something you need urgently.

**Comment by toysonlocation** [comment]
This looks like the relevant output...

```
11-24 22:32:34.135  4554  4580 D DeviceStateHelper: Audo mode: 0
11-24 22:32:34.528 21036 21036 I com.distriqt.MediaPlayer: MediaPlayerController::setting volume control stream to STREAM_MUSIC
11-24 22:32:34.528 21036 21036 I com.distriqt.MediaPlayer: MediaPlayerController::createPlayer( [null, false, true, controls:embedded, 0, 0, 750, 1500, false] )
11-24 22:32:34.529 21036 21036 I com.distriqt.MediaPlayer: MediaPlayer::createPlayer( [null, false, true, controls:embedded, 0, 0, 750, 1500, false]
11-24 22:32:34.535 21036 21036 I com.distriqt.MediaPlayer: ExoPlayerFragment::onCreateView()
11-24 22:32:34.537 21036 21036 W System.err: android.view.InflateException: Binary XML file line #7 in air.com.toyl.testing:layout/distriqt_mediaplayer_ep_layout_embedded: Binary XML file line #7 in air.com.toyl.testing:layout/distriqt_mediaplayer_ep_layout_embedded: Error inflating class com.distriqt.extension.mediaplayer.player.exoplayer.CustomExoPlayerView
11-24 22:32:34.537 21036 21036 W System.err: Caused by: android.view.InflateException: Binary XML file line #7 in air.com.toyl.testing:layout/distriqt_mediaplayer_ep_layout_embedded: Error inflating class com.distriqt.extension.mediaplayer.player.exoplayer.CustomExoPlayerView
11-24 22:32:34.538 21036 21036 W System.err: Caused by: java.lang.reflect.InvocationTargetException
11-24 22:32:34.538 21036 21036 W System.err:    at java.lang.reflect.Constructor.newInstance0(Native Method)
11-24 22:32:34.538 21036 21036 W System.err:    at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
11-24 22:32:34.538 21036 21036 W System.err:    at android.view.LayoutInflater.createView(LayoutInflater.java:852)
11-24 22:32:34.538 21036 21036 W System.err:    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
11-24 22:32:34.538 21036 21036 W System.err:    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
11-24 22:32:34.538 21036 21036 W System.err:    at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
11-24 22:32:34.538 21036 21036 W System.err:    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
11-24 22:32:34.538 21036 21036 W System.err:    at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
11-24 22:32:34.538 21036 21036 W System.err:    at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
11-24 22:32:34.538 21036 21036 W System.err:    at com.distriqt.extension.mediaplayer.player.exoplayer.ExoPlayerFragment.onCreateView(ExoPlayerFragment.java:162)
11-24 22:32:34.538 21036 21036 W System.err:    at android.app.Fragment.performCreateView(Fragment.java:2505)
11-24 22:32:34.538 21036 21036 W System.err:    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1303)
11-24 22:32:34.538 21036 21036 W System.err:    at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
11-24 22:32:34.538 21036 21036 W System.err:    at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
11-24 22:32:34.538 21036 21036 W System.err:    at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
11-24 22:32:34.538 21036 21036 W System.err:    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
11-24 22:32:34.538 21036 21036 W System.err:    at android.app.FragmentManagerImpl$1.run(FragmentManager.java:742)
11-24 22:32:34.538 21036 21036 W System.err:    at android.os.Handler.handleCallback(Handler.java:938)
11-24 22:32:34.538 21036 21036 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
11-24 22:32:34.538 21036 21036 W System.err:    at android.os.Looper.loop(Looper.java:223)
11-24 22:32:34.538 21036 21036 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:7664)
11-24 22:32:34.538 21036 21036 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
11-24 22:32:34.538 21036 21036 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
11-24 22:32:34.538 21036 21036 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
11-24 22:32:34.538 21036 21036 W System.err: Caused by: java.lang.NoSuchFieldError: No static field PlayerView of type [I in class Lcom/google/android/exoplayer2/ui/R$styleable; or its superclasses (declaration of 'com.google.android.exoplayer2.ui.R$styleable' appears in /data/app/~~0SxCYPrMPcAjwhX1vkoYRw==/air.com.toyl.testing-kjR7EVAQnqBONmrT8d6i3Q==/base.apk)
11-24 22:32:34.538 21036 21036 W System.err:    at com.google.android.exoplayer2.ui.PlayerView.<init>(PlayerView.java:306)
11-24 22:32:34.538 21036 21036 W System.err:    at com.google.android.exoplayer2.ui.PlayerView.<init>(PlayerView.java:265)
11-24 22:32:34.538 21036 21036 W System.err:    at com.distriqt.extension.mediaplayer.player.exoplayer.CustomExoPlayerView.<init>(CustomExoPlayerView.java:45)
11-24 22:32:34.538 21036 21036 W System.err:    ... 24 more
11-24 22:32:34.539 21036 21036 I com.distriqt.MediaPlayer: ExoPlayerFragment::load(): trying uri
11-24 22:32:34.539 21036 21036 I com.distriqt.MediaPlayer: ExoPlayerFragment::loading from https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/1080/Big_Buck_Bunny_1080_10s_1MB.mp4
11-24 22:32:34.542 21036 21036 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
11-24 22:32:34.543 21036 21036 W System.err:    at com.distriqt.extension.mediaplayer.player.exoplayer.ExoPlayerFragment.updateFullscreenButtonState(ExoPlayerFragment.java:739)
11-24 22:32:34.543 21036 21036 W System.err:    at com.distriqt.extension.mediaplayer.player.exoplayer.ExoPlayerFragment.onActivityCreated(ExoPlayerFragment.java:227)
11-24 22:32:34.543 21036 21036 W System.err:    at android.app.Fragment.performActivityCreated(Fragment.java:2514)
11-24 22:32:34.543 21036 21036 W System.err:    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1323)
11-24 22:32:34.543 21036 21036 W System.err:    at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
11-24 22:32:34.543 21036 21036 W System.err:    at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
11-24 22:32:34.543 21036 21036 W System.err:    at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
11-24 22:32:34.543 21036 21036 W System.err:    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
11-24 22:32:34.543 21036 21036 W System.err:    at android.app.FragmentManagerImpl$1.run(FragmentManager.java:742)
11-24 22:32:34.543 21036 21036 W System.err:    at android.os.Handler.handleCallback(Handler.java:938)
11-24 22:32:34.543 21036 21036 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
11-24 22:32:34.543 21036 21036 W System.err:    at android.os.Looper.loop(Looper.java:223)
11-24 22:32:34.543 21036 21036 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:7664)
11-24 22:32:34.543 21036 21036 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
11-24 22:32:34.543 21036 21036 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
11-24 22:32:34.543 21036 21036 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
11-24 22:32:34.543 21036 21036 I com.distriqt.MediaPlayer: ExoPlayerFragment::onResume()
11-24 22:32:34.546 21036 21036 I air.com.toyl.testing: [Event type="mediaplayer:ready" bubbles=false cancelable=false eventPhase=2]
11-24 22:32:34.549 21036 21036 I com.distriqt.MediaPlayer: ExoPlayerFragment::setFullscreen( true, true )
11-24 22:32:34.549 21036 21036 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
11-24 22:32:34.549 21036 21036 W System.err:    at com.distriqt.extension.mediaplayer.player.exoplayer.ExoPlayerFragment.updateFullscreenButtonState(ExoPlayerFragment.java:739)
11-24 22:32:34.549 21036 21036 W System.err:    at com.distriqt.extension.mediaplayer.player.exoplayer.ExoPlayerFragment.setFullscreen(ExoPlayerFragment.java:675)
11-24 22:32:34.549 21036 21036 W System.err:    at com.distriqt.extension.mediaplayer.player.MediaPlayer.setFullscreen(MediaPlayer.java:181)
11-24 22:32:34.549 21036 21036 W System.err:    at com.distriqt.extension.mediaplayer.functions.mediaplayerview.SetFullscreenFunction.call(SetFullscreenFunction.java:47)
11-24 22:32:34.549 21036 21036 W System.err:    at com.adobe.air.customHandler.callTimeoutFunction(Native Method)
11-24 22:32:34.549 21036 21036 W System.err:    at com.adobe.air.customHandler.handleMessage(customHandler.java:28)
11-24 22:32:34.549 21036 21036 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:106)
11-24 22:32:34.549 21036 21036 W System.err:    at android.os.Looper.loop(Looper.java:223)
11-24 22:32:34.549 21036 21036 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:7664)
11-24 22:32:34.549 21036 21036 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
11-24 22:32:34.549 21036 21036 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
11-24 22:32:34.549 21036 21036 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
11-24 22:32:34.602   914   998 I CHRE    : @ 262132.879: [AR] inconsistent: 41.176471

```

**Comment by coelhonix** [comment]
> I know we use this a lot in our native extensions, but I'm not sure how AIR handles it currently. I can probably put together a quick ANE for you to load this content if it's something you need urgently.

That would be great!

**Comment by marchbold** [comment]
Okay, I'll put together an ANE that reads the text from the content url and returns it. Will that be sufficient?

**Comment by marchbold** [comment]
I haven't had a chance to test or document this yet but here is the ane:

https://github.com/airnativeextensions/ANE-ContentProvider

```as3
ContentProvider.instance.addEventListener( DataEvent.DATA, dataHandler );
ContentProvider.instance.readFromContentUrl( "content://" );
		
function dataHandler( event:DataEvent ):void
{
	trace( event.data );
}
```

**Comment by coelhonix** [comment]
Unfortunately I wasn't able to use this ANE to open the file :/ I did exactly like your example, but no data was loaded

Also, my problem was that I need to open the file and output data on it, with this ANE should I be able to do it?

**Comment by coelhonix** [comment]
And thanks a lot for being available to help me :)

**Comment by marchbold** [comment]
What happened with the extension? Could you post the logs from the device? 

Do you need to write to the file as well? That could be a bit more involved.

**Comment by coelhonix** [comment]
Yes, I need to write to the file, because it will be the output of our tests.

Through the log I noticed that what I got is a permission denial.

```
12-06 11:16:01.861  3436  3451 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading android.support.v4.content.FileProvider uri content://com.google.samples.apps.gameloopmanager/files/results0.json from pid=4477, uid=10161 requires the provider be exported, or grantUriPermission()
12-06 11:16:01.861  3436  3451 E DatabaseUtils:         at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:608)
12-06 11:16:01.861  3436  3451 E DatabaseUtils:         at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:483)
12-06 11:16:01.861  3436  3451 E DatabaseUtils:         at android.content.ContentProvider$Transport.enforceFilePermission(ContentProvider.java:474)
12-06 11:16:01.861  3436  3451 E DatabaseUtils:         at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:419)
12-06 11:16:01.861  3436  3451 E DatabaseUtils:         at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:313)
12-06 11:16:01.861  3436  3451 E DatabaseUtils:         at android.os.Binder.execTransact(Binder.java:565)
12-06 11:16:01.861  4477  4477 W System.err: java.lang.SecurityException: Permission Denial: reading android.support.v4.content.FileProvider uri content://com.google.samples.apps.gameloopmanager/files/results0.json from pid=4477, uid=10161 requires the provider be exported, or grantUriPermission()
12-06 11:16:01.863  4477  4477 W System.err:    at android.os.Parcel.readException(Parcel.java:1684)
12-06 11:16:01.863  4477  4477 W System.err:    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
12-06 11:16:01.863  4477  4477 W System.err:    at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
12-06 11:16:01.863  4477  4477 W System.err:    at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692)
12-06 11:16:01.863  4477  4477 W System.err:    at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1147)
12-06 11:16:01.863  4477  4477 W System.err:    at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:984)
12-06 11:16:01.863  4477  4477 W System.err:    at android.content.ContentResolver.openInputStream(ContentResolver.java:704)
12-06 11:16:01.863  4477  4477 W System.err:    at com.distriqt.extension.contentprovider.controller.ContentProviderController.readFromContentUrl(ContentProviderController.java:82)
12-06 11:16:01.863  4477  4477 W System.err:    at com.distriqt.extension.contentprovider.functions.ReadFromContentUrlFunction.call(ReadFromContentUrlFunction.java:37)
12-06 11:16:01.863  4477  4477 W System.err:    at com.adobe.air.customHandler.callTimeoutFunction(Native Method)
12-06 11:16:01.863  4477  4477 W System.err:    at com.adobe.air.customHandler.handleMessage(customHandler.java:28)
12-06 11:16:01.863  4477  4477 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:102)
12-06 11:16:01.863  4477  4477 W System.err:    at android.os.Looper.loop(Looper.java:154)
12-06 11:16:01.863  4477  4477 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6138)
12-06 11:16:01.863  4477  4477 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
12-06 11:16:01.863  4477  4477 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
12-06 11:16:01.863  4477  4477 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
```

**Comment by marchbold** [comment]
Have you got a reference for what you are trying to do, is `com.google.samples.apps.gameloopmanager` your application or are you trying to communicate with one of the google sample apps?

**Comment by coelhonix** [comment]
I'm trying to communicate with it.
When I run a game loop test, this application invoke my app and send to it the url to the file, so I can write the output of my test. When it will be possible to write to this file, I'll be able to use firelab's test lab to run multiple tests and analyze all resulting files. 
I just have [their documentation](https://firebase.google.com/docs/test-lab/android/game-loop?authuser=0) as reference

**Comment by marchbold** [comment]
Yeah okay, you might have to contact our [custom development team](airnativeextensions@distriqt.com) if you need some help on this, looks like a bit more than just a quick content provider read.
