### ISSUE TITLE
Failed to package AIR application

### ISSUE THREAD

**Issue by xxxVBxxx** [airsdk/Adobe-Runtime-Support#1431]
Hi,

When I try to package an air application it throws an exception. 
This issue popped up after I updated the Adverts.ane from Distriqt.
AIR SDK: 33.1.1.674

Thanks in advance!

Failed to package AIR application app.apk:
Exception in thread "Thread-0"
java.lang.NullPointerException
at com.harman.adt.a.a(a.java)
at com.harman.adt.a.c(a.java)
at com.harman.adt.a.run(a.java)
at java.lang.Thread.run(Thread.java:745)

**Comment by ajwfrost** [comment]
If that's in the com.harman classes then it shouldn't be anything to do with the ANE .. can you please try
`adt -license`
and let us know if that works? And also do you have internet connectivity on this machine?

thanks

**Comment by xxxVBxxx** [comment]
> If that's in the com.harman classes then it shouldn't be anything to do with the ANE .. can you please try `adt -license` and let us know if that works? And also do you have internet connectivity on this machine?
> 
> thanks
Thanks for replying

adt -license result

AIR Developer Tool version 33.1.1.674
Exception in thread "Thread-0" java.lang.NullPointerException
        at com.harman.adt.a.a(a.java)
        at com.harman.adt.a.c(a.java)
        at com.harman.adt.a.run(a.java)
        at java.lang.Thread.run(Thread.java:748)
WARNING: license file detected but this is invalid and will be ignored. Contact adobe.support@harman.com for support
License file was present but not valid
DeveloperID=null


I checked the internet conectivity. it's working properly.

**Comment by ajwfrost** [comment]
Okay thanks -> can you please replace your adt.lic file with the one that you were originally sent from us? It looks like something has corrupted this.

We can make changes to the code in ADT to make it a little clearer what's happened...

thanks

**Comment by xxxVBxxx** [comment]
Thanks a lot @ajwfrost
After replacing the adt, license is completely fine now. 

AIR Developer Tool version 33.1.1.674
License file is present and valid
DeveloperID=772870cb-64a0-402e-a6fb-377d532005a9

But I'm still unable to package the application. After replacing the licence file it now throws this exception.

Failed to package AIR application app.apk:
				dx tool failed:Error: Program type already present: com.google.auto.value.extension.memoized.Memoized
				Compilation failed
