### ISSUE TITLE
bad error when publishing app using adobe animate 

### ISSUE THREAD

**Issue by atiani** [airsdk/Adobe-Runtime-Support#1516]
AIR SDK version: 33.1.1.731
Device OS: andriod
Device version: 30
Development IDE:adobe animate
Development OS:windows
i have this error when i published app
below : the error :
[https://drive.google.com/file/d/1CiKXzA-nW_1ebCA2nuIJV-2-m959yG7Z/view?usp=sharing](url)

**Comment by wmtj** [comment]
I have the same problem too.

**Comment by MESepehr** [comment]
I have the same problem.

**Comment by blueredcz** [comment]
I have the same problem, and if the SDK is not placed in the folder "AIR33.1" it hangs on this error.
![Snímek obrazovky 2022-01-06 223939](https://user-images.githubusercontent.com/44625708/148458315-21382efd-274c-44b4-80a4-7502da7ef3a6.png)

**Comment by bobrokrol** [comment]
error while packaging .aab / .apk
unexpected failure: zip file closed
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(Unknown Source)
        at java.util.zip.ZipFile.getEntry(Unknown Source)
        at com.adobe.air.apk.AABPackager.processExtensions(AABPackager.java)
        at com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
        at com.adobe.air.apk.AABPackager.createPackage(AABPackager.java)
        at com.adobe.air.ADT.parseArgsAndGo(ADT.java)
        at com.adobe.air.ADT.run(ADT.java)
        at com.adobe.air.ADT.main(ADT.java)

**Comment by jimmymjing** [comment]
Same problem!

**Comment by ajwfrost** [comment]
Okay thanks - one of our test cases had been mis-edited which meant we missed this one :-(  
Will get an update out asap with this fixed..
thanks

**Comment by moazatiani** [comment]
ok thank you about that

**Comment by itlancer** [comment]
For me it fixed with latest AIR SDK 33.1.1.743.
Thanks!
