### ISSUE TITLE
Error building legacy apk in 33.1.1.743

### ISSUE THREAD

**Issue by ptysbilbo** [airsdk/Adobe-Runtime-Support#1584]
Hi,
I'm trying to build an 64bit apk using AIR 33.1.1.743. I put the following line into the desctiptor.
`<BuildLegacyAPK>true</BuildLegacyAPK>`

I'm getting an error:
> unexpected failure: For input string: ""
> java.lang.NumberFormatException: For input string: ""
>         at java.lang.NumberFormatException.forInputString(Unknown Source)
>         at java.lang.Integer.parseInt(Unknown Source)
>         at com.adobe.air.apk.ResourceBytecodeGenerator.generateFromRFile(ResourceBytecodeGenerator.java)
>         at com.adobe.air.apk.APKOutputStream.a(APKOutputStream.java)
>         at com.adobe.air.apk.APKOutputStream.a(APKOutputStream.java)
>         at com.adobe.air.apk.APKOutputStream.addApplicationDescriptor(APKOutputStream.java)
>         at com.adobe.air.ApplicationPackager.addSpecialFiles(ApplicationPackager.java)
>         at com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java) 
>         at com.adobe.air.ADT.parseArgsAndGo(ADT.java)
>         at com.adobe.air.ADT.run(ADT.java)
>         at com.adobe.air.ADT.main(ADT.java)

I can succesfully build an apk using AIR 33.1.1.633 (of course without `<BuildLegacyAPK>true</BuildLegacyAPK>`)

I can't upgrade to Java 11 because my app is quite old and using 1024bit certificate. Last time I checked newer versions required 2048bit cert.
Or maybe there is a way to use my old certicate with newer Java, or change certificate to existing app?

Thanks

**Comment by shaymolho** [comment]
@ajwfrost we also encounter this, any idea why?

**Comment by ajwfrost** [comment]
Hi - sorry, missed this one to start with. The mechanism changed in build 713:
`github-274: Updating Java bytecode generator to cope with Android styleable resources`
so it seems there's an issue with it trying to handle some of this code still. The bytecode generator is used as a fallback if it can't find an appropriate JDK so you may be able to work around this if you can provide a JAVA_HOME variable that points to a JDK (as opposed to a JRE .. i.e. we need to use the "javac" tool to turn the generated R.java code into compiled Java/Dex code...)

To fix this actual bug though, we can see if we can reproduce this problem using the PushNotifications ANE...

thanks

**Comment by Policy56** [comment]
Hi,

I got nearly the same error since i use Air 33.1 and tried to build a 64bit app.
I didn't use PushNotifications ANE

``` 
java.lang.Exception: 
unexpected failure: For input string: "8G"
java.lang.NumberFormatException: For input string: "8G"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Long.parseLong(Unknown Source)
	at java.lang.Long.parseLong(Unknown Source)
	at com.adobe.air.apk.AABOutputStream.parseXmxVal(AABOutputStream.java)
	at com.adobe.air.apk.AABOutputStream.addJavaMemoryOptions(AABOutputStream.java)
	at com.adobe.air.apk.AABOutputStream.buildGradle(AABOutputStream.java)
	at com.adobe.air.apk.AABPackager.renameOutput(AABPackager.java)
	at com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
	at com.adobe.air.apk.AABPackager.createPackage(AABPackager.java)
	at com.adobe.air.ADT.parseArgsAndGo(ADT.java)
	at com.adobe.air.ADT.run(ADT.java)
	at com.adobe.air.ADT.main(ADT.java)
``` 

My JAVA_HOME path has been set to : C:\Program Files\Java\jdk-11.0.11

Thanks

**Comment by ajwfrost** [comment]
Can you please sue 8192M...? We'll need to add a "G" parsing option to it though :-)
(and reading back .. this `parseXmxVal` failure is going to be unrelated to the original issue here...)

**Comment by ajwfrost** [comment]
@shaymolho @ptysbilbo  just checking with the original description -> if you're using the latest distriqt ANE and the latest AIR SDK, building via Gradle, I would expect these problems to have gone away now. Please don't use the `BuildLegacyAPK` setting now, I don't think it works properly with the ANEs and the latest Android SDKs.

thanks

**Comment by ajwfrost** [comment]
@Policy56 actually -> could you please try lower-case values? So `8192m` or `8g` should both work...

**Comment by Policy56** [comment]
> @Policy56 actually -> could you please try lower-case values? So `8192m` or `8g` should both work...

Thank you @ajwfrost, the lower-case values `8192m' works! Have a good day !
