### ISSUE TITLE
Crash: Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference

### ISSUE THREAD

**Issue by Dima107** [airsdk/Adobe-Runtime-Support#1606]
AIR SDK 33.1.1.620 - 713
Android:
Android 9 - 64%
Android 8 - 35%
Android 10 <1%
I can't repicate this. It's log from Crashlytics
I attached file with threads codes
@marchbold I see code from you Firebase, Crashlitycs, GooglePlayServices, okhttp into threads. Can you look at this please?
 
 Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:275)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:20967)
       at android.view.ViewGroup.layout(ViewGroup.java:6440)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:20967)
       at android.view.ViewGroup.layout(ViewGroup.java:6440)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
       at android.view.View.layout(View.java:20967)
       at android.view.ViewGroup.layout(ViewGroup.java:6440)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:955)
       at android.view.View.layout(View.java:20967)
       at android.view.ViewGroup.layout(ViewGroup.java:6440)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3092)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2779)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1863)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8072)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
       at android.view.Choreographer.doCallbacks(Choreographer.java:723)
       at android.view.Choreographer.doFrame(Choreographer.java:658)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:7000)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
[threads.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/7973285/threads.txt)

**Comment by marchbold** [comment]
The threads just all look like normal background threads relating to crashlytics so not sure they are causing the issue? I don't believe crashytics will ever call `View.getVisibility()` so I can't imagine that is the cause here. 

The ZygoteInit at the beginning of that stack trace normally is associated with Android application startup, so are you doing any visibility checks or something at startup? Might be something @ajwfrost needs to look into with the AIR startup ?

**Comment by Dima107** [comment]
I don't think I check vsibility by myself. I call only one thing similar to "visibily" in the game - AdView show() and hide(). But I don't do it on startup.

Also I wanna note that I see just "java.lang.NullPointerException" into Google Play Console without any words about "android.view.View.getVisibility()"

**Comment by Dima107** [comment]
I wanna update crash info. We have the same crash for Android 10. Differece is just in line number
Android 10 - 99%


Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:284)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:21927)
       at android.view.ViewGroup.layout(ViewGroup.java:6260)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:21927)
       at android.view.ViewGroup.layout(ViewGroup.java:6260)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
       at android.view.View.layout(View.java:21927)
       at android.view.ViewGroup.layout(ViewGroup.java:6260)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
       at android.view.View.layout(View.java:21927)
       at android.view.ViewGroup.layout(ViewGroup.java:6260)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3088)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2598)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1726)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7610)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1052)
       at android.view.Choreographer.doCallbacks(Choreographer.java:875)
       at android.view.Choreographer.doFrame(Choreographer.java:810)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1037)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7386)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1072)

**Comment by ajwfrost** [comment]
Can I check what this means:
> Android 10 - 99%

As if that means they're seeing this in 99% of attempts, then I would hope it's reproducible..! The only thing I can think of from that call stack is if we've got a view added to the layout which is null - or if we change the number of children while their function is running, perhaps in response to a layout callback.

We can check on this but any info on the devices etc would be good. Can you please confirm whether you have the HARMAM/AIR splash screen being displayed, as this makes a difference to the view stack..?

thanks

**Comment by ajwfrost** [comment]
So looking at the call stack:
`android.view.ViewRootImpl.performLayout` calls `android.widget.FrameLayout.onLayout(FrameLayout.java:270)`
which makes sense: at the root of our activity we have `setContentView` with a FrameLayout object.

This triggers the ViewGroup layout which goes through each View and then the call here is triggered to:
`android.widget.LinearLayout.onLayout(LinearLayout.java:1582)`

It looks like we have three locations where LinearLayout is being used:
1) Listen error dialog
2) Remote debugger dialog
3) Expandable file chooser

So if one of these uses a FrameLayout which also then contains a FrameLayout but where one of the elements ends up null (or if the loop could end up out of bounds by the group changing), then we have a culprit..

Listen error dialog -> just has a text view
Remote debugger dialog -> has a text view and an edit text view
Expandable file chooser -> loads a view from resources: either LinearLayout containing CheckBox and LinearLayout with 2x TextView; or just a LinearLayout containing 2x TextView

So it doesn't seem to be this. The other thing we could be adding is a web view .. or I just noticed the fact you're adding some ad view ..? 

Looking at the Android source for this part, it's not that you're calling show/hide or anything, it's just the automatic laying out of elements and it's trying to decide upon placement of elements so it needs to know which are invisible and therefore don't impact the layout.

Are you able to reproduce this yourselves btw? If so can you try excluding the advertising bit, or can we have the APK to take a look?

thanks

**Comment by Dima107** [comment]
Unfortunately we can't reproduce this crash. I take all crash logs from Firebase Crashlitycs console and GoogplayConsole.

"Android 10 - 99%" it means that 99% of devices that were crashed had Android 10. (at android.widget.FrameLayout.layoutChildren(FrameLayout.java:284))
"Android 9 - 64%,  Android 8 - 35%" it means that 99% of device that were crashed had Android 8 or 9. (at android.widget.FrameLayout.layoutChildren(FrameLayout.java:275)))
I just wanted to say that crashes for Android 8, 9, and 10 has almost the same crashes. Difference is in line  number.

Our app is video game. We have these crashes on release version. So I don't this this is "Listen error dialog, Remote debugger dialog or Expandable file chooser".

We show ads. So I think it's can be source of these crashes. We'll try optimize usage of ads.

Thank you

**Comment by marchbold** [comment]
@Dima107 If you are adding an advert to your app too early (before AIR has completed initialising) I potentially could see a case where this occurs depending on how long AIR takes to init the main view. I'd suggest checking when you create / show your ad and try waiting until your AIR content is visible (added to stage event or something similar).

**Comment by Dima107** [comment]
We add Adverts after Starling complete initializing(Starling root class is added to Stage). I think Starling does it after AIR complete initialising

**Comment by marchbold** [comment]
Do you have any other native extensions that add UI to the app?

**Comment by Dima107** [comment]
1. InAppBilling. We request inapps on app launch to determine if user's GooglePlayPass is activated.
2. GameServices is temporary disabled.

**Comment by marchbold** [comment]
IAB or GameServices shouldn't add any view components related to the above error so I doubt those are the issue.

**Comment by jigtrap** [comment]
Hi, I know it's been more than two years since last post in this issue, I don't know the state of this issue, but Play Console has reported the same crash in my app.  

Is the more frequent crash my app  have with 72%  of the total Crash Rate 
![get_visibility](https://github.com/airsdk/Adobe-Runtime-Support/assets/84687012/f782a517-ab0a-48ef-bfcc-640db505bbbc)

@ajwfrost , please let me know if I should start another issue or this post already works.

(Log from Android Vitals)
Stack trace
1
Sample attributes:
motorola hawaiip (moto g22)
Android 12 (SDK 31)
Version: 1000093Occurred: 4 hours ago
Type
java.lang.NullPointerException
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:284)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:270)
  at android.view.View.layout (View.java:23305)
  at android.view.ViewGroup.layout (ViewGroup.java:6482)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:332)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:270)
  at android.view.View.layout (View.java:23305)
  at android.view.ViewGroup.layout (ViewGroup.java:6482)
  at android.widget.LinearLayout.setChildFrame (LinearLayout.java:1829)
  at android.widget.LinearLayout.layoutVertical (LinearLayout.java:1673)
  at android.widget.LinearLayout.onLayout (LinearLayout.java:1582)
  at android.view.View.layout (View.java:23305)
  at android.view.ViewGroup.layout (ViewGroup.java:6482)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:332)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:270)
  at com.android.internal.policy.DecorView.onLayout (DecorView.java:829)
  at android.view.View.layout (View.java:23305)
  at android.view.ViewGroup.layout (ViewGroup.java:6482)
  at android.view.ViewRootImpl.performLayout (ViewRootImpl.java:3866)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:3298)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:2235)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:9028)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1105)
  at android.view.Choreographer.doCallbacks (Choreographer.java:896)
  at android.view.Choreographer.doFrame (Choreographer.java:815)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1090)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:223)
  at android.os.Looper.loop (Looper.java:317)
  at android.app.ActivityThread.main (ActivityThread.java:7942)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:568)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1045)


Thanks in advance,
Aldo

**Comment by jigtrap** [comment]
Forgot to mention what I'm using :

Adobe AIR SDK 50.2.5.1
Anes: Distriqt  InAppBilling and Adverts
I dont use any dialog besides the ones related to the ANEs (including Google Play Admob Consent Message via UMP)
I started to use  InAppBilling and Adverts after Event.ADDED_TO_STAGE.

If you need any other information please just let me know.

Thanks in advance
Aldo

**Comment by jigtrap** [comment]
@ajwfrost , hello, any news about it?

**Comment by ajwfrost** [comment]
We haven't any way to find this one out or fix it I'm afraid, unless we're able to get a way to reproduce it. The crash happens purely within Android's own code, caused by a lack of defensive programming. At a guess there is some condition where a list is changing whilst they're iterating through it, which is something we might be able to find a workaround for - but equally, we might not, and the only definite fix for this would have to come from Google..

thanks

**Comment by jigtrap** [comment]
I understand, thanks.

**Comment by jigtrap** [comment]
Hi @Dima107, I hope you are doing great, since I am having trouble with te reported crash, I wanted to asked you if you found any workaround to prevent this happenging?, 

Thanks in advance.
Aldo

**Comment by httpwebmedia** [comment]
Hello guys, recently I updated my app with air sdk 51.1.3.7 and I have tons of this crash:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:284)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24791)
       at android.view.ViewGroup.layout(ViewGroup.java:6555)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24791)
       at android.view.ViewGroup.layout(ViewGroup.java:6555)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
       at android.view.View.layout(View.java:24791)
       at android.view.ViewGroup.layout(ViewGroup.java:6555)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:868)
       at android.view.View.layout(View.java:24791)
       at android.view.ViewGroup.layout(ViewGroup.java:6555)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4768)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4013)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2765)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10219)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1544)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1553)
       at android.view.Choreographer.doCallbacks(Choreographer.java:1109)
       at android.view.Choreographer.doFrame(Choreographer.java:994)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1527)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:257)
       at android.os.Looper.loop(Looper.java:368)
       at android.app.ActivityThread.main(ActivityThread.java:8839)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```
Any ideas on how to troubleshoot this? @udmv and @FliplineStudios have you run into this too?

**Comment by FliplineStudios** [comment]
@httpwebmedia I've seen that in our apps since at least AIR 33.1, not sure when exactly it started.  I was just checking our latest games that we've updated with 51.1.3.10 and I don't notice the crash amount increasing, it seems pretty consistent with what we saw in 33.1 or 50.2 (happening for around 1 or 2 users per day).  Are you seeing it jump up a lot higher than in previous releases?

**Comment by ajwfrost** [comment]
I'd be very interested if you are able to nail down some steps to reproduce this .. we've seen it periodically from a lot of people but as the call stacks never include any AIR code, and we've not seen it in all our own testing, we have no real way to investigate it. It would be lovely if Google added null-reference checking to avoid the crash, but they would probably say that we're doing something wrong to cause it (and they may be right, it's just tricky to find out what!!)

thanks

**Comment by premiumsB** [comment]
Andrew the thing is that we rarely (like never) are able to reproduce the crash with the ios simulator even if we take the right os and device that Xcode -- Crashes give us. So this is hard for us to replicate if we don't have any good way to debug ourself.

**Comment by marchbold** [comment]
If you are using any of our extensions, could you list them for me and I'll check on my usage of this? I'll see if there's potentially any issues there or at least checks I can put in place.

**Comment by httpwebmedia** [comment]
@marchbold here is my list:
```xml
    <extensionID>androidx.appcompat</extensionID>
    <extensionID>androidx.browser</extensionID>
    <extensionID>androidx.cardview</extensionID>
    <extensionID>androidx.constraintlayout</extensionID>
    <extensionID>androidx.core</extensionID>
    <extensionID>androidx.datastore</extensionID>
    <extensionID>androidx.exifinterface</extensionID>
    <extensionID>androidx.media3</extensionID>
    <extensionID>androidx.room</extensionID>
    <extensionID>androidx.vectordrawable</extensionID>
    <extensionID>androidx.webkit</extensionID>
    <extensionID>androidx.work</extensionID>
    <extensionID>com.bumptech.glide</extensionID>
    <extensionID>com.distriqt.Adverts</extensionID>
    <extensionID>com.distriqt.AppGroupDefaults</extensionID>
    <extensionID>com.distriqt.Application</extensionID>
    <extensionID>com.distriqt.ApplicationRater</extensionID>
    <extensionID>com.distriqt.Core</extensionID>
    <extensionID>com.distriqt.Firebase</extensionID>
    <extensionID>com.distriqt.firebase.Crashlytics</extensionID>
    <extensionID>com.distriqt.IDFA</extensionID>
    <extensionID>com.distriqt.Image</extensionID>
    <extensionID>com.distriqt.InAppBilling</extensionID>
    <extensionID>com.distriqt.MediaPlayer</extensionID>
    <extensionID>com.distriqt.NetworkInfo</extensionID>
    <extensionID>com.distriqt.playservices.Ads</extensionID>
    <extensionID>com.distriqt.playservices.AdsIdentifier</extensionID>
    <extensionID>com.distriqt.playservices.AppSet</extensionID>
    <extensionID>com.distriqt.playservices.Base</extensionID>
    <extensionID>com.distriqt.playservices.CloudMessaging</extensionID>
    <extensionID>com.distriqt.PushNotifications</extensionID>
    <extensionID>com.distriqt.square.okhttp</extensionID>
    <extensionID>com.distriqt.square.okhttp3</extensionID>
    <extensionID>com.google.android.datatransport</extensionID>
    <extensionID>com.google.android.play.appupdate</extensionID>
    <extensionID>com.google.android.play.review</extensionID>
    <extensionID>com.google.code.gson</extensionID>
    <extensionID>com.google.dagger</extensionID>
    <extensionID>com.google.firebase.core</extensionID>
    <extensionID>com.google.firebase.messaging</extensionID>
    <extensionID>com.google.guava</extensionID>
    <extensionID>com.google.protobuflite</extensionID>
    <extensionID>com.jetbrains.kotlin</extensionID>
    <extensionID>io.grpc</extensionID>
    <extensionID>io.reactivex</extensionID>
```

**Comment by marchbold** [comment]
Are you using any of the keyboard or display mode functionality from the Application extension? 

Though as I mentioned a while ago I can't see how this crash would be connected to the extensions. Definitely seems like something odd during the startup process. I wonder if you could describe how you are starting up your app? Maybe there's a clue there?

**Comment by ajwfrost** [comment]
Also - wondering if you use StageText? and do you handle the 'complete' event from it at all? It's the only place I can see us listening out for a Java "onLayout" callback, I'm wondering if there's something happening within this listener that would change the Android widget layouts/children...

**Comment by httpwebmedia** [comment]
@marchbold Yes, I do. I noticed that on the second launch of the app, ADB logs the following error:
`06-17 16:29:56.687  8163  8497 I com.androidapp: Error: Error #3200: Cannot perform operation on closed window.
06-17 16:29:56.687  8163  8497 I com.androidapp:       at flash.display::Stage/set displayState()
06-17 16:29:56.687  8163  8497 I com.androidapp:       at Main/frame1()[Main::frame1:449]`

To force fullscreen mode, I always use the following code in the first frame of the Flash timeline:
`import flash.display.*;
stage.align = StageAlign.TOP_LEFT;
stage.scaleMode = StageScaleMode.EXACT_FIT;
stage.displayState = StageDisplayState.FULL_SCREEN_INTERACTIVE;`

The error seems to be triggered by the line: by stage.displayState = StageDisplayState.FULL_SCREEN_INTERACTIVE
What’s odd is that the issue only occurs on the second and all subsequent bootups, but not on the initial launch right after installation.

@ajwfrost I did a quick check in my code and found no references to StageText. As far as I know, I’m only using DynamicText objects created in Animate. In my code, I primarily rely on:
flash.text.TextField;
flash.text.TextFormat;

I also noticed that on second boot and later launches, when running the apk-debug with adb logcat, it generates temporary ANR files like this:
`06-17 09:53:40.084  1908  5736 I ActivityManager: Collecting stacks for pid 5440 into temporary file temp_anr_3377501398698023435.txt`
Is there a way to access these files directly on the device?

**Comment by httpwebmedia** [comment]
Any thoughts? @ajwfrost @marchbold

**Comment by vishavjeet1999** [comment]
Temporary fix that worked for me:

Switched from @react-navigation/native-stack to @react-navigation/stack.

Why this helps:

native-stack uses react-native-screens to control real native view hierarchies (UINavigationController on iOS / FragmentManager on Android).

This adds complexity because the native view hierarchy must stay perfectly in sync with the React tree.

In some edge cases (e.g., very fast navigation changes, async dispatches, race conditions during unmount), React state and native state can go out of sync — leading to crashes like dispatchCancelPendingInputEvents, null pointer exceptions, or unexpected detach errors.

The JS-based @react-navigation/stack keeps the entire stack in the JS realm, rendering screens as React components inside a single native container view.

This removes the native view detach/attach lifecycle and avoids those native crashes — at the cost of slightly less performant transitions.

⚠️ Note:

This should be treated as a temporary workaround.

Monitor upstream fixes, or debug what triggers the state mismatch so you can safely switch back to native-stack for better native performance once stable.

Hope this helps anyone facing the same issue! 🚀

**Comment by ajwfrost** [comment]
@httpwebmedia do you use any webview with react-native stuff in it? I have no idea how that might work together, I wouldn't be surprised if there are all sorts of side-effects if react is trying to control the native UI at the same time that AIR is..!

But in case you're not .. I've just seen the hint about the display state, and I'm wondering if this might be the same kind of trigger i.e. where there's a separate view/UI element being added to the layout. We can check for this happening I guess, and see if we also get that error output. If we added logcat output, are you able to fetch this? Or alternatively I guess this would be a good candidate for enabling the diagnostics ANE, we'd need to update the runtime to output appropriate messages though..

thanks

**Comment by httpwebmedia** [comment]
@ajwfrost I figured it out for the issue regarding 
`06-17 16:29:56.687  8163  8497 I com.androidapp: Error: Error #3200: Cannot perform operation on closed window. 06-17 16:29:56.687  8163  8497 I com.androidapp:       at flash.display::Stage/set displayState() 06-17 16:29:56.687  8163  8497 I com.androidapp:       at Main/frame1()[Main::frame1:449]
`
I managed to resolve the issue by adding the following code — no more errors:
`
import flash.display.*;
addEventListener(Event.ENTER_FRAME,initStageAdjust);
function initStageAdjust(evt:Event):void {
	removeEventListener(Event.ENTER_FRAME,initStageAdjust);
	stage.align = StageAlign.TOP_LEFT;
	stage.scaleMode = StageScaleMode.EXACT_FIT;
	stage.displayState = StageDisplayState.FULL_SCREEN_INTERACTIVE;
}
`

For anyone looking to access ANR files, you can retrieve them via ADB with the following command:
`adb.exe -s bugreport bugreport.zip`

Once extracted, the ANR traces can be found at: 
bugreport/FS/data/anr/

Regarding the error "Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference", it's still **unresolved**.
Just to clarify — I'm not using React in my project.

I'm nearly ready to start using AirDiagnostic. I've sent you a complete example of my integration and will wait for your return from holiday to continue.
