### ISSUE TITLE
Problem with AirSdk 33.1.1.795

### ISSUE THREAD

**Issue by ac27437676** [airsdk/Adobe-Runtime-Support#1814]
I worked on FlashBuilder 4.7，after i use  AirSdk 33.1.1.795,my workspace has a problem: 

org.eclipse.core.runtime.internal.adaptor.EclipseLazyStarter$TerminatingClassNotFoundException: 自动激活 bundle com.adobe.flexbuilder.as.editor 时出错（24）。
	at org.eclipse.core.runtime.internal.adaptor.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:122)
	at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass(ClasspathManager.java:462)
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.findLocalClass(DefaultClassLoader.java:216)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:400)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:476)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:429)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:417)
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.osgi.internal.loader.BundleLoader.loadClass(BundleLoader.java:345)
	at org.eclipse.osgi.framework.internal.core.BundleHost.loadClass(BundleHost.java:229)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.loadClass(AbstractBundle.java:1207)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:174)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.ui.internal.WorkbenchPlugin$1.run(WorkbenchPlugin.java:268)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchPlugin.createExtension(WorkbenchPlugin.java:264)
	at org.eclipse.ui.internal.registry.ViewDescriptor.createView(ViewDescriptor.java:63)
	at org.eclipse.ui.internal.ViewReference.createPartHelper(ViewReference.java:327)
	at org.eclipse.ui.internal.ViewReference.createPart(ViewReference.java:229)
	at org.eclipse.ui.internal.WorkbenchPartReference.getPart(WorkbenchPartReference.java:595)
	at org.eclipse.ui.internal.WorkbenchPage.makeActive(WorkbenchPage.java:1320)
	at org.eclipse.ui.internal.WorkbenchPage.updateActivePart(WorkbenchPage.java:1304)
	at org.eclipse.ui.internal.WorkbenchPage.handleDeferredEvents(WorkbenchPage.java:1496)
	at org.eclipse.ui.internal.WorkbenchPage.deferUpdates(WorkbenchPage.java:1485)
	at org.eclipse.ui.internal.WorkbenchPage.access$14(WorkbenchPage.java:1476)
	at org.eclipse.ui.internal.WorkbenchPage$16.runWithException(WorkbenchPage.java:3386)
	at org.eclipse.ui.internal.StartupThreading$StartupRunnable.run(StartupThreading.java:31)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4140)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3757)
	at org.eclipse.ui.application.WorkbenchAdvisor.openWindows(WorkbenchAdvisor.java:803)
	at org.eclipse.ui.internal.Workbench$33.runWithException(Workbench.java:1595)
	at org.eclipse.ui.internal.StartupThreading$StartupRunnable.run(StartupThreading.java:31)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4140)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3757)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2604)
	at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2494)
	at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:674)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:667)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at com.adobe.flexbuilder.standalone.FlashBuilderApplication.start(FlashBuilderApplication.java:79)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:344)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:622)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:577)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1410)
Caused by: org.osgi.framework.BundleException: 束 com.adobe.flexbuilder.as.editor 的激活程序 com.adobe.flexbuilder.as.editor.ActionScriptPlugin 无效
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.loadBundleActivator(AbstractBundle.java:171)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:679)
	at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:381)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.start(AbstractBundle.java:299)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:440)
	at org.eclipse.osgi.internal.loader.BundleLoader.setLazyTrigger(BundleLoader.java:268)
	at org.eclipse.core.runtime.internal.adaptor.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
	... 59 more
Caused by: java.lang.NullPointerException
	at com.adobe.flexbuilder.as.editor.ActionScriptPlugin.log(ActionScriptPlugin.java:179)
	at com.adobe.flexbuilder.as.editor.quickfix.ActionScriptQuickFixRegistry.<init>(ActionScriptQuickFixRegistry.java:50)
	at com.adobe.flexbuilder.as.editor.quickfix.ActionScriptQuickFixRegistry.getInstance(ActionScriptQuickFixRegistry.java:58)
	at com.adobe.flexbuilder.as.editor.ActionScriptPlugin.<init>(ActionScriptPlugin.java:184)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance0(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.loadBundleActivator(AbstractBundle.java:166)
	... 65 more

how can i deal it? thanks every one!

![QQ截图20220401145312](https://user-images.githubusercontent.com/51351053/161211947-fdbdbeb6-1e12-4647-8087-4de378a30b9c.png)

**Comment by ajwfrost** [comment]
Hi

That's a long call stack! I wonder if the root issue is the one at the bottom:
```
Caused by: java.lang.NullPointerException
at com.adobe.flexbuilder.as.editor.ActionScriptPlugin.log(ActionScriptPlugin.java:179)
```
which implies that something's gone wrong within the internal logging process for Flash Builder.

We don't support Flash Builder though, and don't have access to those sources; I know Adobe stopped supporting it some time ago now, so my only suggestions would be:
1) can you try cleaning out the workspace or if necessary deleting it and re-creating it?
2) it would be worth looking to move to a new IDE, I'm not sure if there are any benefits to continuing to use Flash Builder..?

thanks

**Comment by ac27437676** [comment]
> Hi
> 
> That's a long call stack! I wonder if the root issue is the one at the bottom:
> 
> ```
> Caused by: java.lang.NullPointerException
> at com.adobe.flexbuilder.as.editor.ActionScriptPlugin.log(ActionScriptPlugin.java:179)
> ```
> 
> which implies that something's gone wrong within the internal logging process for Flash Builder.
> 
> We don't support Flash Builder though, and don't have access to those sources; I know Adobe stopped supporting it some time ago now, so my only suggestions would be:
> 
> 1. can you try cleaning out the workspace or if necessary deleting it and re-creating it?
> 2. it would be worth looking to move to a new IDE, I'm not sure if there are any benefits to continuing to use Flash Builder..?
> 
> thanks

Can you recommend a good IDE?
In addition, thank you for your efforts for FlashAIR，Blessings are getting better and better。

**Comment by marchbold** [comment]
@ac27437676 We highly recommend IntelliJ, but there are other common options listed here: https://airsdk.dev/docs/basics/setup-an-editor
