### ISSUE TITLE
Huge amount of ANRs

### ISSUE THREAD

**Issue by xxxVBxxx** [airsdk/Adobe-Runtime-Support#2138]
Hello.
I'm not sure if this is the right place to write about this issue, but I couldn't find anything better.
The android version of my app is getting a lot of ANRs and I can't figure out what causes it. 
Here are some of the Crashlytics logs.

`main (native): tid=1 systid=26102 
#00 pc 0x52288c libCore.so 
#01 pc 0x52a17d libCore.so 
#02 pc 0x4c0041 libCore.so 
#03 pc 0x4c044f libCore.so 
#04 pc 0x529d77 libCore.so 
#05 pc 0x529bf5 libCore.so 
#06 pc 0x489325 libCore.so 
#07 pc 0x476e55 libCore.so 
#08 pc 0x479c07 libCore.so 
#09 pc 0x4b5a15 libCore.so 
#10 pc 0x4daa5d libCore.so 
#11 pc 0x4da589 libCore.so 
#12 pc 0x4da34f libCore.so 
#13 pc 0x4da4d1 libCore.so 
#14 pc 0x4da35f libCore.so 
#15 pc 0x4da4d1 libCore.so 
#16 pc 0x4da35f libCore.so 
#17 pc 0x4da4d1 libCore.so 
#18 pc 0x4da35f libCore.so 
#19 pc 0x4da4d1 libCore.so 
#20 pc 0x4da35f libCore.so 
#21 pc 0x4da59b libCore.so 
#22 pc 0x4da34f libCore.so 
#23 pc 0x4d9fe3 libCore.so 
#24 pc 0x4d9f9b libCore.so 
#25 pc 0x179f  
       at com.adobe.air.customHandler.callTimeoutFunction(Native method)
       at com.adobe.air.customHandler.handleMessage(customHandler.java)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:334)
       at android.app.ActivityThread.main(ActivityThread.java:8287)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)

main (native): tid=1 systid=26102 
#00 pc 0x52288c libCore.so 
#01 pc 0x52a17d libCore.so 
#02 pc 0x4c0041 libCore.so 
#03 pc 0x4c044f libCore.so 
#04 pc 0x529d77 libCore.so 
#05 pc 0x529bf5 libCore.so 
#06 pc 0x489325 libCore.so 
#07 pc 0x476e55 libCore.so 
#08 pc 0x479c07 libCore.so 
#09 pc 0x4b5a15 libCore.so 
#10 pc 0x4daa5d libCore.so 
#11 pc 0x4da589 libCore.so 
#12 pc 0x4da34f libCore.so 
#13 pc 0x4da4d1 libCore.so 
#14 pc 0x4da35f libCore.so 
#15 pc 0x4da4d1 libCore.so 
#16 pc 0x4da35f libCore.so 
#17 pc 0x4da4d1 libCore.so 
#18 pc 0x4da35f libCore.so 
#19 pc 0x4da4d1 libCore.so 
#20 pc 0x4da35f libCore.so 
#21 pc 0x4da59b libCore.so 
#22 pc 0x4da34f libCore.so 
#23 pc 0x4d9fe3 libCore.so 
#24 pc 0x4d9f9b libCore.so 
#25 pc 0x179f  
       at com.adobe.air.customHandler.callTimeoutFunction(Native method)
       at com.adobe.air.customHandler.handleMessage(customHandler.java)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:334)
       at android.app.ActivityThread.main(ActivityThread.java:8287)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)

main (native): tid=1 systid=6697 
#00 pc 0x741e4c split_config.arm64_v8a.apk!libCore.so 
#01 pc 0x7359f0 split_config.arm64_v8a.apk!libCore.so 
#02 pc 0x84bd70 split_config.arm64_v8a.apk!libCore.so 
#03 pc 0x84ba6c split_config.arm64_v8a.apk!libCore.so 
#04 pc 0x84a138 split_config.arm64_v8a.apk!libCore.so 
#05 pc 0x849eec split_config.arm64_v8a.apk!libCore.so 
#06 pc 0x84e40c split_config.arm64_v8a.apk!libCore.so 
#07 pc 0x84e33c split_config.arm64_v8a.apk!libCore.so 
#08 pc 0x84e238 split_config.arm64_v8a.apk!libCore.so 
#09 pc 0x490cf4 split_config.arm64_v8a.apk!libCore.so 
#10 pc 0x490900 split_config.arm64_v8a.apk!libCore.so 
#11 pc 0x275ab8 split_config.arm64_v8a.apk!libCore.so 
#12 pc 0x2782c4 split_config.arm64_v8a.apk!libCore.so 
       at com.adobe.air.customHandler.callTimeoutFunction(Native method)
       at com.adobe.air.customHandler.handleMessage(customHandler.java:28)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:255)
       at android.app.ActivityThread.main(ActivityThread.java:8212)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

main (native): tid=1 systid=14834 
#00 pc 0x523448 libCore.so 
#01 pc 0x484f91 libCore.so 
#02 pc 0x52294d libCore.so 
#03 pc 0x52278b libCore.so 
#04 pc 0x521467 libCore.so 
#05 pc 0x5212b7 libCore.so 
#06 pc 0x52436d libCore.so 
#07 pc 0x5242db libCore.so 
#08 pc 0x524233 libCore.so 
#09 pc 0x27d633 libCore.so 
#10 pc 0x27d395 libCore.so 
#11 pc 0xe9981 libCore.so 
#12 pc 0xeb665 libCore.so 
#13 pc 0x2003543 memfd:jit-cache 
#14 pc 0x200603b memfd:jit-cache 
       at com.adobe.air.customHandler.callTimeoutFunction(Native method)
       at com.adobe.air.customHandler.handleMessage(customHandler.java)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
`

I'm using AIR SDK 33.1.1.889 
Thanks in advance.

**Comment by xxxVBxxx** [comment]
Here is one more. 
```
main (native): tid=1 systid=31933 
#00 pc 0x4dab0 libc.so (syscall + 32)
#01 pc 0x47cc80 libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*) + 140)
#02 pc 0x5734a4 libart.so (art::JNI<false>::PushLocalFrame(_JNIEnv*, int) + 976)
#03 pc 0x2c8f6c split_config.arm64_v8a.apk 
#04 pc 0x2d1ed8 split_config.arm64_v8a.apk 
#05 pc 0x34a778 split_config.arm64_v8a.apk 
#06 pc 0x34c3d8 split_config.arm64_v8a.apk 
#07 pc 0x621fb4 split_config.arm64_v8a.apk 
#08 pc 0xdc84  
       at com.adobe.air.customHandler.callTimeoutFunction(Native method)
       at com.adobe.air.customHandler.handleMessage(customHandler.java:28)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loopOnce(Looper.java:238)
       at android.os.Looper.loop(Looper.java:357)
       at android.app.ActivityThread.main(ActivityThread.java:8090)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```
