### ISSUE TITLE
AIR 50.0.1.1: Crash on start on Android 4.4.2

### ISSUE THREAD

**Issue by sjabberwocky** [airsdk/Adobe-Runtime-Support#2216]
Hi!

I just test AIR 50.0.1.1 and it works fine with our game on Android 8.1 and 11, but does not work with Android 4.4.2.
After clicking on the icon, we see the launch image and then a crash happens.

It would be nice if the 33.1 branch could be updated with a fixed OpenSSL so that the AIR team can stabilise the 50.1 branch without rushing.

```
E/AndroidRuntime( 6568): Process: air.app, PID: 6568
E/AndroidRuntime( 6568): java.lang.UnsatisfiedLinkError: Native method not found: com.adobe.air.AIRWindowSurfaceView.nativeSurfaceCreated:()V
E/AndroidRuntime( 6568): 	at com.adobe.air.AIRWindowSurfaceView.nativeSurfaceCreated(Native Method)
E/AndroidRuntime( 6568): 	at com.adobe.air.AIRWindowSurfaceView.surfaceCreated(AIRWindowSurfaceView.java:739)
E/AndroidRuntime( 6568): 	at android.view.SurfaceView.updateWindow(SurfaceView.java:662)
E/AndroidRuntime( 6568): 	at android.view.SurfaceView.access$000(SurfaceView.java:90)
E/AndroidRuntime( 6568): 	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:195)
E/AndroidRuntime( 6568): 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:847)
E/AndroidRuntime( 6568): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2197)
E/AndroidRuntime( 6568): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1192)
E/AndroidRuntime( 6568): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6231)
E/AndroidRuntime( 6568): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
E/AndroidRuntime( 6568): 	at android.view.Choreographer.doCallbacks(Choreographer.java:591)
E/AndroidRuntime( 6568): 	at android.view.Choreographer.doFrame(Choreographer.java:560)
E/AndroidRuntime( 6568): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
E/AndroidRuntime( 6568): 	at android.os.Handler.handleCallback(Handler.java:808)
E/AndroidRuntime( 6568): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime( 6568): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 6568): 	at android.app.ActivityThread.main(ActivityThread.java:5333)
E/AndroidRuntime( 6568): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 6568): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 6568): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
E/AndroidRuntime( 6568): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
E/AndroidRuntime( 6568): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  688):   Force finishing activity air.app/.AIRAppEntry
```

**Comment by ajwfrost** [comment]
Yes -> it seems that the AIR 50 library has a minimum requirement of Android 5.0, although this isn't by design and isn't set in the tools...

The 33.1.1.935 release is a bit delayed due to issues on the mac/iphone side but I'm thinking we should perhaps just push out a version that has updates only on the other platforms, so as to unblock the Android folk!

thanks

**Comment by ajwfrost** [comment]
Yes although the plan is that they support all of them (!) - this is more about which version of Android is supported by the AIR runtime, and details should be in the release notes. Obviously for this particular case, we've got a problem as we should be able to support 32-bit versions on Android 4.1 (Jelly Bean) upwards.

Mind you, 99.1% of devices are seemingly on Android 5.0 (API 21 = Lollipop) or later, so this isn't likely to affect a huge proportion of people..
