### ISSUE TITLE
apk,aab crashed at androidversion12 device by using 33.1.1.935 

### ISSUE THREAD

**Issue by Devkjk** [airsdk/Adobe-Runtime-Support#2244]
I have read past topics and seems to be solved issue.
So I think I may mistake something. 
I use Mac,AIRSDK 33.1.1.889
I tried below.

1.I updated AndroidStudio.
2.In AndroidStudio,I select preference -> AndroidSDK
  dowload Android 12.0
  AndroidSDK Location shows /Users/mmm/Library/Android/sdk
3.I overwrite lib/adt.cfg
 add lines below
 AndroidPlatformSDK=/Users/mmm/Library/Android/sdk
 JAVA_HOME=/Applications/Android Studio.app/Contents/jre/Contents/Home
4.publish swf by Animate
5.run cmd
```
$ cd (directory my swf file exist)
$ java -Xmx1024M -jar (pass of adt.jar) -package -target apk-captive-runtime -arch armv8 -storetype pkcs12 -keystore (pass of p12 file) -storepass password output.apk (pass for xml) (pass for icons directory) -extdir (pass for ANEs directory) target.swf
```
 *I havent able to find how to adt command :(

result:
```
WARNING: could not find appropriate Java Home location for v11+ JDK
aapt tool failed:/private/var/folders/qv/9gwpq0gs4xv2_99611xxpyg80000gn/T/52c15baa-9eba-4e39-92f0-b361a26b7433/savedstate-1.1.0-res/values/values.xml:3: error: Found tag id where item is expected
...
(many logs same as some past topics content)
...
```

**Comment by Devkjk** [comment]
Now I can use adt command :D

**Comment by Devkjk** [comment]
Now I update jdk version to 17.0.5.
After adt command.
```
sdk must refer to a valid directory path
```
I checked AndroidPlatformSDK pass and it is exist :(
Next I comment out adt.cfg.
```
unexpected failure: Unable to run java: com.adobe.air.ADTException: gradle tool failed: 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':com.google.android.gms.ads.impl:extractReleaseAnnotations'.
> Could not resolve all files for configuration ':com.google.android.gms.ads.impl:lintClassPath'.
   > Could not download groovy-ant-3.0.7.jar (org.codehaus.groovy:groovy-ant:3.0.7)
      > Could not get resource 'https://jcenter.bintray.com/org/codehaus/groovy/groovy-ant/3.0.7/groovy-ant-3.0.7.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/codehaus/groovy/groovy-ant/3.0.7/groovy-ant-3.0.7.jar'.
            > Read timed out
   > Could not download groovy-cli-picocli-3.0.7.jar (org.codehaus.groovy:groovy-cli-picocli:3.0.7)
      > Could not get resource 'https://jcenter.bintray.com/org/codehaus/groovy/groovy-cli-picocli/3.0.7/groovy-cli-picocli-3.0.7.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/codehaus/groovy/groovy-cli-picocli/3.0.7/groovy-cli-picocli-3.0.7.jar'.
            > Read timed out
...long message...
BUILD FAILED in 7m 56s

	at com.adobe.air.apk.AABOutputStream.buildGradle(AABOutputStream.java)
	at com.adobe.air.apk.AABPackager.renameOutput(AABPackager.java)
	at com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
	at com.adobe.air.apk.AABPackager.createPackage(AABPackager.java)
	at com.adobe.air.ADT.parseArgsAndGo(ADT.java)
	at com.adobe.air.ADT.run(ADT.java)
	at com.adobe.air.ADT.main(ADT.java)
```

**Comment by Devkjk** [comment]
Now I can create apk,aab by using  33.1.1.935.
I have a question.
Though My p12 file is 1024 and using java 17.0.5,there is no error :(

**Comment by Devkjk** [comment]
I installed apk to android device.
And not launch app :(
What to do next?

**Comment by Devkjk** [comment]
I uploaded logcat.
please help me.
[myapp_logcat.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/9901899/myapp_logcat.txt)

below part of log that begin crash
```
--------- beginning of crash
10-31 23:14:29.625  3494  3494 E AndroidRuntime: FATAL EXCEPTION: main
10-31 23:14:29.625  3494  3494 E AndroidRuntime: Process: air.com.myapp, PID: 3494
10-31 23:14:29.625  3494  3494 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider androidx.work.impl.WorkManagerInitializer: java.lang.ClassNotFoundException: Didn't find class "androidx.work.impl.WorkManagerInitializer" on path: DexPathList[[zip file "/data/app/~~5-rPAXcL7ivuecvye23ERA==/air.com.myapp-dgYvDQFS_VA1QBR5Stc-2g==/base.apk", zip file "/data/app/~~5-rPAXcL7ivuecvye23ERA==/air.com.myapp-dgYvDQFS_VA1QBR5Stc-2g==/split_config.arm64_v8a.apk", zip file "/data/app/~~5-rPAXcL7ivuecvye23ERA==/air.com.myapp-dgYvDQFS_VA1QBR5Stc-2g==/split_config.ja.apk", zip file "/data/app/~~5-rPAXcL7ivuecvye23ERA==/air.com.myapp-dgYvDQFS_VA1QBR5Stc-2g==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/~~5-rPAXcL7ivuecvye23ERA==/air.com.myapp-dgYvDQFS_VA1QBR5Stc-2g==/lib/arm64, /data/app/~~5-rPAXcL7ivuecvye23ERA==/air.com.myapp-dgYvDQFS_VA1QBR5Stc-2g==/base.apk!/lib/arm64-v8a, /data/app/~~5-rPAXcL7ivuecvye23ERA==/air.com.myapp-dgYvDQFS_VA1QBR5Stc-2g==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/~~5-rPAXcL7ivuecvye23ERA==/air.com.myapp-dgYvDQFS_VA1QBR5Stc-2g==/split_config.ja.apk!/lib/arm64-v8a, /data/app/~~5-rPAXcL7ivuecvye23ERA==/air.com.myapp-dgYvDQFS_VA1QBR5Stc-2g==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /product/lib64]]
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:7464)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6976)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6747)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 	at android.app.ActivityThread.access$1500(ActivityThread.java:256)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.work.impl.WorkManagerInitializer" on path: DexPathList[[zip file "/data/app/~~5-rPAXcL7ivuecvye23ERA==/air.com.myapp-dgYvDQFS_VA1QBR5Stc-2g==/base.apk", zip file "/data/app/~~5-rPAXcL7ivuecvye23ERA==/air.com.myapp-dgYvDQFS_VA1QBR5Stc-2g==/split_config.arm64_v8a.apk", zip file "/data/app/~~5-rPAXcL7ivuecvye23ERA==/air.com.myapp-dgYvDQFS_VA1QBR5Stc-2g==/split_config.ja.apk", zip file "/data/app/~~5-rPAXcL7ivuecvye23ERA==/air.com.myapp-dgYvDQFS_VA1QBR5Stc-2g==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/~~5-rPAXcL7ivuecvye23ERA==/air.com.myapp-dgYvDQFS_VA1QBR5Stc-2g==/lib/arm64, /data/app/~~5-rPAXcL7ivuecvye23ERA==/air.com.myapp-dgYvDQFS_VA1QBR5Stc-2g==/base.apk!/lib/arm64-v8a, /data/app/~~5-rPAXcL7ivuecvye23ERA==/air.com.myapp-dgYvDQFS_VA1QBR5Stc-2g==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/~~5-rPAXcL7ivuecvye23ERA==/air.com.myapp-dgYvDQFS_VA1QBR5Stc-2g==/split_config.ja.apk!/lib/arm64-v8a, /data/app/~~5-rPAXcL7ivuecvye23ERA==/air.com.myapp-dgYvDQFS_VA1QBR5Stc-2g==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /product/lib64]]
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 	at androidx.core.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:67)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:7448)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 	... 11 more
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 	Suppressed: java.io.IOException: Failed to open dex files from /data/app/~~5-rPAXcL7ivuecvye23ERA==/air.com.myapp-dgYvDQFS_VA1QBR5Stc-2g==/split_config.arm64_v8a.apk because: Entry not found
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.DexFile.openDexFileNative(Native Method)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.DexFile.openDexFile(DexFile.java:371)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.DexFile.<init>(DexFile.java:113)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.DexFile.<init>(DexFile.java:86)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:438)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:397)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.DexPathList.<init>(DexPathList.java:166)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:160)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:130)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:146)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:106)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:117)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:123)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at android.app.ApplicationLoaders.getClassLoaderWithSharedLibraries(ApplicationLoaders.java:60)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:971)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at android.app.LoadedApk.getClassLoader(LoadedApk.java:1062)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at android.app.LoadedApk.getResources(LoadedApk.java:1310)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at android.app.ContextImpl.createAppContext(ContextImpl.java:3037)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at android.app.ContextImpl.createAppContext(ContextImpl.java:3029)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6660)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		... 9 more
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 	Suppressed: java.io.IOException: Failed to open dex files from /data/app/~~5-rPAXcL7ivuecvye23ERA==/air.com.myapp-dgYvDQFS_VA1QBR5Stc-2g==/split_config.ja.apk because: Entry not found
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.DexFile.openDexFileNative(Native Method)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.DexFile.openDexFile(DexFile.java:371)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.DexFile.<init>(DexFile.java:113)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.DexFile.<init>(DexFile.java:86)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:438)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:397)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.DexPathList.<init>(DexPathList.java:166)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:160)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:130)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:146)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:106)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:117)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:123)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at android.app.ApplicationLoaders.getClassLoaderWithSharedLibraries(ApplicationLoaders.java:60)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:971)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at android.app.LoadedApk.getClassLoader(LoadedApk.java:1062)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at android.app.LoadedApk.getResources(LoadedApk.java:1310)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at android.app.ContextImpl.createAppContext(ContextImpl.java:3037)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at android.app.ContextImpl.createAppContext(ContextImpl.java:3029)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6660)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		... 9 more
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 	Suppressed: java.io.IOException: Failed to open dex files from /data/app/~~5-rPAXcL7ivuecvye23ERA==/air.com.myapp-dgYvDQFS_VA1QBR5Stc-2g==/split_config.xxhdpi.apk because: Entry not found
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.DexFile.openDexFileNative(Native Method)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.DexFile.openDexFile(DexFile.java:371)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.DexFile.<init>(DexFile.java:113)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.DexFile.<init>(DexFile.java:86)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:438)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:397)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.DexPathList.<init>(DexPathList.java:166)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:160)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:130)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:146)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:106)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:117)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:123)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at android.app.ApplicationLoaders.getClassLoaderWithSharedLibraries(ApplicationLoaders.java:60)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:971)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at android.app.LoadedApk.getClassLoader(LoadedApk.java:1062)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at android.app.LoadedApk.getResources(LoadedApk.java:1310)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at android.app.ContextImpl.createAppContext(ContextImpl.java:3037)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at android.app.ContextImpl.createAppContext(ContextImpl.java:3029)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6660)
10-31 23:14:29.625  3494  3494 E AndroidRuntime: 		... 9 more
```

**Comment by Devkjk** [comment]
Now I am trying this.
https://airsdk.dev/docs/tutorials/platform/android/packaging-android-app-bundles
I did not know such a good document until now :/

**Comment by Devkjk** [comment]
I do all above page,but same error in logcat.

FYI
swf is pulished by Animate2021 with some ditriqt ANEs
After process,I use adt tool.
My certficate p12 is 1024,so make aab without signing option.
I test by bundletool.
I sign p12 when make apks by java 1.8 (other process is java17).

Someone advice me plesase.

**Comment by Devkjk** [comment]
Finally apk works at my device :)
There were Many mistakes at app descriptor.
