### ISSUE TITLE
App not responsive during the preload

### ISSUE THREAD

**Issue by megajogos** [airsdk/Adobe-Runtime-Support#2326]
We have implemented a Preloader class and when stage.loaderInfo.bytesLoaded >= stage.loaderInfo.bytesTotal we call the stage.preloadComplete("MainApp") and it is working but during this load the main thread is totally busy and no render frame was called.

So during this load if the user touch the screen the ANR happens. 

@ajwfrost Please make the Adobe Air render at least 1 frame each 5 seconds to avoid the ANR.

**Comment by megajogos** [comment]
@ajwfrost any news about this? 
Google Play started a new policy about ANR and we are losing organic installs.

**Comment by megajogos** [comment]
@ajwfrost we have a lot of ANRs starting our app please help us! We need to mantain the app responsible during the app load.

**Comment by ajwfrost** [comment]
Apologies for not responding on the first part of this earlier. We had actually investigated and found that the loading on Android, although nominally asynchronous, is still actually happening within one JNI call which means that yes it's holding up the UI thread and not allowing touch events to be processed. So the preloader thing isn't going to help on Android for the ANR rate.

We had looked at changing that so that the loading is properly asynchronous, but that would be a massive rearchitecture .. so it was actually simpler to complete the "runtime thread" changes that we'd started a little while back, with a view to reducing the ANR count.

Upshot is -> we are about to release version AIR SDK version 50.2 which will allow you to put the runtime into a background thread on Android, leaving the UI thread free .. this will hopefully eliminate your problem here. Happy to send you a pre-release of it if you want, we've got a couple of outstanding changes to go into it before we pull the trigger on the release build..

thanks

**Comment by ajwfrost** [comment]
@megajogos can you email me direct and let me know what flavour (i.e, which OS you build with, and whether it's the normal one or the Flex-compatible one that you need) - `andrew.frost@harman.com`
thanks

**Comment by spAds2** [comment]
@ajwfrost unless I'm missing something, it would be awesome if such changes are documented somewhere.

Release notes state "AIR Android – adding 'runtimeInBackgroundThread' flag to app descriptor".
Someone not following these tickets will have no idea about the function or impact of this.

I personally also do not know where to add this new flag, as it is not documented or mentioned anywhere.

**Comment by ajwfrost** [comment]
Hi @spAds2 - sorry for the delay responding. From the release notes (PDF):
> A new app descriptor setting has been introduced under the “<android>” tag, “<runtimeInBackgroundThread>”, which can be set to “true” in order to switch the AIR runtime into a separate (non-UI) thread during application start-up. This means that there is an additional (internal) event queue added which should mean that the Android UI remains responsive to events, eliminating the “App Not Responding” problems particularly during start-up.
> Note that this does not actually improve performance, but shouldn’t adversely affect it. There may need to be changes in any ANE that uses functions that must be run in the main/UI thread of the application.

We've also just added information under here:
https://airsdk.dev/docs/building/application-descriptor-files/elements/android#runtimeinbackgroundthread

Normally we aim to have a github reference in the release notes so that people can come to these threads to get the background and more info, but with things like this where it was just using our internal reference, yes I can see there should be a way to link to some extra info... and we probably need to spend a bit more time updating the airsdk.dev site with things like this! Maybe a more verbose version of the changelists in section 3 of the release notes, similar to how Adobe used to write their release notes, would help..?

thanks

**Comment by megajogos** [comment]
@ajwfrost we have tested runtimeInBackgroundThread and worked really well to avoid the ANR starting our app but Adverts ANE is not working.

So we could not use it because of it.

**Comment by marchbold** [comment]
@megajogos We have a lot of work to make our extensions work with this addition. We have started on it but not sure when we will be able to update them all.

**Comment by megajogos** [comment]
The change log of version AIR 50.2.2.3 says:

"Workaround for Android ANE functions to run in UI thread"

@ajwfrost how to use this workaround?

**Comment by ajwfrost** [comment]
> To configure this, the fully qualified function class name is required (which can generally be seen in the call stack for a “run on UI thread” failure – the class name will have “.call” after it which is the FREFunction override that is called by AIR). A file (empty/tiny) needs to be created and packaged in the base of the application (so, generally, alongside the main SWF file) that has the exact same name as the class name. During function registration, the runtime checks for such files and if found, the functions will be called via a separate mechanism to run in the UI thread whilst the runtime waits for the result.

So for example: if you see a call stack that's got:
```
03-20 11:04:55.153  1601  1601 E Ads     : Error creating webview.
03-20 11:04:55.153  1601  1601 E Ads     : com.google.android.gms.ads.internal.webview.u: Webview initialization failed.
03-20 11:04:55.153  1601  1601 E Ads     :      at com.google.android.gms.ads.internal.webview.v.a(:com.google.android.gms.policy_ads_fdr_dynamite@230500000@230500000057.504263922.504263922:6)
....
03-20 11:04:55.153  1601  1601 E Ads     : Caused by: java.lang.IllegalStateException: Calling View methods on another thread than the UI thread.
03-20 11:04:55.153  1601  1601 E Ads     :      at com.android.webview.chromium.WebViewChromium.b(chromium-TrichromeWebViewGoogle.aab-stable-556305833:25)
03-20 11:04:55.153  1601  1601 E Ads     :      at com.android.webview.chromium.WebViewChromium.init(chromium-TrichromeWebViewGoogle.aab-stable-556305833:92)
03-20 11:04:55.153  1601  1601 E Ads     :      at android.webkit.WebView.<init>(WebView.java:435)
```
then you need to find out what is the bottom of the call stack and it should be an ANE function, for example
```
03-20 11:04:55.153  1601  1601 E Ads     :      at com.mycompany.myane.FncCreateWebView.call (FncCreateWebView.java:123)
```

Then, create an empty file that is the same as the ANE's FREFunction class (`touch com.mycompany.myane.FncCreateWebView`) and package this up as part of your APK/AAB file, in the same root location you'd normally put the main SWF.

We're not 100% sure yet on whether this is working properly in more complex cases - let us know how you get on, we could also provide a build with some additional debugging to output at every ANE call if it's tricky to determine the above..

thanks

**Comment by megajogos** [comment]
@ajwfrost we are not able to try this because the Adobe Air 50.2.2.3 is not working for us:
https://github.com/airsdk/Adobe-Runtime-Support/issues/2576

**Comment by bobrokrol** [comment]
Hello, I  have tried with distriqt ane, but it doesnt seems to work at all

here is the esxception
```
04-29 21:58:44.748  7115  7115 W System.err: com.adobe.fre.FREWrongThreadException
04-29 21:58:44.748  7115  7115 W System.err: 	at com.adobe.fre.FREObject.getAsString(Native Method)
04-29 21:58:44.748  7115  7115 W System.err: 	at com.distriqt.extension.adverts.functions.interstitials.LoadFunction.call(LoadFunction.java:40)
04-29 21:58:44.748  7115  7115 W System.err: 	at com.adobe.fre.FREContext$1.run(FREContext.java:184)
04-29 21:58:44.748  7115  7115 W System.err: 	at android.os.Handler.handleCallback(Handler.java:873)
04-29 21:58:44.748  7115  7115 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-29 21:58:44.748  7115  7115 W System.err: 	at android.os.Looper.loop(Looper.java:193)
04-29 21:58:44.748  7115  7115 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6737)
04-29 21:58:44.748  7115  7115 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-29 21:58:44.748  7115  7115 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
```
I have tried to package next empty files into root:

com.distriqt.extension.adverts.functions.interstitials.LoadFunction
com.distriqt.extension.adverts.functions.interstitials.LoadFunction.call
LoadFunction
com.distriqt.extension.adverts.functions.interstitials.Load

but I do nto see any difference. I see exceptions in same function. 
SDK is 50.2.2.5

**Comment by marchbold** [comment]
You will have to add nearly all the calls to this list, as the majority of the AdMob SDK is required to be run on the UI thread. We have a beta available now in the repository.

**Comment by bobrokrol** [comment]
> You will have to add nearly all the calls to this list, as the majority of the AdMob SDK is required to be run on the UI thread. We have a beta available now in the repository.

yes I expected this, but its was  not clear what exactly to ad as I havent seen difference in console logs.

so file name for  "interstitials.load" my should be:
 com.distriqt.extension.adverts.functions.interstitials.LoadFunction

**Comment by bobrokrol** [comment]
> You will have to add nearly all the calls to this list, as the majority of the AdMob SDK is required to be run on the UI thread. We have a beta available now in the repository.

* consent framework and interstitials do not work for me. 
* rewards  videos work.

.


```
 System.err: com.adobe.fre.FREWrongThreadException
04-30 15:58:09.973 11506 11506 W System.err: 	at com.adobe.fre.FREObject.getAsString(Native Method)
04-30 15:58:09.973 11506 11506 W System.err: 	at com.distriqt.extension.adverts.functions.interstitials.LoadFunction.call(LoadFunction.java:38)
04-30 15:58:09.973 11506 11506 W System.err: 	at com.adobe.fre.FREContext$1.run(FREContext.java:184)
04-30 15:58:09.973 11506 11506 W System.err: 	at android.os.Handler.handleCallback(Handler.java:942)
04-30 15:58:09.973 11506 11506 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-30 15:58:09.973 11506 11506 W System.err: 	at android.os.Looper.loopOnce(Looper.java:226)
04-30 15:58:09.973 11506 11506 W System.err: 	at android.os.Looper.loop(Looper.java:313)
04-30 15:58:09.973 11506 11506 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8747)
04-30 15:58:09.973 11506 11506 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-30 15:58:09.973 11506 11506 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
04-30 15:58:09.973 11506 11506 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```


```
System.err: java.lang.IllegalStateException: Method must be call on main thread.
04-30 15:57:56.586 11506 11589 W System.err: 	at com.google.android.gms.internal.consent_sdk.zzcd.zza(com.google.android.ump:user-messaging-platform@@2.0.0:2)
04-30 15:57:56.586 11506 11589 W System.err: 	at com.google.android.gms.internal.consent_sdk.zzba.zza(com.google.android.ump:user-messaging-platform@@2.0.0:1)
04-30 15:57:56.586 11506 11589 W System.err: 	at com.google.android.ump.UserMessagingPlatform.loadConsentForm(com.google.android.ump:user-messaging-platform@@2.0.0:1)
04-30 15:57:56.586 11506 11589 W System.err: 	at com.distriqt.extension.adverts.platforms.admob.GoogleAdMobUserMessagingPlatform.loadConsentForm(GoogleAdMobUserMessagingPlatform.java:107)
04-30 15:57:56.586 11506 11589 W System.err: 	at com.distriqt.extension.adverts.functions.ump.LoadConsentFormFunction.call(LoadConsentFormFunction.java:37)
04-30 15:57:56.586 11506 11589 W System.err: 	at com.adobe.air.customHandler.callTimeoutFunction(Native Method)
04-30 15:57:56.586 11506 11589 W System.err: 	at com.adobe.air.Entrypoints$1.handleMessage(Entrypoints.java:257)
04-30 15:57:56.586 11506 11589 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-30 15:57:56.586 11506 11589 W System.err: 	at android.os.Looper.loopOnce(Looper.java:226)
04-30 15:57:56.586 11506 11589 W System.err: 	at android.os.Looper.loop(Looper.java:313)
04-30 15:57:56.586 11506 11589 W System.err: 	at com.adobe.air.Entrypoints.run(Entrypoints.java:278)
04-30 15:57:56.586 11506 11589 W System.err: 	at java.lang.Thread.run(Thread.java:1012)
```

so its partially working. 
But I need alos  solution  for  other ane's ironsource +  facebook + admob adapter , adverts + facebook,  Play BIlling (if its not work), admob consent framework.

at least need fully working Adverts + Consent Framework so I can release one app and see if it do better or worse.

**Comment by megajogos** [comment]
@marchbold We have tried the last version of Adverts and air 50.2.2.6 and the ads are working fine!

But the Application.ane is not:
```
2023-05-30 11:04:50.056 17206-17411 System.err              air.br.com.megajogos.mobile          W  android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
2023-05-30 11:04:50.056 17206-17411 System.err              air.br.com.megajogos.mobile          W  	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8461)
2023-05-30 11:04:50.056 17206-17411 System.err              air.br.com.megajogos.mobile          W  	at android.view.ViewRootImpl.recomputeViewAttributes(ViewRootImpl.java:4287)
2023-05-30 11:04:50.056 17206-17411 System.err              air.br.com.megajogos.mobile          W  	at android.view.View.setOnSystemUiVisibilityChangeListener(View.java:25350)
2023-05-30 11:04:50.056 17206-17411 System.err              air.br.com.megajogos.mobile          W  	at com.distriqt.extension.application.display.DisplayController.<init>(DisplayController.java:106)
2023-05-30 11:04:50.056 17206-17411 System.err              air.br.com.megajogos.mobile          W  	at com.distriqt.extension.application.ApplicationContext.display(ApplicationContext.java:426)
2023-05-30 11:04:50.056 17206-17411 System.err              air.br.com.megajogos.mobile          W  	at com.distriqt.extension.application.functions.display.WillCutoutAffectViewFunction.call(WillCutoutAffectViewFunction.java:37)
2023-05-30 11:04:50.056 17206-17411 System.err              air.br.com.megajogos.mobile          W  	at com.adobe.air.customHandler.nativeOnTouchCallback(Native Method)
2023-05-30 11:04:50.056 17206-17411 System.err              air.br.com.megajogos.mobile          W  	at com.adobe.air.Entrypoints$1.handleMessage(Entrypoints.java:301)
2023-05-30 11:04:50.057 17206-17411 System.err              air.br.com.megajogos.mobile          W  	at android.os.Handler.dispatchMessage(Handler.java:107)
2023-05-30 11:04:50.057 17206-17411 System.err              air.br.com.megajogos.mobile          W  	at android.os.Looper.loop(Looper.java:214)
2023-05-30 11:04:50.057 17206-17411 System.err              air.br.com.megajogos.mobile          W  	at com.adobe.air.Entrypoints.run(Entrypoints.java:318)
2023-05-30 11:04:50.057 17206-17411 System.err              air.br.com.megajogos.mobile          W  	at java.lang.Thread.run(Thread.java:919)
```

**Comment by marchbold** [comment]
@megajogos Yeah we have only done the NativeWebView and Adverts ANEs so far. Will look at this one next.
