### ISSUE TITLE
Mac app built with 50.2.2.2 or 50.2.2.3 crashes after closing

### ISSUE THREAD

**Issue by kasparv** [airsdk/Adobe-Runtime-Support#2571]
Mac apps built with Air SDK 50.2.2.2 or 50.2.2.3 produce a crash on Mac OS after closing.
This also happens with `adl` when running the project from IntelliJ.
Attached Mac OS log.

<img width="186" alt="error" src="https://user-images.githubusercontent.com/2829488/229891589-f588a701-b8a4-41f7-bb68-93fd11bb2891.png">
[log.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/11152030/log.txt)

## Known Workarounds

Build using 50.2.1.1

**Comment by kasparv** [comment]
After some testing it seems that the app fails to clear itself correctly from the memory as the error code `SIGNAL, Code 11 Segmentation fault: 11` suggests? And this again is only happening if worker is used.
Also it seems that if the worker-containing app for Android (.aab) is built on Mac using 50.2.2.3, it will crash but not when built with Windows.

**Comment by itlancer** [comment]
I have the same issue with 50.2.2.4 with macOS too.
Also there is similar issue with Android too on application exit which uses workers:
```
Failed to deliver inset state change to w=Window{bdea75d u0 com.my.app/com.my.app.AIRAppEntry EXITING}
android.os.DeadObjectException
    at android.os.BinderProxy.transactNative(Native Method)
    at android.os.BinderProxy.transact(BinderProxy.java:605)
    at android.view.IWindow$Stub$Proxy.insetsControlChanged(IWindow.java:832)
    at com.android.server.wm.WindowState.notifyInsetsControlChanged(WindowState.java:4363)
    at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$5$InsetsStateController(InsetsStateController.java:594)
    at com.android.server.wm.-$$Lambda$InsetsStateController$AD-N-CuASggMPuANxay4AharPVM.run(Unknown Source:2)
    at com.android.server.wm.WindowAnimator.executeAfterPrepareSurfacesRunnables(WindowAnimator.java:341)
    at com.android.server.wm.RootWindowContainer.performSurfacePlacementNoTrace(RootWindowContainer.java:1029)
    at com.android.server.wm.RootWindowContainer.performSurfacePlacement(RootWindowContainer.java:958)
    at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop(WindowSurfacePlacer.java:182)
    at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:131)
    at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:120)
    at com.android.server.wm.WindowSurfacePlacer$Traverser.run(WindowSurfacePlacer.java:62)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:246)
    at android.os.HandlerThread.run(HandlerThread.java:67)
    at com.android.server.ServiceThread.run(ServiceThread.java:44)
```

**Comment by ajwfrost** [comment]
The iOS/macOS version of this fix will come in our next release, we didn't build those platforms for 50.2.2.6.

But that Android one will need to be investigated further, we can check it..

thanks

**Comment by itlancer** [comment]
@ajwfrost 
`NativeApplication.nativeApplication.exit()` cause such crash with Android: https://github.com/airsdk/Adobe-Runtime-Support/issues/2670
`<runtimeInBackgroundThread>true</runtimeInBackgroundThread>` not used.

**Comment by itlancer** [comment]
For me it fixed with latest AIR 50.2.3.1+. Checked with macOS.
Thanks!
