### ISSUE TITLE
[AIR 50.2.2.6][Android] `NativeApplication.nativeApplication.exit()` cause crash

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#2670]
## Problem Description
`NativeApplication.nativeApplication.exit()` cause crash (not proper exit) with Android using AIR 50.2.2.6.
So your applications cannot implement correct exit pipeline. Especially if apps uses native extensions and so on that should be correctly disposed.

Tested with latest AIR 50.2.2.6 version with multiple different Android devices with different OS versions with different applications and architectures.
Same problem in all cases.
There is no such problem with AIR ~50.2.2.2 and below.

May be related issues:
https://github.com/airsdk/Adobe-Runtime-Support/issues/2614 (may be side effect and not a bug)
https://github.com/airsdk/Adobe-Runtime-Support/issues/2571

## Steps to Reproduce
Launch application with code below and click anywhere on stage to close application.
Application example with sources attached.
[android_exit_bug.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/11626322/android_exit_bug.zip)

```
package {
	import flash.display.Sprite;
	import flash.events.MouseEvent;
	import flash.desktop.NativeApplication;
	
	public class AndroidExitBug extends Sprite {
		
		public function AndroidExitBug() {
			stage.addEventListener(MouseEvent.CLICK, click);
		}
		
		private function click(e:MouseEvent):void {
			trace("click");
			NativeApplication.nativeApplication.exit();//This line cause "W/WindowManager: Exception thrown during dispatchAppVisibility Window{e4dd592 u0 android.exit.bug/android.exit.bug.AIRAppEntry EXITING} android.os.DeadObjectException" exception in ADB Logcat
		}
	}
}
```

**Actual Result:**
Application crash (not proper exit).

```
W/WindowManager: Exception thrown during dispatchAppVisibility Window{e860e1a u0 android.exit.bug/android.exit.bug.AIRAppEntry EXITING}
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:584)
        at android.view.IWindow$Stub$Proxy.dispatchAppVisibility(IWindow.java:536)
        at com.android.server.wm.WindowState.sendAppVisibilityToClients(WindowState.java:3498)
        at com.android.server.wm.WindowContainer.sendAppVisibilityToClients(WindowContainer.java:1203)
        at com.android.server.wm.WindowToken.setClientVisible(WindowToken.java:398)
        at com.android.server.wm.ActivityRecord.setClientVisible(ActivityRecord.java:6702)
        at com.android.server.wm.ActivityRecord.onAnimationFinished(ActivityRecord.java:7498)
        at com.android.server.wm.WindowContainer.doAnimationFinished(WindowContainer.java:3225)
        at com.android.server.wm.WindowContainer.onAnimationFinished(WindowContainer.java:3237)
        at com.android.server.wm.WindowContainer$$ExternalSyntheticLambda4.onAnimationFinished(Unknown Source:2)
        at com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$0$com-android-server-wm-SurfaceAnimator(SurfaceAnimator.java:133)
        at com.android.server.wm.SurfaceAnimator$$ExternalSyntheticLambda1.run(Unknown Source:8)
        at com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$1$com-android-server-wm-SurfaceAnimator(SurfaceAnimator.java:143)
        at com.android.server.wm.SurfaceAnimator$$ExternalSyntheticLambda0.onAnimationFinished(Unknown Source:4)
        at com.android.server.wm.RemoteAnimationController.onAnimationFinished(RemoteAnimationController.java:273)
        at com.android.server.wm.RemoteAnimationController.-$$Nest$monAnimationFinished(Unknown Source:0)
        at com.android.server.wm.RemoteAnimationController$FinishedCallback.onAnimationFinished(RemoteAnimationController.java:384)
        at android.view.IRemoteAnimationFinishedCallback$Stub.onTransact(IRemoteAnimationFinishedCallback.java:89)
        at android.os.Binder.execTransactInternal(Binder.java:1285)
        at android.os.Binder.execTransact(Binder.java:1244)
```

**Expected Result:**
Application correctly exit without exceptions.

## Known Workarounds
Use AIR ~50.2.2.2 or earlier.

**Comment by itlancer** [comment]
Fixed with latest AIR SDK. Checked with AIR SDK 50.2.3.1.
Thanks!

But related issue with native extensions and Android application closing still exists: https://github.com/airsdk/Adobe-Runtime-Support/issues/2614
