### ISSUE TITLE
[AIR 50.2.2.6][Android] App Crashing

### ISSUE THREAD

**Issue by megajogos** [airsdk/Adobe-Runtime-Support#2671]
After sending a request to Firebase, the following error message appears:

`05-31 15:18:30.793 28593 28593 D com.distriqt.Application: DisplayController::updateVisibility(): unknown
05-31 15:18:30.815 29400 29400 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
05-31 15:18:30.859 29400 29400 W art     : Unexpected CPU variant for X86 using defaults: x86_64
05-31 15:18:30.887 29403 29403 E patchoat: Failed to open output oat file /data/dalvik-cache/x86_64/system@framework@wm.jar@classes.dex: Permission denied(13)
05-31 15:18:30.888 29400 29400 W art     : Failed execv(/system/bin/patchoat --instruction-set=x86_64 --input-oat-file=/system/framework/oat/x86_64/wm.odex `

After that, the app crashes and closes and shows a sequence of errors in Logcat. I did a test using version 50.2.2.5 of the AIR, and it works normally, but in version 50.2.2.6 the app always crashes.

Here is the complete log:
[crashing app logcat.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/11630470/crashing.app.logcat.txt)

**Comment by ajwfrost** [comment]
Hmmm.... I think your earlier snippet isn't actually a fatal problem. Looking at the complete log, the issue here is due to a secondary thread. Are you using the 'background runtime' option? It doesn't look like it, given I can see AS3 traces coming out on the main UI thread, but I'm wondering about the usage of this otherwise:

```
05-31 15:18:34.230 28593 29049 F art     : art/runtime/runtime.cc:1537] Thread[150,tid=29049,Native,Thread*=0x9ee6ab00,peer=0x32c26ee0,"Binder:28593_7"] attempting to detach while still running code

05-31 15:18:36.114 28593 29049 F art     : art/runtime/runtime.cc:422] Runtime aborting...
05-31 15:18:36.114 28593 29049 F art     : art/runtime/runtime.cc:422] Aborting thread:
05-31 15:18:36.114 28593 29049 F art     : art/runtime/runtime.cc:422]   sysTid=29049
05-31 15:18:36.114 28593 29049 F art     : art/runtime/runtime.cc:422]   native: #07 pc 005148f9  /system/lib/libart.so (_ZN3art7Runtime19DetachCurrentThreadEv+377)
05-31 15:18:36.114 28593 29049 F art     : art/runtime/runtime.cc:422]   native: #08 pc 00395e25  /system/lib/libart.so (_ZN3art3JII19DetachCurrentThreadEP7_JavaVM+69)
05-31 15:18:36.115 28593 29049 F art     : art/runtime/runtime.cc:422]   native: #09 pc 00148eaa  /system/lib/libart.so (_ZN3art8CheckJII19DetachCurrentThreadEP7_JavaVM+122)
05-31 15:18:36.115 28593 29049 F art     : art/runtime/runtime.cc:422]   native: #10 pc 002585a9  /system/lib/libhoudini.so (???)
05-31 15:18:36.115 28593 29049 F art     : art/runtime/runtime.cc:422]   at com.adobe.air.AIRWindowSurfaceView.nativeShowOriginalRect(Native method)
05-31 15:18:36.115 28593 29049 F art     : art/runtime/runtime.cc:422]   at com.adobe.air.AIRWindowSurfaceView$InputMethodReceiver.onReceiveResult(AIRWindowSurfaceView.java:941)
05-31 15:18:36.115 28593 29049 F art     : art/runtime/runtime.cc:422]   at android.os.ResultReceiver$MyResultReceiver.send(ResultReceiver.java:59)
05-31 15:18:36.115 28593 29049 F art     : art/runtime/runtime.cc:422]   at com.android.internal.os.IResultReceiver$Stub.onTransact(IResultReceiver.java:58)
05-31 15:18:36.115 28593 29049 F art     : art/runtime/runtime.cc:422]   at android.os.Binder.execTransact(Binder.java:565)
```

We can check the usage here where we're being called from other threads and trying to clean ourselves up, it appears that this isn't the right thing to do here. Or actually, it may be that the way we're checking whether we're already attached or not, isn't quite working, which means we're detaching when we shouldn't....

thanks

**Comment by ajwfrost** [comment]
I just found that I had written the above at the start of the day but hadn't posted it! so, quick update, we have found that the way we were checking to see whether a thread was attached in JNI wasn't coping with situations where other components were attaching them .. and the "attach"/"detach" calls aren't paired up which means you can call "attach" however many times you like, but you must only call "detach" once, at the correct time. 

So, we have a fix for this which will go in to our next release..

thanks

**Comment by megajogos** [comment]
Thanks for the feedback. By the way, answering the question asked, we are not using the background runtime option
