### ISSUE TITLE
Adding delayed-load capability for ANEs example

### ISSUE THREAD

**Issue by cleverbeapps** [airsdk/Adobe-Runtime-Support#2826]
Hi @ajwfrost 
For the purpose of decreasing application launch time, I want to utilize this new delayed-load feature. Since there are no examples on this topic, could you please explain, I have doubts about how I use it. 

- descriptor.xml:
```
<extensions>
<!--<extensionID>com.distriqt.Adverts</extensionID>--> - I have removed this line from the descriptor file
</extensions>
```

- MyAdsManager.as:
```
package game.managers {
     CONFIG::mobile {
         import com.distriqt.extension.adverts.Adverts;
         import com.distriqt.extension.adverts.InterstitialAd;
         .....
     }
     public class MyAdsManager {
          static public function init():void {
               CONFIG::mobile {
                    var aneDir:File = File.applicationDirectory.resolvePath("ane/com.distriqt.Adverts.ane");
                    ExtensionContext.loadExtension('com.distriqt.Adverts', aneDir);   // here I call dedicated method to fetch ane
                    Adverts.service.initialise();
               }
          }
     }
}
```

In this way I have exception at launch time:
[Fault] exception, information=VerifyError: Error #1014: Class com.distriqt.extension.adverts::InterstitialAd could not be found.
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	
So, what I am doing wrong? Thank you.

**Comment by cleverbeapps** [comment]
Another example:

- descriptor.xml:
```
<extensions>
<extensionID delayLoad="true">com.distriqt.Adverts</extensionID>   // here I add 'delayLoad' attribute
</extensions>
```

- MyAdsManager.as:
```
package game.managers {
     CONFIG::mobile {
         import com.distriqt.extension.adverts.Adverts;
         import com.distriqt.extension.adverts.InterstitialAd;
         .....
     }
     public class MyAdsManager {
          static public function init():void {
               CONFIG::mobile {
                    // no call for ExtensionContext.loadExtension
                    Adverts.service.initialise();
               }
          }
     }
}
```

In this way everything works fine like always before, so it seems that delayLoad="true" was not taken into consideration by the runtime.

**Comment by cleverbeapps** [comment]
@ajwfrost Andrew, could you help, please?

**Comment by marchbold** [comment]
Must say I haven't tested this functionality so not really sure what works. I'll have a look into it next week.

**Comment by cleverbeapps** [comment]
> Must say I haven't tested this functionality so not really sure what works. I'll have a look into it next week.

@marchbold really interesting, what you will find, Michael

**Comment by ajwfrost** [comment]
Hi

Sorry for the slow response.. the "delayLoad" thing is meant to prevent us from loading in the extension information (both the library SWF and the native libraries) until you then call the `loadExtension()` method. So, if you've got this set and you try to access a definition that's from the library, you should actually get a VerifyError. From the example, above, it should then be impossible to call `MyAdsManager.init()` before you've loaded the extension...!

From the release notes:

> AIR-5960: Adding delayed-load capability for ANEs
> To avoid having to load and initialise everything within the first frame of execution, ANEs can now be loaded in a delayed fashion. To set this up, add a “delayLoad="true"” attribute into the “extensionID” tag, and then – prior to accessing any of the AS3 definitions from the ANE’s library – use the new ExtensionContext.loadExtension() method. This method can also be used to load an ANE that’s not listed in the application descriptor file – for this, the path to the ANE folder needs to be given. The AIR runtime then uses this folder to look for an extension descriptor file under a relative path of “META-INF/ANE/extension.xml”.


thanks

**Comment by cleverbeapps** [comment]
@ajwfrost Andrew, please, correct me. Another example:
In project I have folder
<img width="311" alt="image" src="https://github.com/airsdk/Adobe-Runtime-Support/assets/96975636/3320b217-5c77-445d-a95f-79e94b6d9e5d">
Then I add it to files and folders to package:
<img width="302" alt="image" src="https://github.com/airsdk/Adobe-Runtime-Support/assets/96975636/701c201a-51fe-42f8-be0a-440860698cba">
Then I remove extentionId from descriptor:
<img width="480" alt="image" src="https://github.com/airsdk/Adobe-Runtime-Support/assets/96975636/c13424cb-5a2d-47bb-883b-483042624dd7">
Then I do:
`var aneDir:File = File.applicationDirectory.resolvePath("anePreload");
        ExtensionContext.loadExtension('com.distriqt.Adverts', aneDir);`
And then error appears:
<img width="786" alt="image" src="https://github.com/airsdk/Adobe-Runtime-Support/assets/96975636/adce399a-c5a7-41fe-9743-2c4b4d382c24">

**Comment by ajwfrost** [comment]
@cleverbeapps if you've not packaged the extension into the application bundle (via having it as an extensionID in the app descriptor) then you'll need to manually extract the required files into the location where you then try to call `loadExtension` from .. so e.g. under your "anePreload" path, we're looking for a file "META-INF/ANE/extension.xml" per that error message. We don't read into the .ane file directly..

thanks

**Comment by cleverbeapps** [comment]
@ajwfrost 
So, I've extracted files from ane to that folder, but now another error (when creating ios package):
<img width="1085" alt="image" src="https://github.com/airsdk/Adobe-Runtime-Support/assets/96975636/bf6641e6-98a5-4b67-a26e-bdf4328ac9b8">

**Comment by ajwfrost** [comment]
I'm wondering what it's trying to sign, and finding that it's not actually a macho binary..!

But yes, the simpler mechanism should be to just add the `delayLoad="true"` setting, and then `ExtensionContext.loadExtension(extensionID, null)` which  should return true if it's loaded.

thanks

**Comment by cleverbeapps** [comment]
> I'm wondering what it's trying to sign, and finding that it's not actually a macho binary..!
> 
> But yes, the simpler mechanism should be to just add the `delayLoad="true"` setting, and then `ExtensionContext.loadExtension(extensionID, null)` which should return true if it's loaded.
> 
> thanks

I've noticed, that even if I do not call `ExtensionContext.loadExtension(extensionID, null)`,
and use delayLoad="true" - extensions work like it already loaded. Is it really do 'delayed-load'?

**Comment by cleverbeapps** [comment]
Hi @ajwfrost 
Is it possible to have it work at the next release?

**Comment by ajwfrost** [comment]
Hi @cleverbeapps  - we've just looked at this, but the `delayLoad="true"` setting appears to be working how we would expect it?

So e.g. we've got an app descriptor with the extension:
```
<extensionID>com.distriqt.Core</extensionID>
```
and we can see the SWF library data for this being loaded in at start-up. But if we change it to:
```
<extensionID delayLoad="true">com.distriqt.Core</extensionID>
```
then the SWF library is not loaded in.

Below is the file we used to test this:
```
package
{
  import com.distriqt.extension.core.Core;

  public class TestANE
  {
    public function TestANE()
    {
      trace("TestANE constructor");
    }
    public function isLoaded() : Boolean
    {
      trace("Checking for District Core..");
      var result : Boolean = false;
      try
      {
        result = runTest();
        trace("Test ran without throwing");
      }
      catch(e : Error)
      {
        trace("Test threw error: " + e.toString());
      }
      return result;
    }
    private function runTest() : Boolean
    {
      Core.init(null);
      trace(new Core().version);
      return true;
    }
  }
}
```
called with:
```
	// test if the ANE is loaded
	var tester : TestANE = new TestANE();
	trace("ANE load status = " + tester.isLoaded());
```

Results with the 'delayLoad' setting were:
```
10-30 08:47:44.008 12323 12323 D AdobeAIR: TRACE: TestANE constructor
10-30 08:47:44.008 12323 12323 D AdobeAIR: TRACE: Checking for District Core..
10-30 08:47:44.009 12323 12323 D AdobeAIR: TRACE: Test threw error: ReferenceError: Error #1065: Variable com.distriqt.extension.core::Core is not defined.
10-30 08:47:44.009 12323 12323 D AdobeAIR: TRACE: ANE load status = false
```


If you're getting the ANE's definitions even if you have `delayLoad="true"`, can you check how you're including the ANE library? It should be via the `external-library-path` option, i.e. the definitions are excluded from the main SWF. You can perhaps check your own SWF to ensure that the definitions aren't in it (via SWFInvestigator or swfdump or similar)?


thanks
