### ISSUE TITLE
[Android] `System.err: java.lang.NoSuchMethodError: no non-static method "Lcom/adobe/flashruntime/air/VideoTextureSurface;.getHeight()I"` on `VideoTexture` start to play

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#2910]
## Problem Description
`System.err: java.lang.NoSuchMethodError: no non-static method "Lcom/adobe/flashruntime/air/VideoTextureSurface;.getHeight()I"` error appears in LogCat when `VideoTexture` start to play using Android devices.

Tested with multiple AIR versions from 33.1 to latest AIR 50.2.3.8 with different AIR applications, devices, architectures and videos.
Tested with pure `Stage3D` and with Starling.
Same issue in all cases.

Related issues:
https://github.com/airsdk/Adobe-Runtime-Support/issues/2268
https://github.com/airsdk/Adobe-Runtime-Support/issues/1174
https://github.com/airsdk/Adobe-Runtime-Support/issues/587
https://github.com/airsdk/Adobe-Runtime-Support/issues/92
https://github.com/airsdk/Adobe-Runtime-Support/issues/16

## Steps to Reproduce
Launch application with code below with any Android device. It just play video using `VideoTexture` in a loop.

Application example with sources, Scout log, LogCat log and video attached.
[android_videotexture_videotexturesurface_getheight_error.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/13321206/android_videotexture_videotexturesurface_getheight_error.zip)

```
package {
	import flash.display.Sprite;
	import flash.display.Stage3D;
	import flash.events.Event;
	import flash.events.NetStatusEvent;
	import flash.net.NetStream;
	import flash.display3D.Context3D;
	import flash.display3D.IndexBuffer3D;
	import flash.geom.Matrix3D;
	import flash.net.NetConnection;
	import flash.display3D.textures.VideoTexture;
	import com.adobe.utils.AGALMiniAssembler;
	import flash.display3D.Context3DProgramType;
	import flash.display3D.Context3DVertexBufferFormat;
	import flash.display3D.VertexBuffer3D;
	import flash.display3D.Program3D;
	import flash.display3D.Context3DProfile;
	import flash.desktop.NativeApplication;
	import flash.desktop.SystemIdleMode;
	
	public class AndroidVideoTextureVideoTextureSurfaceGetHeightError extends Sprite {
		private var stage3D:Stage3D;
		private var context3D:Context3D;
		private var indexbuffer:IndexBuffer3D;
		private var matrix:Matrix3D = new Matrix3D();
		private var _netConnection:NetConnection;
		private var _netStream:NetStream;
		private var videoTexture:VideoTexture;
		
		public function AndroidVideoTextureVideoTextureSurfaceGetHeightError() {
			NativeApplication.nativeApplication.systemIdleMode = SystemIdleMode.KEEP_AWAKE;
			
			stage3D = stage.stage3Ds[0];
			stage3D.addEventListener(Event.CONTEXT3D_CREATE, contextCreated);
			stage3D.requestContext3DMatchingProfiles(Vector.<String>([Context3DProfile.BASELINE, Context3DProfile.BASELINE_EXTENDED, Context3DProfile.STANDARD, Context3DProfile.ENHANCED, Context3DProfile.STANDARD_CONSTRAINED, Context3DProfile.STANDARD_EXTENDED]));
		}
		
		private function contextCreated(event:Event):void {
			trace("contextCreated");
			
			context3D = stage.stage3Ds[0].context3D;
			context3D.enableErrorChecking = true;
			context3D.configureBackBuffer(640, 480, 4, true, true, true);
			trace(context3D.driverInfo, context3D.profile);
			
			playVideo();
		}
		
		private function playVideo():void {
			removeEventListener(Event.ENTER_FRAME, enterFrame);
			
			if (videoTexture != null) {
				videoTexture.dispose();//This ilne cause crash
				videoTexture = null;
			}
			if (_netStream != null) {
				_netStream.removeEventListener(NetStatusEvent.NET_STATUS, netStream_netStatus);
				_netStream.close();
				_netStream = null;
			}
			if (_netConnection != null) {
				_netConnection.removeEventListener(NetStatusEvent.NET_STATUS, netConnection_netStatus);
				_netConnection.close();
				_netConnection = null;
			}
			
			
			var vertices:Vector.<Number> = Vector.<Number>([
			1, -1, 0, 1, 0,
			1, 1, 0, 1, 1,
			-1, 1, 0, 0, 1,
			-1,-1, 0, 0, 0
			]);
			
			var vertexbuffer:VertexBuffer3D = context3D.createVertexBuffer(4, 5);
			vertexbuffer.uploadFromVector(vertices, 0, 4);
			
			indexbuffer = context3D.createIndexBuffer(6);
			indexbuffer.uploadFromVector(Vector.<uint>([0, 1, 2, 2, 3, 0]), 0, 6);
			
			var vertexShaderAssembler:AGALMiniAssembler = new AGALMiniAssembler();
			vertexShaderAssembler.assemble(Context3DProgramType.VERTEX, "m44 op, va0, vc0\n" + "mov v0, va1");
			
			var fragmentShaderAssembler:AGALMiniAssembler = new AGALMiniAssembler();
			fragmentShaderAssembler.assemble( Context3DProgramType.FRAGMENT, "tex ft1, v0, fs0 <2d,linear, nomip>\n" + "mov oc, ft1");
			
			var program:Program3D = context3D.createProgram();
			program.upload( vertexShaderAssembler.agalcode, fragmentShaderAssembler.agalcode);
			
			context3D.setVertexBufferAt(0, vertexbuffer, 0, Context3DVertexBufferFormat.FLOAT_3);
			context3D.setVertexBufferAt(1, vertexbuffer, 3, Context3DVertexBufferFormat.FLOAT_2);
			
			videoTexture = context3D.createVideoTexture();
			context3D.setTextureAt(0, videoTexture);
			
			context3D.setProgram(program);
			matrix.appendScale(1, -1, 1);
			context3D.setProgramConstantsFromMatrix(Context3DProgramType.VERTEX, 0, matrix, true);
			
			
			_netConnection = new NetConnection();
			_netConnection.addEventListener(NetStatusEvent.NET_STATUS, netConnection_netStatus);
			_netConnection.connect(null);
		}
		
		private function netConnection_netStatus(e:NetStatusEvent):void {
			if (e.info.code == "NetConnection.Connect.Success"){
				_netStream = new NetStream(_netConnection);
				_netStream.addEventListener(NetStatusEvent.NET_STATUS, netStream_netStatus);
				_netStream.client = {onMetaData:getMeta, onPlayStatus:onPlayStatus};
				_netStream.play("neon.mp4");
				videoTexture.attachNetStream(_netStream);
				
				videoTexture.addEventListener(Event.TEXTURE_READY, renderState);
			}
		}
		
		private function netStream_netStatus(event:NetStatusEvent):void {
			trace(event.info.code);
			switch (event.info.code){
				case "NetStream.Play.StreamNotFound":
					trace("Stream not found");
					break;
				default:
					break;
			}
		}

		private function getMeta(mdata:Object):void {
			trace("metadata");
		}

		private function onPlayStatus(infoObject:Object):void {
			trace("onPlayStatus", infoObject.code);
			playVideo();
		}

		private function renderState(e:Event):void {
			videoTexture.removeEventListener(Event.TEXTURE_READY, renderState);
			trace("renderState");
			render();
			addEventListener(Event.ENTER_FRAME, enterFrame);
		}
	
		private function enterFrame(event:Event):void {
			render();
		}

		private function render():void {
			context3D.clear(1, 0, 0, 1);
			context3D.drawTriangles(indexbuffer);
			context3D.present();
		}

	}
}
```

**Actual Result:**
On every video playback start in LogCat you will see error:
```
System.err: java.lang.NoSuchMethodError: no non-static method "Lcom/adobe/flashruntime/air/VideoTextureSurface;.getHeight()I"
System.err: 	at com.adobe.air.customHandler.callTimeoutFunction(Native Method)
System.err: 	at com.adobe.air.customHandler.handleMessage(customHandler.java:33)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
System.err: 	at android.os.Looper.loop(Looper.java:193)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
or
```
System.err: java.lang.NoSuchMethodError: no non-static method "Lcom/adobe/flashruntime/air/VideoTextureSurface;.getHeight()I"
System.err: 	at com.adobe.air.customHandler.callTimeoutFunction(Native Method)
System.err: 	at com.adobe.air.Entrypoints$1.handleMessage(Entrypoints.java:318)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
System.err: 	at android.os.Looper.loopOnce(Looper.java:346)
System.err: 	at android.os.Looper.loop(Looper.java:475)
System.err: 	at com.adobe.air.Entrypoints.run(Entrypoints.java:339)
System.err: 	at java.lang.Thread.run(Thread.java:1012)
```
No errors in Scout.
Full LogCat log attached above.
*After long time period 10-60 minutes sample could cause `NetStream.Play.Failed` error or application crash (may be memory leak?). Especially with low-performance devices. May be it not related to this one.

**Expected Result:**
Application playback video in a loop without errors/crashes.

## Known Workarounds
none
May be you can just ignore it but seems it has affect badly to stability.

**Comment by itlancer** [comment]
@ajwfrost, issue still exists with latest AIR 51.2.1.1.
I can see a lot of different errors which seems lead to memory leak and then after ~1.5 hours of work in real application (just video playback using Starling).
```
04-18 23:23:00.161 14742 14742 D AdobeAIR: Error when opening [/data/user/0/com.myapp12345.myapp12/cache/app/28b74095-0ec0-4b1d-a2f1-61afc185b118/assets/META-INF/AIR/FlashAuthor.cfg] with mode [r] -> java.io.FileNotFoundException: /data/user/0/com.myapp12345.myapp12/cache/app/28b74095-0ec0-4b1d-a2f1-61afc185b118/assets/META-INF/AIR/FlashAuthor.cfg (No such file or directory)
04-18 23:23:00.161 14742 14742 D AdobeAIR: File URI was /data/user/0/com.myapp12345.myapp12/cache/app/28b74095-0ec0-4b1d-a2f1-61afc185b118/assets/META-INF/AIR/FlashAuthor.cfg
```
```
04-18 23:22:27.886 13586 13586 E [EGL-ERROR]: void __egl_platform_dequeue_buffer(egl_surface *):1809: failed to dequeue buffer from native window 0xdb96a808; err = -38, buf = 0x0,max_allowed_dequeued_buffers 3
04-18 23:22:27.896 13586 14698 E art     : ashmem_create_region failed for 'indirect ref table': Too many open files
04-18 23:22:27.896  4103  4110 E BufferQueueProducer: [SurfaceView - com.myapp12345.myapp12/com.myapp12345.myapp12.AIRAppEntry] dequeueBuffer: attempting to exceed the max dequeued buffer count (2)
04-18 23:22:27.906  4103 13682 D Layer   : Layer (HwcAgt-0x7aad1ba000) No valid buffer now, waiting for new buffer.
04-18 23:22:28.106  4103 13682 D Layer   : Layer (HwcAgt-0x7aad1ba000) No valid buffer now, waiting for new buffer.
04-18 23:22:28.168  4464  4503 W InputDispatcher: channel '2fc5252 com.myapp12345.myapp12/com.myapp12345.myapp12.AIRAppEntry (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
04-18 23:22:28.168  4464  4503 E InputDispatcher: channel '2fc5252 com.myapp12345.myapp12/com.myapp12345.myapp12.AIRAppEntry (server)' ~ Channel is unrecoverably broken and will be disposed!
04-18 23:22:28.169  4464 10714 D GraphicsStats: Buffer count: 7
04-18 23:22:28.170  4464  5105 I WindowManager: WIN DEATH: Window{2fc5252 u0 com.myapp12345.myapp12/com.myapp12345.myapp12.AIRAppEntry}
04-18 23:22:28.170  4464  5105 W InputDispatcher: Attempted to unregister already unregistered input channel '2fc5252 com.myapp12345.myapp12/com.myapp12345.myapp12.AIRAppEntry (server)'
04-18 23:22:28.170  4464  5105 W WindowManager: Force-removing child win Window{b9c26af u0 SurfaceView - com.myapp12345.myapp12/com.myapp12345.myapp12.AIRAppEntry} from container Window{2fc5252 u0 com.myapp12345.myapp12/com.myapp12345.myapp12.AIRAppEntry}
04-18 23:22:28.180  4129  4905 E OMXNodeInstance: !!! Observer died. Quickly, do something, ... anything...
04-18 23:22:28.180  4464 10715 I ActivityManager: Process com.myapp12345.myapp12 (pid 13586) has died
04-18 23:22:28.180  4464 10715 D ActivityManager: cleanUpApplicationRecord -- 13586
04-18 23:22:28.180  4129  4906 E OMXNodeInstance: !!! Observer died. Quickly, do something, ... anything...
04-18 23:22:28.180  4129  4906 E OMXNodeInstance: !!! Observer died. Quickly, mName:=amlogic.avc.decoder.awesome
04-18 23:22:28.180  4129  4906 D OmxComponent: getExtensionIndex 1099 name="OMX.amlogic.index.forceShutdown"
04-18 23:22:28.180  4129  4906 D OmxVideoDecoder: setParameter 645 0x7f000105
04-18 23:22:28.180  4129  4906 D OmxVideoDecoder: OMX.amlogic.index.forceShutdown=true
04-18 23:22:28.180  4129  4906 D OmxComponentManagerImpl: DecreaseEntryNumByName pEntry->mNum=9, pEntry->mMaxNum:9,componentName:OMX.amlogic.avc.decoder.awesome
04-18 23:22:28.181  4129  4906 I omx_core: OMX_freeHandle_num_= 8
04-18 23:22:28.181  4129  4906 D AmlogicVideoDecoderAwesome: ~AmlogicVideoDecoderAwesome
04-18 23:22:28.181  4129  4906 D AmlogicVideoDecoderAwesome: ~AmlogicVideoDecoder
04-18 23:22:28.181  4464 10715 W ActivityManager: Force removing ActivityRecord{a76886d u0 com.myapp12345.myapp12/.AIRAppEntry t4361}: app died, no saved state
04-18 23:22:28.184  4129 13082 E OMXNodeInstance: !!! Observer died. Quickly, do something, ... anything...
04-18 23:22:28.184  4129 13082 E OMXNodeInstance: !!! Observer died. Quickly, mName:=amlogic.avc.decoder.awesome
04-18 23:22:28.184  4129 13082 D OmxComponent: getExtensionIndex 1099 name="OMX.amlogic.index.forceShutdown"
04-18 23:22:28.184  4129 13082 D OmxVideoDecoder: setParameter 645 0x7f000105
04-18 23:22:28.184  4129 13082 D OmxVideoDecoder: OMX.amlogic.index.forceShutdown=true
04-18 23:22:28.184  4129 13082 D OmxComponentManagerImpl: DecreaseEntryNumByName pEntry->mNum=8, pEntry->mMaxNum:9,componentName:OMX.amlogic.avc.decoder.awesome
04-18 23:22:28.184  4129 13082 I omx_core: OMX_freeHandle_num_= 7
04-18 23:22:28.184  4129 13082 D AmlogicVideoDecoderAwesome: ~AmlogicVideoDecoderAwesome
04-18 23:22:28.185  4129 13082 D AmlogicVideoDecoderAwesome: ~AmlogicVideoDecoder
04-18 23:22:28.185  4129 19569 E OMXNodeInstance: !!! Observer died. Quickly, do something, ... anything...
04-18 23:22:28.185  4129 19569 E OMXNodeInstance: !!! Observer died. Quickly, mName:=amlogic.avc.decoder.awesome
04-18 23:22:28.185  4129 19569 D OmxComponent: getExtensionIndex 1099 name="OMX.amlogic.index.forceShutdown"
04-18 23:22:28.186  4129 19569 D OmxVideoDecoder: setParameter 645 0x7f000105
04-18 23:22:28.186  4129 19569 D OmxVideoDecoder: OMX.amlogic.index.forceShutdown=true
04-18 23:22:28.186  4129 19569 D OmxComponentManagerImpl: DecreaseEntryNumByName pEntry->mNum=7, pEntry->mMaxNum:9,componentName:OMX.amlogic.avc.decoder.awesome
04-18 23:22:28.186  4129 19569 I omx_core: OMX_freeHandle_num_= 6
04-18 23:22:28.187  4129  4592 E OMXNodeInstance: !!! Observer died. Quickly, do something, ... anything...
04-18 23:22:28.187  4129  4592 E OMXNodeInstance: !!! Observer died. Quickly, mName:=amlogic.avc.decoder.awesome
04-18 23:22:28.187  4129  4592 D OmxComponent: getExtensionIndex 1099 name="OMX.amlogic.index.forceShutdown"
04-18 23:22:28.187  4129  4592 D OmxVideoDecoder: setParameter 645 0x7f000105
04-18 23:22:28.187  4129  4592 D OmxVideoDecoder: OMX.amlogic.index.forceShutdown=true
04-18 23:22:28.188  4129 21551 E OMXNodeInstance: !!! Observer died. Quickly, do something, ... anything...
04-18 23:22:28.188  4129 21551 E OMXNodeInstance: !!! Observer died. Quickly, mName:=amlogic.avc.decoder.awesome
04-18 23:22:28.188  4129 21551 D OmxComponent: getExtensionIndex 1099 name="OMX.amlogic.index.forceShutdown"
04-18 23:22:28.188  4129 21551 D OmxVideoDecoder: setParameter 645 0x7f000105
04-18 23:22:28.188  4129 21551 D OmxVideoDecoder: OMX.amlogic.index.forceShutdown=true
04-18 23:22:28.189  4129  4908 E OMXNodeInstance: !!! Observer died. Quickly, do something, ... anything...
04-18 23:22:28.189  4129  4908 E OMXNodeInstance: !!! Observer died. Quickly, mName:=amlogic.avc.decoder.awesome
04-18 23:22:28.189  4129  4908 D OmxComponent: getExtensionIndex 1099 name="OMX.amlogic.index.forceShutdown"
04-18 23:22:28.189  4129  4908 D OmxVideoDecoder: setParameter 645 0x7f000105
04-18 23:22:28.189  4129  4908 D OmxVideoDecoder: OMX.amlogic.index.forceShutdown=true
04-18 23:22:28.190  4129 20038 E OMXNodeInstance: !!! Observer died. Quickly, do something, ... anything...
04-18 23:22:28.190  4129 20038 E OMXNodeInstance: !!! Observer died. Quickly, mName:=amlogic.avc.decoder.awesome
04-18 23:22:28.190  4129 20038 D OmxComponent: getExtensionIndex 1099 name="OMX.amlogic.index.forceShutdown"
04-18 23:22:28.190  4129 20038 D OmxVideoDecoder: setParameter 645 0x7f000105
04-18 23:22:28.190  4129 20038 D OmxVideoDecoder: OMX.amlogic.index.forceShutdown=true
04-18 23:22:28.190  4129  4175 E OMXNodeInstance: !!! Observer died. Quickly, do something, ... anything...
04-18 23:22:28.190  4129  4175 E OMXNodeInstance: !!! Observer died. Quickly, mName:=amlogic.avc.decoder.awesome
04-18 23:22:28.190  4129  4175 D OmxComponent: getExtensionIndex 1099 name="OMX.amlogic.index.forceShutdown"
04-18 23:22:28.190  4129  4175 D OmxVideoDecoder: setParameter 645 0x7f000105
04-18 23:22:28.190  4129  4175 D OmxVideoDecoder: OMX.amlogic.index.forceShutdown=true
04-18 23:22:28.192  4129  5224 E OMXNodeInstance: !!! Observer died. Quickly, do something, ... anything...
04-18 23:22:28.192  4129  5224 E OMXNodeInstance: !!! Observer died. Quickly, mName:=amlogic.avc.decoder.awesome
04-18 23:22:28.192  4129  5224 D OmxComponent: getExtensionIndex 1099 name="OMX.amlogic.index.forceShutdown"
04-18 23:22:28.192  4129  5224 D OmxVideoDecoder: setParameter 645 0x7f000105
04-18 23:22:28.192  4129  5224 D OmxVideoDecoder: OMX.amlogic.index.forceShutdown=true
04-18 23:22:28.194  4118  4118 I Zygote  : Process 13586 exited due to signal (11)
04-18 23:22:28.197  4129 19569 D AmlogicVideoDecoderAwesome: ~AmlogicVideoDecoderAwesome
04-18 23:22:28.197  4129 19569 D AmlogicVideoDecoderAwesome: ~AmlogicVideoDecoder
04-18 23:22:28.197  4129  4592 D OmxComponentManagerImpl: DecreaseEntryNumByName pEntry->mNum=6, pEntry->mMaxNum:9,componentName:OMX.amlogic.avc.decoder.awesome
04-18 23:22:28.197  4129  4592 I omx_core: OMX_freeHandle_num_= 5
04-18 23:22:28.198  4129  4592 D AmlogicVideoDecoderAwesome: ~AmlogicVideoDecoderAwesome
04-18 23:22:28.198  4129  4592 D AmlogicVideoDecoderAwesome: ~AmlogicVideoDecoder
04-18 23:22:28.198  4129 21551 D OmxComponentManagerImpl: DecreaseEntryNumByName pEntry->mNum=5, pEntry->mMaxNum:9,componentName:OMX.amlogic.avc.decoder.awesome
04-18 23:22:28.198  4129 21551 I omx_core: OMX_freeHandle_num_= 4
04-18 23:22:28.199  4129 21551 D AmlogicVideoDecoderAwesome: ~AmlogicVideoDecoderAwesome
04-18 23:22:28.199  4129 21551 D AmlogicVideoDecoderAwesome: ~AmlogicVideoDecoder
04-18 23:22:28.199  4129  4908 D OmxComponentManagerImpl: DecreaseEntryNumByName pEntry->mNum=4, pEntry->mMaxNum:9,componentName:OMX.amlogic.avc.decoder.awesome
04-18 23:22:28.199  4129  4908 I omx_core: OMX_freeHandle_num_= 3
04-18 23:22:28.201  4129  4908 D AmlogicVideoDecoderAwesome: ~AmlogicVideoDecoderAwesome
04-18 23:22:28.201  4129  4908 D AmlogicVideoDecoderAwesome: ~AmlogicVideoDecoder
04-18 23:22:28.201  4129 20038 D OmxComponentManagerImpl: DecreaseEntryNumByName pEntry->mNum=3, pEntry->mMaxNum:9,componentName:OMX.amlogic.avc.decoder.awesome
04-18 23:22:28.201  4129 20038 I omx_core: OMX_freeHandle_num_= 2
04-18 23:22:28.203  4129 20038 D AmlogicVideoDecoderAwesome: ~AmlogicVideoDecoderAwesome
04-18 23:22:28.203  4129 20038 D AmlogicVideoDecoderAwesome: ~AmlogicVideoDecoder
04-18 23:22:28.203  4129  4175 D OmxComponentManagerImpl: DecreaseEntryNumByName pEntry->mNum=2, pEntry->mMaxNum:9,componentName:OMX.amlogic.avc.decoder.awesome
04-18 23:22:28.203  4129  4175 I omx_core: OMX_freeHandle_num_= 1
04-18 23:22:28.204  4129  4175 D AmlogicVideoDecoderAwesome: ~AmlogicVideoDecoderAwesome
04-18 23:22:28.204  4129  4175 D AmlogicVideoDecoderAwesome: ~AmlogicVideoDecoder
04-18 23:22:28.205  4129  5224 D OmxComponentManagerImpl: DecreaseEntryNumByName pEntry->mNum=1, pEntry->mMaxNum:9,componentName:OMX.amlogic.avc.decoder.awesome
04-18 23:22:28.205  4129  5224 I omx_core: OMX_freeHandle_num_= 0
04-18 23:22:28.209  4129  5224 D AmlogicVideoDecoderAwesome: ~AmlogicVideoDecoderAwesome
04-18 23:22:28.209  4129  5224 D AmlogicVideoDecoderAwesome: ~AmlogicVideoDecoder
04-18 23:22:28.233  4464  5105 W WindowManager: Force-removing child win Window{f9ffabc u0 SurfaceView - com.myapp12345.myapp12/com.myapp12345.myapp12.AIRAppEntry} from container Window{2fc5252 u0 com.myapp12345.myapp12/com.myapp12345.myapp12.AIRAppEntry}
04-18 23:22:28.237 24379 24460 D resmon  : Mem trigger
04-18 23:22:28.246  4103  4103 I hwcomposer: no omx video layer, no OVERLAY, set display_mode 0->1
04-18 23:22:28.247  4098  4163 I SystemControl: Matched uevent message with pattern: DEVPATH=/devices/virtual/switch/video_layer1
04-18 23:22:28.247  4098  4163 I SystemControl: HDCP TX switch_name: video_layer1 ,switch_state: 0
04-18 23:22:28.258  4464  5105 W WindowManager: Force-removing child win Window{eeb3a45 u0 SurfaceView - com.myapp12345.myapp12/com.myapp12345.myapp12.AIRAppEntry} from container Window{2fc5252 u0 com.myapp12345.myapp12/com.myapp12345.myapp12.AIRAppEntry}
04-18 23:22:28.298  4464  9166 W WindowManager: Failed looking up window
04-18 23:22:28.298  4464  9166 W WindowManager: java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@3f03923 does not exist
04-18 23:22:28.298  4464  9166 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9432)
04-18 23:22:28.298  4464  9166 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9423)
04-18 23:22:28.298  4464  9166 W WindowManager: 	at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1807)
04-18 23:22:28.298  4464  9166 W WindowManager: 	at android.os.BinderProxy.sendDeathNotice(Binder.java:688)
04-18 23:22:28.298  4464  9166 I WindowManager: WIN DEATH: null
```
```
04-18 23:05:39.828 13586 13586 I CreateVideoDecoder: using MediaCodec Decoder
04-18 23:05:39.849 13586 13586 W System.err: java.lang.NoSuchMethodError: no non-static method "Lcom/adobe/flashruntime/air/VideoTextureSurface;.getHeight()I"
04-18 23:05:39.850 13586 13586 W System.err: 	at com.adobe.air.customHandler.callTimeoutFunction(Native Method)
04-18 23:05:39.850 13586 13586 W System.err: 	at com.adobe.air.customHandler.handleMessage(customHandler.java:35)
04-18 23:05:39.850 13586 13586 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-18 23:05:39.850 13586 13586 W System.err: 	at android.os.Looper.loop(Looper.java:154)
04-18 23:05:39.850 13586 13586 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6121)
04-18 23:05:39.850 13586 13586 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-18 23:05:39.850 13586 13586 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
04-18 23:05:39.850 13586 13586 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
04-18 23:05:39.850 13586 13586 D runtime : /13586: AndroidMediaCodec::Initialized
04-18 23:05:39.850 13586 13586 D runtime : /13586: ndroidMediaFormat::InitClass initialized
04-18 23:05:39.853 13586 13586 D runtime : /13586: AndroidMediaCodec::Initialized
04-18 23:05:39.858  4133  4233 I MediaPlayerService: MediaPlayerService::getOMX
04-18 23:05:39.860 13586  7867 I OMXClient: MuxOMX ctor
04-18 23:05:39.863  4129  4907 I OMXMaster: makeComponentInstance(OMX.amlogic.avc.decoder.awesome) in mediacodec process
04-18 23:05:39.863  4129  4907 D OmxComponentManagerImpl: support frame mode
04-18 23:05:39.863  4129  4907 D OmxComponentManagerImpl: format support multi-instance
04-18 23:05:39.863  4129  4907 D OmxComponentManagerImpl: getEntryByName_2_num=9, componentName:OMX.amlogic.avc.decoder.awesome
04-18 23:05:39.863  4129  4907 E OMX     : FAILED to allocate omx component 'OMX.amlogic.avc.decoder.awesome' err=InsufficientResources(0x80001000)
04-18 23:05:39.863 13586  7867 W ACodec  : Allocating component 'OMX.amlogic.avc.decoder.awesome' failed, try next one.
04-18 23:05:39.865  4129 21551 I OMXMaster: makeComponentInstance(OMX.google.h264.decoder) in mediacodec process
```
```
04-18 23:22:23.363  4103  4143 E BufferQueueProducer: [SurfaceView - com.myapp12345.myapp12/com.myapp12345.myapp12.AIRAppEntry] dequeueBuffer: attempting to exceed the max dequeued buffer count (2)
04-18 23:22:23.364 13586 13586 E [EGL-ERROR]: void __egl_platform_dequeue_buffer(egl_surface *):1809: failed to dequeue buffer from native window 0xdb96a808; err = -38, buf = 0x0,max_allowed_dequeued_buffers 3
04-18 23:22:23.371 13586 14455 E HAL     : load: module=/system/lib/hw/gralloc.amlogic.so
04-18 23:22:23.371 13586 14455 E HAL     : dlopen failed: library "/system/lib/hw/gralloc.amlogic.so" not found
04-18 23:22:23.371 13586 14455 E [Gralloc-ERROR]: void gralloc_backend_sync(private_handle_t *):136 Could not get gralloc module for handle 0x964902e0
04-18 23:22:23.372  4103  4110 E BufferQueueProducer: [SurfaceView - com.myapp12345.myapp12/com.myapp12345.myapp12.AIRAppEntry] dequeueBuffer: attempting to exceed the max dequeued buffer count (2)
04-18 23:22:23.372 13586 13586 E [EGL-ERROR]: void __egl_platform_dequeue_buffer(egl_surface *):1809: failed to dequeue buffer from native window 0xdb96a808; err = -38, buf = 0x0,max_allowed_dequeued_buffers 3
```
```
04-18 23:22:23.400 13586 13586 E GLConsumer: [SurfaceTexture-3-13586-194] syncForReleaseLocked: error dup'ing native fence fd: 0x3000
04-18 23:22:23.401 13586 13586 I AdobeAIR: Exception caught from Java: java.lang.RuntimeException: Error during updateTexImage (see logcat for details)
04-18 23:22:23.402  4103  4463 E BufferQueueProducer: [SurfaceView - com.myapp12345.myapp12/com.myapp12345.myapp12.AIRAppEntry] dequeueBuffer: attempting to exceed the max dequeued buffer count (2)
```
Full log attached (application work, then crash, then started again):
[android_videotexture_videotexturesurface_getheight_error2.zip](https://github.com/user-attachments/files/19822809/android_videotexture_videotexturesurface_getheight_error2.zip)
