### ISSUE TITLE
Calling TimeZone.availableTimeZoneNames cause application to crash

### ISSUE THREAD

**Issue by ylazy** [airsdk/Adobe-Runtime-Support#3421]
I tried to call the new Air 50 API:

```as
trace(TimeZone.availableTimeZoneNames);
```

and my app crashed!

```
Exception in debugger: flash.tools.debugger.NotConnectedException: Debugger is no longer connected to Flash Player
	at flash.tools.debugger.concrete.PlayerSession.isSuspended(PlayerSession.java:311)
	at flash.tools.debugger.threadsafe.ThreadSafeSession.isSuspended(ThreadSafeSession.java:174)
	at com.as3mxml.vscode.SWFDebugSession$SessionRunner.run(SWFDebugSession.java:255)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

https://github.com/user-attachments/assets/5792e737-5c7f-4f0a-be13-860ab73fc8f2

Please view the video for more detail.

Thanks!

**Comment by ylazy** [comment]
The issue related to the application ID. I don't know why but changing the application ID fixes the issue.

https://github.com/user-attachments/assets/4b6bb8c8-761d-4480-a828-57a898c3d71b

**Comment by ajwfrost** [comment]
@ylazy  that's a little bizarre! No idea how that can be related, but we can try it out here and see what happens... Thanks for the clear videos and explanations!

**Comment by ajwfrost** [comment]
We can't reproduce this using the normal Flash Debugger, wondering if it's possible to get a zip-up of your VSCode folder there so that we can try it with the exact same settings etc?

thanks

**Comment by ylazy** [comment]
[bug.zip](https://github.com/user-attachments/files/16757062/bug.zip)

I've attached a zip file to reproduce the problem.

- unzip
- edit `Launch.bat` and change the `Air SDK 51.1.1.1` Folder in `set AirHome=Y:/Development/ActionScript/SDK/AdobeAir/Windows/51.1`. Save.
- Click to run `Launch.bat`. On my machine (Windows 11 24H2 26100.1586) it crashed.

https://github.com/user-attachments/assets/98828813-8925-4349-9df4-757db625b1db

It's so strange. Now the issue happens with any application id.

**Comment by ajwfrost** [comment]
We just tried this on a 23H2 build but it worked fine. Can you double-check the version you have please, I don't think 24H2 is a thing yet? or are you on some beta version?!

I suspect if it's crashing in that call, there's a library/dependency missing. We can add in some debugging outputs perhaps, if you're able to try with those...

**Comment by ylazy** [comment]
> We just tried this on a 23H2 build but it worked fine. Can you double-check the version you have please, I don't think 24H2 is a thing yet? or are you on some beta version?!

Yes I'm joining the Windows Insider Program.

![image](https://github.com/user-attachments/assets/39fcef32-975a-4b50-b218-60aea5b0f90b)

I realized that the issue only depend on time on day. At this morning, the issue **did happened**. At this lunch, the issue **did not** happened. At this time I'm writing, the issue **is happening**. I've just downloaded the zip file that I uploaded today and run it, and it's surprising that it's not crashing now 🤔
