### ISSUE TITLE
Crash on Amazon device with AIR 5.1.1.1 and beyond

### ISSUE THREAD

**Issue by Michoko92** [airsdk/Adobe-Runtime-Support#3458]
Hi,

When I build an APK with AIR 51.1.1.1 and further versions for my Amazon testing device  (which is pretty old : Fire HD tablet, 3rd generation, running Fire OS 4.5.5.3), the build crashes at startup. Here is the log:
```

09-09 10:36:31.192  5052  5052 E AndroidRuntime: Process: air.com.indiegoes.angelnumber, PID: 5052
09-09 10:36:31.192  5052  5052 E AndroidRuntime: java.lang.UnsatisfiedLinkError: Native method not found: com.adobe.air.AIRWindowSurfaceView.nativeSurfaceCreated:()V
09-09 10:36:31.192  5052  5052 E AndroidRuntime: 	at com.adobe.air.AIRWindowSurfaceView.nativeSurfaceCreated(Native Method)
09-09 10:36:31.192  5052  5052 E AndroidRuntime: 	at com.adobe.air.AIRWindowSurfaceView.surfaceCreated(AIRWindowSurfaceView.java:780)
09-09 10:36:31.192  5052  5052 E AndroidRuntime: 	at android.view.SurfaceView.updateWindow(SurfaceView.java:572)
09-09 10:36:31.192  5052  5052 E AndroidRuntime: 	at android.view.SurfaceView.access$000(SurfaceView.java:86)
09-09 10:36:31.192  5052  5052 E AndroidRuntime: 	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:175)
09-09 10:36:31.192  5052  5052 E AndroidRuntime: 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:847)
09-09 10:36:31.192  5052  5052 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1959)
09-09 10:36:31.192  5052  5052 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1057)
09-09 10:36:31.192  5052  5052 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5857)
09-09 10:36:31.192  5052  5052 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:815)
09-09 10:36:31.192  5052  5052 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:628)
09-09 10:36:31.192  5052  5052 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:598)
09-09 10:36:31.192  5052  5052 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:801)
09-09 10:36:31.192  5052  5052 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:755)
09-09 10:36:31.192  5052  5052 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-09 10:36:31.192  5052  5052 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:145)
09-09 10:36:31.192  5052  5052 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5266)
09-09 10:36:31.192  5052  5052 E AndroidRuntime: 	at java.lang.reflect.Method.invokeNative(Native Method)
09-09 10:36:31.192  5052  5052 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:515)
09-09 10:36:31.192  5052  5052 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:826)
09-09 10:36:31.192  5052  5052 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:642)
09-09 10:36:31.192  5052  5052 E AndroidRuntime: 	at dalvik.system.NativeStart.main(Native Method)
09-09 10:36:31.192  5052  5052 I AndroidRuntime: To Report FATAL to activityManagerService
09-09 10:36:31.246   458   871 W ActivityManager:   Force finishing activity air.com.indiegoes.angelnumber/.AIRAppEntry
```

If I build the same APK with AIR 51.0.1.4, it works fine. Did the Android requirements change between AIR 51.0.x and AIR 51.1.x, to the point I can't target this platform version any longer?

Here is the manifest:

 ```
<android> 
	<colorDepth>16bit</colorDepth>
  	<manifestAdditions> 
          <![CDATA[
              <manifest android:installLocation="auto">
				<uses-sdk android:minSdkVersion="16" android:targetSdkVersion="30" />
				
				<uses-permission android:name="android.permission.INTERNET"/>
				<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>

                <uses-configuration android:reqFiveWayNav="false"/>
                <supports-screens android:smallScreens="true"
									android:normalScreens="true"
									android:largeScreens="true"
									android:xlargeScreens="true"/>
                <uses-feature android:required="false" android:name="android.hardware.touchscreen.multitouch"/>
				  
				<application android:enabled="true">
					<activity android:name="com.distriqt.extension.share.permissions.AuthorisationActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar" /> 
					
					<receiver android:name="com.amazon.device.iap.ResponseReceiver" >
						<intent-filter>
							<action android:name="com.amazon.inapp.purchasing.NOTIFY"
								android:permission="com.amazon.inapp.purchasing.Permission.NOTIFY" />
						</intent-filter>
					</receiver>
					
				</application>
              </manifest>
          ]]>
      </manifestAdditions>
    </android>
```
Thank you!

**Comment by ajwfrost** [comment]
Hi

We had made some changes in 51.1 to bring the Android build process up to date, which meant that our "minimum api" level is now 21 across the board (rather than just for 64-bit) - previously it had been 16 for 32-bit variants.  From memory - I think with the updated Android Gradle Plug-in (needed in order to build for target SDK 34) we were then finding problems with the older minSdkVersion value - I don't see any functional changes in the commit there.

So - yes it looks like Fire OS 4 uses Android API level 19 which means this would be the issue..

thanks
