### ISSUE TITLE
App crash on all android test devices

### ISSUE THREAD

**Issue by hadisn** [airsdk/Adobe-Runtime-Support#3463]
Hi, with AIR 51.1.1.4 app crash on startup, previous version works fine...

`No implementation found for void com.adobe.air.AIRWindowSurfaceView.nativeSurfaceCreated() (tried Java_com_adobe_air_AIRWindowSurfaceView_nativeSurfaceCreated and Java_com_adobe_air_AIRWindowSurfaceView_nativeSurfaceCreated__)
2024-09-11 14:48:45.234  6444-6444  AndroidRuntime          air.com.gamblershome.hotfruits       D  Shutting down VM
2024-09-11 14:48:45.234  6444-6444  AndroidRuntime          air.com.gamblershome.hotfruits       E  FATAL EXCEPTION: main
                                                                                                    Process: air.com.gamblershome.hotfruits, PID: 6444
                                                                                                    java.lang.UnsatisfiedLinkError: No implementation found for void com.adobe.air.AIRWindowSurfaceView.nativeSurfaceCreated() (tried Java_com_adobe_air_AIRWindowSurfaceView_nativeSurfaceCreated and Java_com_adobe_air_AIRWindowSurfaceView_nativeSurfaceCreated__)
                                                                                                    	at com.adobe.air.AIRWindowSurfaceView.nativeSurfaceCreated(Native Method)
                                                                                                    	at com.adobe.air.AIRWindowSurfaceView.surfaceCreated(AIRWindowSurfaceView.java:780)
                                                                                                    	at android.view.SurfaceView.updateWindow(SurfaceView.java:618)
                                                                                                    	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:161)
                                                                                                    	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2206)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1255)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6339)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:751)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                    	at android.os.Looper.loop(Looper.java:154)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6138)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)`

**Comment by ajwfrost** [comment]
Can you check whether there's an earlier logcat output with the AIR version code and platform details? and can you also please confirm the contents of the "lib" folder within the APK file, if you open it in a zip file manager?

Typically this issue happens if the wrong type of APK is used on a device.. I might see if we can get some better error messaging coming out for this kind of scenario.

thanks

**Comment by hadisn** [comment]
> Can you check whether there's an earlier logcat output with the AIR version code and platform details? and can you also please confirm the contents of the "lib" folder within the APK file, if you open it in a zip file manager?
> 
Yeah, this could be problem, there is only armeabi-v7a version in "lib" folder when build with Adobe Animate and AIR 51.1.1.4, just switch to AIR 51.1.1.3 and there it's ok.

I also have problem with ios app, it crash at startup and I can't see error because testing from adobe animate, GADApplicationIdentifier added correctly, but I am not sure about iOS sdk on windows, tried to download manually but got ton of errors... Thinks it's because of distriqt ANE, app without ads works fine...

**Comment by hadisn** [comment]
@ajwfrost sorry for bothering you about this, I forgot to uncomment `CreateAndroidAppBundle=true` :)

Btw, regarding ios app crash, I read this suggestion from @marchbold : https://docs.airnativeextensions.com/docs/adverts/troubleshooting/#ios-crash

I think that I added info additions correctly, but I am not sure about iOS SDK, where and how to download it on windows. I tried to download it from here: https://github.com/xybp888/iOS-SDKs/releases. But with than it gives me a lot of errors... Can you suggest solution please.

Thanks
