### ISSUE TITLE
The following exception occurred when use AIRSDK MacOS 51.1.1.4 version

### ISSUE THREAD

**Issue by pengyangjin** [airsdk/Adobe-Runtime-Support#3478]
packageIpaMac:
     [echo] p12->antResource/key/ios/xdyy_dev.p12
     [echo] mobileprovision->antResource/key/ios/xdyyiphone_dev.mobileprovision
     [java] Java HotSpot(TM) 64-Bit Server VM warning: CodeCache is full. Compiler has been disabled.
     [java] CodeCache: size=131072Kb used=5776Kb max_used=5776Kb free=125295Kb
     [java]  bounds [0x00000001049a8000, 0x0000000104f58000, 0x000000010c9a8000]
     [java]  total_blobs=1850 nmethods=1483 adapters=282
     [java]  compilation: disabled (not enough contiguous free space left)
     [java] Java HotSpot(TM) 64-Bit Server VM warning: Try increasing the code cache size using -XX:ReservedCodeCacheSize=
     [java] Warning: MinimumOSVersion passed in app-xml is less than supported version, ignoring MinimumOSVersion value
     [java] ERROR:  ''
     [java] javax.xml.transform.TransformerException: java.lang.NullPointerException
     [java] 	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:739)
     [java] 	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:345)
     [java] 	at com.adobe.air.Plist.getXMLString(Plist.java)
     [java] 	at com.adobe.air.ipa.IPAOutputStream.addInfoPlist(IPAOutputStream.java)
     [java] 	at com.adobe.air.ipa.IPAOutputStream.addApplicationDescriptor(IPAOutputStream.java)
     [java] 	at com.adobe.air.ApplicationPackager.addSpecialFiles(ApplicationPackager.java)
     [java] 	at com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
     [java] 	at com.adobe.air.ipa.IPAPackager.createPackage(IPAPackager.java)
     [java] 	at com.adobe.air.ADT.parseArgsAndGo(ADT.java)
     [java] 	at com.adobe.air.ADT.run(ADT.java)
     [java] 	at com.adobe.air.ADT.main(ADT.java)
     [java] Caused by: java.lang.NullPointerException
     [java] 	at com.sun.org.apache.xml.internal.serializer.ToUnknownStream.characters(ToUnknownStream.java:343)
     [java] 	at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:242)
     [java] 	at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:228)
     [java] 	at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:228)
     [java] 	at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:228)
     [java] 	at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:134)
     [java] 	at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:96)
     [java] 	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transformIdentity(TransformerImpl.java:686)
     [java] 	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:730)
     [java] 	... 10 more
     [java] ---------
     [java] java.lang.NullPointerException
     [java] 	at com.sun.org.apache.xml.internal.serializer.ToUnknownStream.characters(ToUnknownStream.java:343)
     [java] 	at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:242)
     [java] 	at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:228)
     [java] 	at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:228)
     [java] 	at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:228)
     [java] 	at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:134)
     [java] 	at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:96)
     [java] 	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transformIdentity(TransformerImpl.java:686)
     [java] 	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:730)
     [java] 	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:345)
     [java] 	at com.adobe.air.Plist.getXMLString(Plist.java)
     [java] 	at com.adobe.air.ipa.IPAOutputStream.addInfoPlist(IPAOutputStream.java)
     [java] 	at com.adobe.air.ipa.IPAOutputStream.addApplicationDescriptor(IPAOutputStream.java)
     [java] 	at com.adobe.air.ApplicationPackager.addSpecialFiles(ApplicationPackager.java)
     [java] 	at com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
     [java] 	at com.adobe.air.ipa.IPAPackager.createPackage(IPAPackager.java)
     [java] 	at com.adobe.air.ADT.parseArgsAndGo(ADT.java)
     [java] 	at com.adobe.air.ADT.run(ADT.java)
     [java] 	at com.adobe.air.ADT.main(ADT.java)
     [java] unexpected failure: PLIST generation failed due to transformer error:javax.xml.transform.TransformerException: java.lang.NullPointerException
     [java] java.io.IOException: PLIST generation failed due to transformer error:javax.xml.transform.TransformerException: java.lang.NullPointerException
     [java] 	at com.adobe.air.Plist.getXMLString(Plist.java)
     [java] 	at com.adobe.air.ipa.IPAOutputStream.addInfoPlist(IPAOutputStream.java)
     [java] 	at com.adobe.air.ipa.IPAOutputStream.addApplicationDescriptor(IPAOutputStream.java)
     [java] 	at com.adobe.air.ApplicationPackager.addSpecialFiles(ApplicationPackager.java)
     [java] 	at com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
     [java] 	at com.adobe.air.ipa.IPAPackager.createPackage(IPAPackager.java)
     [java] 	at com.adobe.air.ADT.parseArgsAndGo(ADT.java)
     [java] 	at com.adobe.air.ADT.run(ADT.java)
     [java] 	at com.adobe.air.ADT.main(ADT.java)

Just updated the Adobe Air SDK, nothing else has changed.In version 50.2.4.4, it is normal.The intermediate version was skipped and not attempted.Use jdk 1.8 on macOS 14.4.1 at mac mini m1,2020.

**Comment by a9848840** [comment]
@pengyangjin 

Have you solved this problem?
https://github.com/airsdk/Adobe-Runtime-Support/discussions/2088#discussioncomment-10687958
I also encountered similar problems
Can you share the solution? Thanks

**Comment by pengyangjin** [comment]
yes, I have&nbsp;solved this problem yet. Update the JDK from jdk 1.8 to JDK 17. May be JDK 11 also ok, I am not sure.


pengyangjin
***@***.***







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "airsdk/Adobe-Runtime-Support"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月20日(星期五) 下午2:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [airsdk/Adobe-Runtime-Support] The following exception occurred when use AIRSDK MacOS 51.1.1.4 version (Issue #3478)





 
@pengyangjin
 
Have you solved this problem?
 #2088 (reply in thread)
 I also encountered similar problems
 Can you share the solution? Thanks

**Comment by a9848840** [comment]
I downloaded JDK 17 using MAC, where do I need to set the java path?
Thanks

**Comment by pengyangjin** [comment]
you can use google to search "how to set JAVA_PATH in osx".

**Comment by pengyangjin** [comment]
> I downloaded JDK 17 using MAC, where do I need to set the java path? Thanks

you can use google to search "how to set JAVA_PATH in osx".

**Comment by a9848840** [comment]
Packaging successful, thank you savior

**Comment by ajwfrost** [comment]
In case this arises again .. we just got the same call stack trace and it was caused by a problem in the Info.plist file that ADT is generating:
```
[java] at com.adobe.air.Plist.getXMLString(Plist.java)
```
So if you have any malformed plist entries (although they may be valid XML) this could happen. In our case it's actually a built-in issue, rather than the InfoAdditions, where we are assuming we get a value for the `<orientationAnimation>` field from the app descriptor validator object: but if you're not using the 51.1 namespace, this will return null resulting in an empty string in the plist file, and the above error. Which I think means you need to use a 51.1 app descriptor namespace if you're using the 51.1 version of ADT...
