### ISSUE TITLE
Problems opening the app

### ISSUE THREAD

**Issue by megajogos** [airsdk/Adobe-Runtime-Support#3518]
Problem Description:
I have noticed some delay in our app's startup for a while, especially on the initial screen before the splash screen loads. I suspect there might be some errors in the AndroidManifest.xml file that are causing this delay. I would like to know how I can optimize this issue and resolve the errors related to com.google.android.gms.

I am sending the extensions I am using, along with the AndroidManifest.xml file for review. I have also attached logs collected from different devices and emulators.

Infos:
AIR SDK version 51.0.1.4
Environment: Android
[log pixel6 pro api30 strictmode.txt](https://github.com/user-attachments/files/17346419/log.pixel6.pro.api30.strictmode.txt)
[Logcat Samsung A32.txt](https://github.com/user-att
[logcat moto g play strict mode.txt](https://github.com/user-attachments/files/17346430/logcat.moto.g.play.strict.mode.txt)
achments/files/17346420/Logcat.Samsung.A32.txt)
[logcat redimi 9A.txt](https://github.com/user-attachments/files/17346432/logcat.redimi.9A.txt)

[extensions.txt](https://github.com/user-attachments/files/17346421/extensions.txt)
[AndroidManifest.txt](https://github.com/user-attachments/files/17346428/AndroidManifest.txt)

**Comment by megajogos** [comment]
Another point that StrictMode points out as problematic is this one:
```16:20:52.059 FIAM.Headless           air.br.com.megajogos.mobile         air.br.com.megajogos.mobile          I  went foreground
16:20:52.059 art                     air.br.com.megajogos.mobile         air.br.com.megajogos.mobile          I  Background sticky concurrent mark sweep GC freed 66680(2MB) AllocSpace objects, 1(20KB) LOS objects, 18% free, 7MB/8MB, paused 1.234ms total 171.452ms
16:20:52.060 FIAM.Display            air.br.com.megajogos.mobile         air.br.com.megajogos.mobile          I  Binding to activity: AIRAppEntry
16:20:52.060 FIAM.Headless           air.br.com.megajogos.mobile         air.br.com.megajogos.mobile          I  Setting display event component
16:20:52.061 FIAM.Headless           air.br.com.megajogos.mobile         air.br.com.megajogos.mobile          I  Forcing fetch from service rather than cache. Test Device: false | App Fresh Install: true
16:20:52.062 FIAM.Headless           air.br.com.megajogos.mobile         air.br.com.megajogos.mobile          I  Recoverable exception while reading cache: /data/user/0/air.br.com.megajogos.mobile/files/fiam_impressions_store_file (No such file or directory)
16:20:52.142 StrictMode              air.br.com.megajogos.mobile         air.br.com.megajogos.mobile          D  StrictMode policy violation; ~duration=1054 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65567 violation=2
                                                                                                                 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
                                                                                                                 	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:249)
                                                                                                                 	at java.io.File.exists(File.java:780)
                                                                                                                 	at java.lang.Runtime.load0(Runtime.java:913)
                                                                                                                 	at java.lang.System.load(System.java:1537)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.LoadRuntimeLibraries(AndroidActivityWrapper.java:1925)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.<init>(AndroidActivityWrapper.java:440)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.CreateAndroidActivityWrapper(AndroidActivityWrapper.java:364)
                                                                                                                 	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                                 	at air.com.adobe.appentry.AppEntry.createActivityWrapper(AppEntry.java:706)
                                                                                                                 	at air.com.adobe.appentry.AppEntry.onCreate(AppEntry.java:282)
                                                                                                                 	at air.br.com.megajogos.mobile.AIRAppEntry.onCreate(AIRAppEntry.java:25)
                                                                                                                 	at android.app.Activity.performCreate(Activity.java:6785)
                                                                                                                 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1147)
                                                                                                                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2621)
                                                                                                                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2729)
                                                                                                                 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                                                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480)
                                                                                                                 	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                                 	at android.os.Looper.loop(Looper.java:154)
                                                                                                                 	at android.app.ActivityThread.main(ActivityThread.java:6138)
                                                                                                                 	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                                 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
                                                                                                                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
16:20:52.142 StrictMode              air.br.com.megajogos.mobile         air.br.com.megajogos.mobile          D  StrictMode policy violation; ~duration=1045 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65567 violation=2
                                                                                                                 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
                                                                                                                 	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:249)
                                                                                                                 	at java.io.File.exists(File.java:780)
                                                                                                                 	at java.lang.Runtime.load0(Runtime.java:913)
                                                                                                                 	at java.lang.System.load(System.java:1537)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.LoadRuntimeLibraries(AndroidActivityWrapper.java:1927)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.<init>(AndroidActivityWrapper.java:440)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.CreateAndroidActivityWrapper(AndroidActivityWrapper.java:364)
                                                                                                                 	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                                 	at air.com.adobe.appentry.AppEntry.createActivityWrapper(AppEntry.java:706)
                                                                                                                 	at air.com.adobe.appentry.AppEntry.onCreate(AppEntry.java:282)
                                                                                                                 	at air.br.com.megajogos.mobile.AIRAppEntry.onCreate(AIRAppEntry.java:25)
                                                                                                                 	at android.app.Activity.performCreate(Activity.java:6785)
                                                                                                                 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1147)
                                                                                                                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2621)
                                                                                                                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2729)
                                                                                                                 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                                                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480)
                                                                                                                 	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                                 	at android.os.Looper.loop(Looper.java:154)
                                                                                                                 	at android.app.ActivityThread.main(ActivityThread.java:6138)
                                                                                                                 	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                                 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
                                                                                                                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
16:20:52.142 StrictMode              air.br.com.megajogos.mobile         air.br.com.megajogos.mobile          D  StrictMode policy violation; ~duration=853 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65567 violation=2
                                                                                                                 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
                                                                                                                 	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:249)
                                                                                                                 	at java.io.File.exists(File.java:780)
                                                                                                                 	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:512)
                                                                                                                 	at android.app.ContextImpl.getCacheDir(ContextImpl.java:584)
                                                                                                                 	at android.content.ContextWrapper.getCacheDir(ContextWrapper.java:253)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.initializeAndroidAppVars(AndroidActivityWrapper.java:931)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.parseArgs(AndroidActivityWrapper.java:976)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.onCreate(AndroidActivityWrapper.java:998)
                                                                                                                 	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                                 	at air.com.adobe.appentry.AppEntry.InvokeMethod(AppEntry.java:422)
                                                                                                                 	at air.com.adobe.appentry.AppEntry.InvokeWrapperOnCreate(AppEntry.java:403)
                                                                                                                 	at air.com.adobe.appentry.AppEntry.onCreate(AppEntry.java:285)
                                                                                                                 	at air.br.com.megajogos.mobile.AIRAppEntry.onCreate(AIRAppEntry.java:25)
                                                                                                                 	at android.app.Activity.performCreate(Activity.java:6785)
                                                                                                                 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1147)
                                                                                                                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2621)
                                                                                                                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2729)
                                                                                                                 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                                                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480)
                                                                                                                 	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                                 	at android.os.Looper.loop(Looper.java:154)
                                                                                                                 	at android.app.ActivityThread.main(ActivityThread.java:6138)
                                                                                                                 	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                                 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
                                                                                                                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
16:20:52.142 StrictMode              air.br.com.megajogos.mobile         air.br.com.megajogos.mobile          D  StrictMode policy violation; ~duration=852 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65567 violation=2
                                                                                                                 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
                                                                                                                 	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:249)
                                                                                                                 	at java.io.File.exists(File.java:780)
                                                                                                                 	at com.adobe.air.ApplicationFileManager.RefreshAppCache(ApplicationFileManager.java:451)
                                                                                                                 	at com.adobe.air.ApplicationFileManager.processAndroidDataPath(ApplicationFileManager.java:499)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.initializeAndroidAppVars(AndroidActivityWrapper.java:932)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.parseArgs(AndroidActivityWrapper.java:976)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.onCreate(AndroidActivityWrapper.java:998)
                                                                                                                 	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                                 	at air.com.adobe.appentry.AppEntry.InvokeMethod(AppEntry.java:422)
                                                                                                                 	at air.com.adobe.appentry.AppEntry.InvokeWrapperOnCreate(AppEntry.java:403)
                                                                                                                 	at air.com.adobe.appentry.AppEntry.onCreate(AppEntry.java:285)
                                                                                                                 	at air.br.com.megajogos.mobile.AIRAppEntry.onCreate(AIRAppEntry.java:25)
                                                                                                                 	at android.app.Activity.performCreate(Activity.java:6785)
                                                                                                                 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1147)
                                                                                                                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2621)
                                                                                                                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2729)
                                                                                                                 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                                                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480)
                                                                                                                 	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                                 	at android.os.Looper.loop(Looper.java:154)
                                                                                                                 	at android.app.ActivityThread.main(ActivityThread.java:6138)
                                                                                                                 	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                                 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
                                                                                                                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
16:20:52.142 StrictMode              air.br.com.megajogos.mobile         air.br.com.megajogos.mobile          D  StrictMode policy violation; ~duration=852 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65567 violation=2
                                                                                                                 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
                                                                                                                 	at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:240)
                                                                                                                 	at java.io.File.isDirectory(File.java:804)
                                                                                                                 	at com.adobe.air.ApplicationFileManager.deleteDir(ApplicationFileManager.java:463)
                                                                                                                 	at com.adobe.air.ApplicationFileManager.RefreshAppCache(ApplicationFileManager.java:456)
                                                                                                                 	at com.adobe.air.ApplicationFileManager.processAndroidDataPath(ApplicationFileManager.java:499)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.initializeAndroidAppVars(AndroidActivityWrapper.java:932)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.parseArgs(AndroidActivityWrapper.java:976)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.onCreate(AndroidActivityWrapper.java:998)
                                                                                                                 	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                                 	at air.com.adobe.appentry.AppEntry.InvokeMethod(AppEntry.java:422)
                                                                                                                 	at air.com.adobe.appentry.AppEntry.InvokeWrapperOnCreate(AppEntry.java:403)
                                                                                                                 	at air.com.adobe.appentry.AppEntry.onCreate(AppEntry.java:285)
                                                                                                                 	at air.br.com.megajogos.mobile.AIRAppEntry.onCreate(AIRAppEntry.java:25)
                                                                                                                 	at android.app.Activity.performCreate(Activity.java:6785)
                                                                                                                 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1147)
                                                                                                                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2621)
                                                                                                                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2729)
                                                                                                                 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                                                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480)
                                                                                                                 	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                                 	at android.os.Looper.loop(Looper.java:154)
                                                                                                                 	at android.app.ActivityThread.main(ActivityThread.java:6138)
                                                                                                                 	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                                 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
                                                                                                                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
16:20:52.142 StrictMode              air.br.com.megajogos.mobile         air.br.com.megajogos.mobile          D  StrictMode policy violation; ~duration=829 ms: android.os.StrictMode$StrictModeDiskWriteViolation: policy=65567 violation=1
                                                                                                                 	at android.os.StrictMode$AndroidBlockGuardPolicy.onWriteToDisk(StrictMode.java:1253)
                                                                                                                 	at java.io.UnixFileSystem.delete(UnixFileSystem.java:293)
                                                                                                                 	at java.io.File.delete(File.java:972)
                                                                                                                 	at com.adobe.air.ApplicationFileManager.deleteDir(ApplicationFileManager.java:472)
                                                                                                                 	at com.adobe.air.ApplicationFileManager.RefreshAppCache(ApplicationFileManager.java:456)
                                                                                                                 	at com.adobe.air.ApplicationFileManager.processAndroidDataPath(ApplicationFileManager.java:499)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.initializeAndroidAppVars(AndroidActivityWrapper.java:932)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.parseArgs(AndroidActivityWrapper.java:976)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.onCreate(AndroidActivityWrapper.java:998)
                                                                                                                 	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                                 	at air.com.adobe.appentry.AppEntry.InvokeMethod(AppEntry.java:422)
                                                                                                                 	at air.com.adobe.appentry.AppEntry.InvokeWrapperOnCreate(AppEntry.java:403)
                                                                                                                 	at air.com.adobe.appentry.AppEntry.onCreate(AppEntry.java:285)
                                                                                                                 	at air.br.com.megajogos.mobile.AIRAppEntry.onCreate(AIRAppEntry.java:25)
                                                                                                                 	at android.app.Activity.performCreate(Activity.java:6785)
                                                                                                                 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1147)
                                                                                                                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2621)
                                                                                                                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2729)
                                                                                                                 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                                                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480)
                                                                                                                 	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                                 	at android.os.Looper.loop(Looper.java:154)
                                                                                                                 	at android.app.ActivityThread.main(ActivityThread.java:6138)
                                                                                                                 	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                                 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
                                                                                                                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
16:20:52.142 StrictMode              air.br.com.megajogos.mobile         air.br.com.megajogos.mobile          D  StrictMode policy violation; ~duration=829 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65567 violation=2
                                                                                                                 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
                                                                                                                 	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:249)
                                                                                                                 	at java.io.File.exists(File.java:780)
                                                                                                                 	at java.io.File.mkdirs(File.java:1297)
                                                                                                                 	at com.adobe.air.ApplicationFileManager.processAndroidDataPath(ApplicationFileManager.java:517)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.initializeAndroidAppVars(AndroidActivityWrapper.java:932)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.parseArgs(AndroidActivityWrapper.java:976)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.onCreate(AndroidActivityWrapper.java:998)
                                                                                                                 	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                                 	at air.com.adobe.appentry.AppEntry.InvokeMethod(AppEntry.java:422)
                                                                                                                 	at air.com.adobe.appentry.AppEntry.InvokeWrapperOnCreate(AppEntry.java:403)
                                                                                                                 	at air.com.adobe.appentry.AppEntry.onCreate(AppEntry.java:285)
                                                                                                                 	at air.br.com.megajogos.mobile.AIRAppEntry.onCreate(AIRAppEntry.java:25)
                                                                                                                 	at android.app.Activity.performCreate(Activity.java:6785)
                                                                                                                 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1147)
                                                                                                                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2621)
                                                                                                                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2729)
                                                                                                                 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                                                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480)
                                                                                                                 	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                                 	at android.os.Looper.loop(Looper.java:154)
                                                                                                                 	at android.app.ActivityThread.main(ActivityThread.java:6138)
                                                                                                                 	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                                 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
                                                                                                                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
16:20:52.142 StrictMode              air.br.com.megajogos.mobile         air.br.com.megajogos.mobile          D  StrictMode policy violation; ~duration=829 ms: android.os.StrictMode$StrictModeDiskWriteViolation: policy=65567 violation=1
                                                                                                                 	at android.os.StrictMode$AndroidBlockGuardPolicy.onWriteToDisk(StrictMode.java:1253)
                                                                                                                 	at java.io.UnixFileSystem.createDirectory(UnixFileSystem.java:307)
                                                                                                                 	at java.io.File.mkdir(File.java:1273)
                                                                                                                 	at java.io.File.mkdirs(File.java:1300)
                                                                                                                 	at com.adobe.air.ApplicationFileManager.processAndroidDataPath(ApplicationFileManager.java:517)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.initializeAndroidAppVars(AndroidActivityWrapper.java:932)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.parseArgs(AndroidActivityWrapper.java:976)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.onCreate(AndroidActivityWrapper.java:998)
                                                                                                                 	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                                 	at air.com.adobe.appentry.AppEntry.InvokeMethod(AppEntry.java:422)
                                                                                                                 	at air.com.adobe.appentry.AppEntry.InvokeWrapperOnCreate(AppEntry.java:403)
                                                                                                                 	at air.com.adobe.appentry.AppEntry.onCreate(AppEntry.java:285)
                                                                                                                 	at air.br.com.megajogos.mobile.AIRAppEntry.onCreate(AIRAppEntry.java:25)
                                                                                                                 	at android.app.Activity.performCreate(Activity.java:6785)
                                                                                                                 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1147)
                                                                                                                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2621)
                                                                                                                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2729)
                                                                                                                 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                                                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480)
                                                                                                                 	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                                 	at android.os.Looper.loop(Looper.java:154)
                                                                                                                 	at android.app.ActivityThread.main(ActivityThread.java:6138)
                                                                                                                 	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                                 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
                                                                                                                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
16:20:52.142 StrictMode              air.br.com.megajogos.mobile         air.br.com.megajogos.mobile          D  StrictMode policy violation; ~duration=829 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65567 violation=2
                                                                                                                 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
                                                                                                                 	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:249)
                                                                                                                 	at java.io.File.exists(File.java:780)
                                                                                                                 	at java.io.File.mkdirs(File.java:1297)
                                                                                                                 	at java.io.File.mkdirs(File.java:1311)
                                                                                                                 	at com.adobe.air.ApplicationFileManager.processAndroidDataPath(ApplicationFileManager.java:517)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.initializeAndroidAppVars(AndroidActivityWrapper.java:932)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.parseArgs(AndroidActivityWrapper.java:976)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.onCreate(AndroidActivityWrapper.java:998)
                                                                                                                 	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                                 	at air.com.adobe.appentry.AppEntry.InvokeMethod(AppEntry.java:422)
                                                                                                                 	at air.com.adobe.appentry.AppEntry.InvokeWrapperOnCreate(AppEntry.java:403)
                                                                                                                 	at air.com.adobe.appentry.AppEntry.onCreate(AppEntry.java:285)
                                                                                                                 	at air.br.com.megajogos.mobile.AIRAppEntry.onCreate(AIRAppEntry.java:25)
                                                                                                                 	at android.app.Activity.performCreate(Activity.java:6785)
                                                                                                                 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1147)
                                                                                                                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2621)
                                                                                                                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2729)
                                                                                                                 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                                                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480)
                                                                                                                 	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                                 	at android.os.Looper.loop(Looper.java:154)
                                                                                                                 	at android.app.ActivityThread.main(ActivityThread.java:6138)
                                                                                                                 	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                                 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
                                                                                                                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
16:20:52.142 StrictMode              air.br.com.megajogos.mobile         air.br.com.megajogos.mobile          D  StrictMode policy violation; ~duration=829 ms: android.os.StrictMode$StrictModeDiskWriteViolation: policy=65567 violation=1
                                                                                                                 	at android.os.StrictMode$AndroidBlockGuardPolicy.onWriteToDisk(StrictMode.java:1253)
                                                                                                                 	at java.io.UnixFileSystem.createDirectory(UnixFileSystem.java:307)
                                                                                                                 	at java.io.File.mkdir(File.java:1273)
                                                                                                                 	at java.io.File.mkdirs(File.java:1300)
                                                                                                                 	at java.io.File.mkdirs(File.java:1311)
                                                                                                                 	at com.adobe.air.ApplicationFileManager.processAndroidDataPath(ApplicationFileManager.java:517)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.initializeAndroidAppVars(AndroidActivityWrapper.java:932)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.parseArgs(AndroidActivityWrapper.java:976)
                                                                                                                 	at com.adobe.air.AndroidActivityWrapper.onCreate(AndroidActivityWrapper.java:998)
                                                                                                                 	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                                 	at air.com.adobe.appentry.AppEntry.InvokeMethod(AppEntry.java:422)
                                                                                                                 	at air.com.adobe.appentry.AppEntry.InvokeWrapperOnCreate(AppEntry.java:403)
                                                                                                                 	at air.com.adobe.appentry.AppEntry.onCreate(AppEntry.java:285)
                                                                                                                 	at air.br.com.megajogos.mobile.AIRAppEntry.onCreate(AIRAppEntry.java:25)
                                                                                                                 	at android.app.Activity.performCreate(Activity.java:6785)
                                                                                                                 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1147)
                                                                                                                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2621)
                                                                                                                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2729)
                                                                                                                 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                                                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480)
                                                                                                                 	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                                 	at android.os.Looper.loop(Looper.java:154)
                                                                                                                 	at android.app.ActivityThread.main(ActivityThread.java:6138)
                                                                                                                 	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                                 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
                                                                                                                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
16:20:52.142 FIAM.Headless           air.br.com.megajogos.mobile         air.br.com.megajogos.mobile          I  Starting InAppMessaging runtime with Installation ID d1PszFXDTwedzuSHpHSpEP
16:20:52.225 StrictMode              air.br.com.megajogos.mobile         air.br.com.megajogos.mobile          D  StrictMode policy violation; ~duration=82 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65567 violation=2
                                                                                                                 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
                                                                                                                 	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:249)
                                                                                                                 	at java.io.File.exists(File.java:780)
                                                                                                                 	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:512)
                                                                                                                 	at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:468)
                                                                                                                 	at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:627)
                                                                                                                 	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:345)
                                                                                                                 	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:164)
                                                                                                                 	at com.facebook.internal.FeatureManager.isEnabled(FeatureManager.kt:45)
                                                                                                                 	at com.facebook.internal.FeatureManager$checkFeature$1.onCompleted(FeatureManager.kt:30)
                                                                                                                 	at com.facebook.internal.FetchedAppGateKeepersManager.pollCallbacks$lambda-1(FetchedAppGateKeepersManager.kt:121)
                                                                                                                 	at com.facebook.internal.FetchedAppGateKeepersManager.$r8$lambda$88hCiLqd34I9PIXLsFQQ5bjLs-Q(FetchedAppGateKeepersManager.kt)
                                                                                                                 	at com.facebook.internal.FetchedAppGateKeepersManager$$ExternalSyntheticLambda1.run(D8$$SyntheticClass)
                                                                                                                 	at android.os.Handler.handleCallback(Handler.java:751)
                                                                                                                 	at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                                 	at android.os.Looper.loop(Looper.java:154)
                                                                                                                 	at android.app.ActivityThread.main(ActivityThread.java:6138)
                                                                                                                 	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                                 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
                                                                                                                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
16:20:52.225 StrictMode              air.br.com.megajogos.mobile         air.br.com.megajogos.mobile          D  StrictMode policy violation; ~duration=0 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65567 violation=2
                                                                                                                 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
                                                                                                                 	at android.app.SharedPreferencesImpl.awaitLoadedLocked(SharedPreferencesImpl.java:226)
                                                                                                                 	at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:250)
                                                                                                                 	at com.facebook.internal.FeatureManager.isEnabled(FeatureManager.kt:46)
                                                                                                                 	at com.facebook.internal.FeatureManager$checkFeature$1.onCompleted(FeatureManager.kt:30)
                                                                                                                 	at com.facebook.internal.FetchedAppGateKeepersManager.pollCallbacks$lambda-1(FetchedAppGateKeepersManager.kt:121)
                                                                                                                 	at com.facebook.internal.FetchedAppGateKeepersManager.$r8$lambda$88hCiLqd34I9PIXLsFQQ5bjLs-Q(FetchedAppGateKeepersManager.kt)
                                                                                                                 	at com.facebook.internal.FetchedAppGateKeepersManager$$ExternalSyntheticLambda1.run(D8$$SyntheticClass)
                                                                                                                 	at android.os.Handler.handleCallback(Handler.java:751)
                                                                                                                 	at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                                 	at android.os.Looper.loop(Looper.java:154)
                                                                                                                 	at android.app.ActivityThread.main(ActivityThread.java:6138)
                                                                                                                 	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                                 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
                                                                                                                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)```

Is there anything I can do to improve this step?
