### ISSUE TITLE
Andoid abb can't package.

### ISSUE THREAD

**Issue by TanDing90** [airsdk/Adobe-Runtime-Support#355]
Andoid abb can't package

AIR SDK: 33.1.1.98.

bogon:~ tanding$ /Users/tanding/Documents/IronForce/Trunk/IronForces/build/build_anroid-chillingo-ironforce-AJA.sh ; exit;
WARNING: ANE [com.distriqt.androidsupport.CustomTabs] has no support for Android-x64
WARNING: ANE [com.freshplanet.AirGooglePlayGamesService] has no support for Android-x64
WARNING: ANE [com.distriqt.androidsupport.V4] has no support for Android-x64
WARNING: ANE [com.distriqt.androidsupport.CardViewV7] has no support for Android-x64
WARNING: ANE [com.freshplanet.AirInAppPurchase] has no support for Android-x64
WARNING: ANE [com.distriqt.androidsupport.AppCompatV7] has no support for Android-x64
WARNING: ANE [com.freshplanet.ane.AirFacebook] has no support for Android-x64
WARNING: ANE [com.distriqt.androidsupport.Design] has no support for Android-x64
WARNING: ANE [com.freshplanet.AirFlurry] has no support for Android-x64
WARNING: ANE [com.chillingo.TermsANE] has no support for Android-x64
WARNING: ANE [com.coolfishgames.ane.tools] has no support for Android-x64
WARNING: ANE [com.distriqt.androidsupport.RecyclerViewV7] has no support for Android-x64
WARNING: ANE [com.kochava.extensions.KochavaTracker] has no support for Android-x64
WARNING: ANE [com.freshplanet.ane.AirPushNotification] has no support for Android-x64
Bundle tool failed:[BT:0.10.3] Error: An error occurred while trying to read the file '"/Users/tanding/Documents/IronForce/Trunk/IronForces/build/android_chillingo_aja/aab2079747305951815989.json"'.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: An error occurred while trying to read the file '"/Users/tanding/Documents/IronForce/Trunk/IronForces/build/android_chillingo_aja/aab2079747305951815989.json"'.
       at com.android.tools.build.bundletool.model.exceptions.CommandExecutionException$Builder.build(CommandExecutionException.java:81)
       at com.android.tools.build.bundletool.commands.BuildBundleCommand.parseBundleConfigJson(BuildBundleCommand.java:329)
       at com.android.tools.build.bundletool.commands.BuildBundleCommand.lambda$fromFlags$0(BuildBundleCommand.java:175)
       at java.util.Optional.ifPresent(Optional.java:159)
       at com.android.tools.build.bundletool.commands.BuildBundleCommand.fromFlags(BuildBundleCommand.java:175)
       at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:70)
       at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)
Caused by: java.nio.file.NoSuchFileException: "/Users/tanding/Documents/IronForce/Trunk/IronForces/build/android_chillingo_aja/aab2079747305951815989.json"
       at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
       at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
       at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
       at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
       at java.nio.file.Files.newByteChannel(Files.java:361)
       at java.nio.file.Files.newByteChannel(Files.java:407)
       at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
       at java.nio.file.Files.newInputStream(Files.java:152)
       at java.nio.file.Files.newBufferedReader(Files.java:2784)
       at com.android.tools.build.bundletool.model.utils.files.BufferedIo.reader(BufferedIo.java:49)
       at com.android.tools.build.bundletool.commands.BuildBundleCommand.parseBundleConfigJson(BuildBundleCommand.java:317)
       ... 5 more

**Comment by ajwfrost** [comment]
Hi

You'll need to update your ANEs to get the versions that support 64-bit Android platforms. Other than that, the issue with the missing JSON file is one that we've seen a few times now.

Support for Android App Bundle is very much beta level because we found some issues with merging of resource IDs from ANEs that we couldn't work round. We have been in touch with the Play Store team and are going to try to revisit this soon though..

thanks

   Andrew

**Comment by TanDing90** [comment]
The missing JSON file bug, is it fixed now?

**Comment by ajwfrost** [comment]
Yes, we changed how we created bundles so instead of generating the json and creating a bundle from a zip of compiled code, we're just generating a gradle project structure and getting the Android plug-in from Gradle to do the compilation and packaging...

Actually this whole "aab can't package" issue is a bit out-dated now, so I'll close this: if you can use the SDK 33.1.1.533 (or preferably wait until next week for an update) and still find issues, please open a new issue.

thanks
