### ISSUE TITLE
[Android] AIR application crashes on start when it installed as system app

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#356]
## Problem Description
AIR application crashes on start when it installed as Android system app.
There is no way to use AIR right now for OEM devices, custom firmwares, preinstalled apps where only one main way of distribution - as a system application.
May be AIR application on start trying to find main swf to launch (execute it) but OS prevent such execution from system directory (which read-only) but swf is asset in terms of apk structure. May be something else.

It has been tested with latest AIR 33.1.1.98 with different Android devices with different AIR applications (even "empty" AIR app without any code) with different OS versions.
Same problem in all cases.

Using `sharedUserId="android.uid.system"` in Android application manifest doesn't help. 
Trying to repack apk (with resign) with adding main swf to apk root doesn't help.
The same AIR applications works fine if installed as user apps (classic way).
Other (non-AIR) applications works fine if installed as system apps with the same devices (firmwares).

Related issue (not the same): https://github.com/Gamua/Adobe-Runtime-Support/issues/278

## Steps to Reproduce
Install any AIR application as a system Android app (by custom ROM/firmware, signing it by proper certificate or using root) and launch it.

**Actual Result:**
Application crash with one of the following ADB crash logs.
"Empty" AIR app:
```
2020-06-15 14:28:38.579 1797-1890/? D/audio_hal: out(0xaff32000) do_out_standby
2020-06-15 14:28:38.579 1797-1890/? D/audio_hal: pcm_close card:device(hw:0:0)
2020-06-15 14:28:39.120 2541-2541/com.test.launcher V/ViewRootImpl[Launcher]: Sending input event to IME: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_DPAD_CENTER, scanCode=28, metaState=0, flags=0x8, repeatCount=0, eventTime=52183, downTime=52183, deviceId=3, source=0x701 }
    
    --------- beginning of system
2020-06-15 14:28:39.122 2099-2161/system_process I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.air.app/.AppEntry} from uid 1000 on display 0
2020-06-15 14:28:39.138 2541-2541/com.test.launcher W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:906 android.content.ContextWrapper.sendBroadcast:421 android.app.ActivityThread.performPauseActivityIfNeeded:3744 android.app.ActivityThread.performPauseActivity:3698 android.app.ActivityThread.performPauseActivity:3672 
2020-06-15 14:28:39.156 2777-2777/? E/libprocessgroup: failed to make and chown /acct/uid_10034: Read-only file system
2020-06-15 14:28:39.156 2777-2777/? W/Zygote: createProcessGroup failed, kernel missing CONFIG_CGROUP_CPUACCT?
2020-06-15 14:28:39.157 2099-2110/system_process I/ActivityManager: Start proc 2777:com.air.app/u0a34 for activity com.air.app/.AppEntry
2020-06-15 14:28:39.160 2541-2541/com.test.launcher V/ViewRootImpl[Launcher]: Sending input event to IME: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=28, metaState=0, flags=0x28, repeatCount=0, eventTime=52199, downTime=52183, deviceId=3, source=0x701 }
2020-06-15 14:28:39.161 2541-2541/com.test.launcher W/ViewRootImpl[Launcher]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=28, metaState=0, flags=0x28, repeatCount=0, eventTime=52199, downTime=52183, deviceId=3, source=0x701 }
2020-06-15 14:28:39.161 2541-2541/com.test.launcher W/ViewRootImpl[Launcher]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=28, metaState=0, flags=0x28, repeatCount=0, eventTime=52199, downTime=52183, deviceId=3, source=0x701 }
2020-06-15 14:28:39.161 2541-2541/com.test.launcher W/ViewRootImpl[Launcher]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=28, metaState=0, flags=0x28, repeatCount=0, eventTime=52199, downTime=52183, deviceId=3, source=0x701 }
2020-06-15 14:28:39.161 2541-2541/com.test.launcher W/ViewRootImpl[Launcher]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=28, metaState=0, flags=0x28, repeatCount=0, eventTime=52199, downTime=52183, deviceId=3, source=0x701 }
2020-06-15 14:28:39.161 2541-2541/com.test.launcher W/ViewRootImpl[Launcher]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=28, metaState=0, flags=0x28, repeatCount=0, eventTime=52199, downTime=52183, deviceId=3, source=0x701 }
2020-06-15 14:28:39.161 2541-2541/com.test.launcher W/ViewRootImpl[Launcher]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=28, metaState=0, flags=0x28, repeatCount=0, eventTime=52199, downTime=52183, deviceId=3, source=0x701 }
2020-06-15 14:28:39.196 2777-2784/? I/art: Debugger is no longer active
2020-06-15 14:28:39.196 2777-2784/? I/art: Starting a blocking GC Instrumentation
2020-06-15 14:28:39.240 2777-2777/? W/System: ClassLoader referenced unknown path: /system/priv-app/TestApp/lib/arm
2020-06-15 14:28:39.286 2777-2777/? I/StartupTime1: :1592566119286
2020-06-15 14:28:39.287 2777-2777/? I/AIR VERSION: :33.1.1.98
2020-06-15 14:28:39.287 2777-2777/? I/DEVICE ARCH: :armeabi-v7a
2020-06-15 14:28:39.331 2777-2777/? W/System: ClassLoader referenced unknown path: 
2020-06-15 14:28:39.331 2777-2777/? W/System: ClassLoader referenced unknown path: /system/priv-app/TestApp/lib/arm
2020-06-15 14:28:39.403 2777-2777/? W/OrientationEventListener: Cannot detect sensors. Not enabled
2020-06-15 14:28:39.455 2777-2777/? E/art: No implementation found for void com.adobe.air.AIRWindowSurfaceView.nativeSurfaceCreated() (tried Java_com_adobe_air_AIRWindowSurfaceView_nativeSurfaceCreated and Java_com_adobe_air_AIRWindowSurfaceView_nativeSurfaceCreated__)
2020-06-15 14:28:39.460 2777-2777/? D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2020-06-15 14:28:39.461 2777-2777/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.air.app, PID: 2777
    java.lang.UnsatisfiedLinkError: No implementation found for void com.adobe.air.AIRWindowSurfaceView.nativeSurfaceCreated() (tried Java_com_adobe_air_AIRWindowSurfaceView_nativeSurfaceCreated and Java_com_adobe_air_AIRWindowSurfaceView_nativeSurfaceCreated__)
        at com.adobe.air.AIRWindowSurfaceView.nativeSurfaceCreated(Native Method)
        at com.adobe.air.AIRWindowSurfaceView.surfaceCreated(AIRWindowSurfaceView.java:730)
        at android.view.SurfaceView.updateWindow(SurfaceView.java:608)
        at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:160)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2201)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
        at android.view.Choreographer.doCallbacks(Choreographer.java:683)
        at android.view.Choreographer.doFrame(Choreographer.java:619)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
        at android.os.Handler.handleCallback(Handler.java:750)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6097)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1041)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:931)
2020-06-15 14:28:39.463 2099-2161/system_process W/ActivityManager:   Force finishing activity com.air.app/.AppEntry
2020-06-15 14:28:39.539 2099-2793/system_process I/OpenGLRenderer: Initialized EGL, version 1.4
2020-06-15 14:28:39.539 2099-2793/system_process D/OpenGLRenderer: Swap behavior 1
2020-06-15 14:28:39.603 1786-1786/? I/hwc: HISI_HWC gpu compose for layer=0
2020-06-15 14:28:39.620 1786-1786/? I/hwc: HISI_HWC gpu compose for layer=0
2020-06-15 14:28:39.969 2099-2113/system_process W/ActivityManager: Activity pause timeout for ActivityRecord{39744b2 u0 com.air.app/.AppEntry t11 f}
2020-06-15 14:28:39.971 2099-2113/system_process I/WindowManager: Failed to capture screenshot of Token{202ac03 ActivityRecord{39744b2 u0 com.air.app/.AppEntry t11 f}} appWin=Window{d9d20d u0 SurfaceView - com.air.app/com.air.app.AppEntry} drawState=3
2020-06-15 14:28:40.055 2099-2111/system_process D/EthernetServiceImpl: getDatabaseInterfaceName() InterfaceName: eth0
2020-06-15 14:28:40.055 2099-2684/system_process I/NetUtils: Interface eth0 LinkDown!
2020-06-15 14:28:40.055 2099-2684/system_process D/EthernetServiceImpl: getNetLinkStatus(eth0): 0
2020-06-15 14:28:40.056 2099-2684/system_process I/NetUtils: Interface eth0 LinkDown!
2020-06-15 14:28:40.059 2541-2541/com.test.launcher W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:906 android.content.ContextWrapper.sendBroadcast:421 android.app.ActivityThread.performResumeActivity:3414 android.app.ActivityThread.handleResumeActivity:3450 android.app.ActivityThread$H.handleMessage:1510 
2020-06-15 14:28:40.479 2099-2121/system_process I/WindowManager: Destroying surface Surface(name=Starting com.air.app) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.AppWindowToken.destroySurfaces:365 com.android.server.wm.WindowStateAnimator.finishExit:565 com.android.server.wm.AppWindowAnimator.stepAnimationLocked:427 com.android.server.wm.WindowAnimator.updateAppWindowsLocked:176 
```

More complex AIR application with native extensions:
```
2020-06-15 14:10:34.012 1796-1887/? D/audio_hal: out(0xb4232000) do_out_standby
2020-06-15 14:10:34.012 1796-1887/? D/audio_hal: pcm_close card:device(hw:0:0)
2020-06-15 14:10:34.582 2559-2559/system:ui V/ViewRootImpl[ResolverActivity]: Sending input event to IME: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_DPAD_CENTER, scanCode=28, metaState=0, flags=0x8, repeatCount=0, eventTime=50422, downTime=50422, deviceId=3, source=0x701 }
2020-06-15 14:10:34.790 2559-2559/system:ui V/ViewRootImpl[ResolverActivity]: Sending input event to IME: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=28, metaState=0, flags=0x8, repeatCount=0, eventTime=50631, downTime=50422, deviceId=3, source=0x701 }
2020-06-15 14:10:34.792 1796-1887/? D/audio_hal: out_set_parameters kvpairs = routing=1024
2020-06-15 14:10:34.792 1796-1887/? D/audio_hal: func:out_set_parameters, 1024 ---> HISI_AO_CARD_ID(0, 0) 
2020-06-15 14:10:34.793 1796-1887/? D/audio_hal: pcm_open card:device(hw:0:0) flags(0x8) out(0xb4232000)
    
    --------- beginning of system
2020-06-15 14:10:34.793 2099-2557/system_process I/PackageManager: Setting last chosen activity com.air.test.app/.AppEntry for user 0:
2020-06-15 14:10:34.793 2099-2557/system_process I/PackageManager:   Action: "android.intent.action.MAIN"
2020-06-15 14:10:34.793 2099-2557/system_process I/PackageManager:   Category: "android.intent.category.HOME"
2020-06-15 14:10:34.793 2099-2557/system_process I/PackageManager:   Category: "android.intent.category.DEFAULT"
2020-06-15 14:10:34.793 2099-2557/system_process I/PackageManager:   AutoVerify=false
2020-06-15 14:10:34.794 2099-2110/system_process I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x13000100 cmp=com.air.test.app/.AppEntry} from uid 0 on display 0
2020-06-15 14:10:34.811 2559-2559/system:ui W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:906 android.content.ContextWrapper.sendBroadcast:421 android.app.ActivityThread.performPauseActivityIfNeeded:3744 android.app.ActivityThread.performPauseActivity:3698 android.app.ActivityThread.performPauseActivity:3672 
2020-06-15 14:10:34.825 1785-1838/? D/PermissionCache: checking android.permission.READ_FRAME_BUFFER for uid=1000 => granted (142 us)
2020-06-15 14:10:34.866 1785-1785/? D/SurfaceFlinger: shader cache generated - 24 shaders in 31.221085 ms
2020-06-15 14:10:34.979 2099-2112/system_process W/art: Long monitor contention with owner ActivityManager (2113) at void com.android.server.am.BroadcastQueue.processNextBroadcast(boolean)(BroadcastQueue.java:759) waiters=2 in void com.android.server.am.ActivityManagerService$3.handleMessage(android.os.Message) for 166ms
2020-06-15 14:10:34.979 2099-2238/system_process W/art: Long monitor contention with owner Binder:2099_2 (2111) at void com.android.server.am.ActivityManagerService.activityPaused(android.os.IBinder)(ActivityManagerService.java:6959) waiters=2 in void com.android.server.am.ActivityManagerService.updateConfiguration(android.content.res.Configuration) for 165ms
2020-06-15 14:10:34.990 1796-1887/? D/audio_hal: out_get_latency: out(0xb4232000) latency=20
2020-06-15 14:10:34.996 2603-2603/com.air.test.app I/StartupTime1: :1592565034996
2020-06-15 14:10:34.997 2603-2603/com.air.test.app I/AIR VERSION: :33.1.1.98
2020-06-15 14:10:34.998 2603-2603/com.air.test.app I/DEVICE ARCH: :armeabi-v7a
2020-06-15 14:10:35.033 1796-1887/? D/audio_hal: out_get_latency: out(0xb4232000) latency=20
2020-06-15 14:10:35.083 2603-2603/com.air.test.app W/System: ClassLoader referenced unknown path: 
2020-06-15 14:10:35.083 2603-2603/com.air.test.app W/System: ClassLoader referenced unknown path: /system/priv-app/TestApp/lib/arm
2020-06-15 14:10:35.138 2603-2603/com.air.test.app W/OrientationEventListener: Cannot detect sensors. Not enabled
2020-06-15 14:10:35.220 2603-2799/com.air.test.app I/OpenGLRenderer: Initialized EGL, version 1.4
2020-06-15 14:10:35.221 2603-2799/com.air.test.app D/OpenGLRenderer: Swap behavior 1
2020-06-15 14:10:35.251 2603-2603/com.air.test.app V/VideoSurfaceView: surfaceCreated
2020-06-15 14:10:35.251 2603-2603/com.air.test.app V/VideoSurfaceView: surfaceChanged format=842094169, width=1920, height=1080
2020-06-15 14:10:35.295 2603-2603/com.air.test.app I/AIR RUNTIME: Version 33,1,1,98 - platform Android-ARM
2020-06-15 14:10:35.308 2603-2603/com.air.test.app W/test.app: type=1400 audit(0.0:6): avc: denied { execmod } for path="/system/priv-app/TestApp/TestApp.apk" dev="dm-0" ino=1958 scontext=u:r:priv_app:s0:c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0
2020-06-15 14:10:35.357 1797-2150/? I/CameraModule: [CAMERA_HAL] camera_get_number_of_cameras = 0
    
    --------- beginning of crash
2020-06-15 14:10:35.456 2603-2603/com.air.test.app A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0x943bc000 in tid 2603 (test.app)
2020-06-15 14:10:35.529 2813-2813/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2020-06-15 14:10:35.529 2813-2813/? A/DEBUG: Build fingerprint: 'HiSTBAndroidV6/STB122A:1.0.681-gce193d9d6b/NRD90M/suppor06171324:userdebug/dev-keys'
2020-06-15 14:10:35.529 2813-2813/? A/DEBUG: Revision: '1.0'
2020-06-15 14:10:35.529 2813-2813/? A/DEBUG: ABI: 'arm'
2020-06-15 14:10:35.529 2813-2813/? A/DEBUG: pid: 2603, tid: 2603, name: test.app  >>> com.air.test.app <<<
2020-06-15 14:10:35.529 2813-2813/? A/DEBUG: signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x943bc000
2020-06-15 14:10:35.529 2813-2813/? A/DEBUG:     r0 943d1b30  r1 00000000  r2 00000014  r3 93632854
2020-06-15 14:10:35.529 2813-2813/? A/DEBUG:     r4 93632810  r5 943d1b30  r6 00000000  r7 00000001
2020-06-15 14:10:35.529 2813-2813/? A/DEBUG:     r8 93632810  r9 00000000  sl 924aa3c8  fp beaaf820
2020-06-15 14:10:35.529 2813-2813/? A/DEBUG:     ip 00000000  sp beaaf810  lr 93839750  pc 943bc000  cpsr 600d0010
2020-06-15 14:10:35.546 2813-2813/? A/DEBUG: backtrace:
2020-06-15 14:10:35.546 2813-2813/? A/DEBUG:     #00 pc 00004000  /system/priv-app/TestApp/TestApp.apk (offset 0x1427000)
2020-06-15 14:10:35.546 2813-2813/? A/DEBUG:     #01 pc 0016d74c  /system/priv-app/TestApp/TestApp.apk (offset 0x73c000)
2020-06-15 14:10:35.546 2813-2813/? A/DEBUG:     #02 pc 002213b7  /system/priv-app/TestApp/TestApp.apk (offset 0x73c000)
2020-06-15 14:10:35.546 2813-2813/? A/DEBUG:     #03 pc 001e7e6f  /system/priv-app/TestApp/TestApp.apk (offset 0x73c000)
2020-06-15 14:10:35.546 2813-2813/? A/DEBUG:     #04 pc 002209f7  /system/priv-app/TestApp/TestApp.apk (offset 0x73c000)
2020-06-15 14:10:35.546 2813-2813/? A/DEBUG:     #05 pc 0026a669  /system/priv-app/TestApp/TestApp.apk (offset 0x73c000)
2020-06-15 14:10:35.546 2813-2813/? A/DEBUG:     #06 pc 002635c9  /system/priv-app/TestApp/TestApp.apk (offset 0x73c000)
2020-06-15 14:10:35.546 2813-2813/? A/DEBUG:     #07 pc 000de3ed  /system/priv-app/TestApp/TestApp.apk (offset 0x73c000)
2020-06-15 14:10:35.546 2813-2813/? A/DEBUG:     #08 pc 000e10df  /system/priv-app/TestApp/TestApp.apk (offset 0x73c000)
2020-06-15 14:10:35.547 2813-2813/? A/DEBUG:     #09 pc 000f7875  /system/priv-app/TestApp/TestApp.apk (offset 0x73c000)
2020-06-15 14:10:35.547 2813-2813/? A/DEBUG:     #10 pc 0044da0d  /system/priv-app/TestApp/TestApp.apk (offset 0x73c000)
2020-06-15 14:10:35.547 2813-2813/? A/DEBUG:     #11 pc 004453f5  /system/priv-app/TestApp/TestApp.apk (offset 0x73c000)
2020-06-15 14:10:35.547 2813-2813/? A/DEBUG:     #12 pc 000d8c83  /system/priv-app/TestApp/TestApp.apk (offset 0x73c000)
2020-06-15 14:10:35.547 2813-2813/? A/DEBUG:     #13 pc 000d9125  /system/priv-app/TestApp/TestApp.apk (offset 0x73c000)
2020-06-15 14:10:35.547 2813-2813/? A/DEBUG:     #14 pc 000d98f7  /system/priv-app/TestApp/TestApp.apk (offset 0x73c000)
2020-06-15 14:10:35.547 2813-2813/? A/DEBUG:     #15 pc 000d46cd  /system/priv-app/TestApp/TestApp.apk (offset 0x73c000)
2020-06-15 14:10:35.547 2813-2813/? A/DEBUG:     #16 pc 002b0be7  /data/dalvik-cache/arm/system@priv-app@TestApp@TestApp.apk@classes.dex (offset 0x29b000)
2020-06-15 14:10:36.226 2099-2818/system_process W/ActivityManager:   Force finishing activity com.air.test.app/.AppEntry
2020-06-15 14:10:36.227 2099-2118/system_process I/BootReceiver: Copying /data/tombstones/tombstone_00 to DropBox (SYSTEM_TOMBSTONE)
2020-06-15 14:10:36.245 2099-2131/system_process W/InputDispatcher: channel '5f84ad6 com.air.test.app/com.air.test.app.AppEntry (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
2020-06-15 14:10:36.245 2099-2131/system_process E/InputDispatcher: channel '5f84ad6 com.air.test.app/com.air.test.app.AppEntry (server)' ~ Channel is unrecoverably broken and will be disposed!
2020-06-15 14:10:36.246 2099-2110/system_process D/GraphicsStats: Buffer count: 2
2020-06-15 14:10:36.246 2099-2187/system_process I/WindowManager: WIN DEATH: Window{5f84ad6 u0 com.air.test.app/com.air.test.app.AppEntry}
2020-06-15 14:10:36.246 2099-2187/system_process W/InputDispatcher: Attempted to unregister already unregistered input channel '5f84ad6 com.air.test.app/com.air.test.app.AppEntry (server)'
2020-06-15 14:10:36.246 2099-2187/system_process W/WindowManager: Force-removing child win Window{4dd37ba u0 SurfaceView - com.air.test.app/com.air.test.app.AppEntry} from container Window{5f84ad6 u0 com.air.test.app/com.air.test.app.AppEntry}
2020-06-15 14:10:36.246 2099-2366/system_process I/ActivityManager: Process com.air.test.app (pid 2603) has died
2020-06-15 14:10:36.246 2099-2187/system_process I/WindowManager: Destroying surface Surface(name=SurfaceView - com.air.test.app/com.air.test.app.AppEntry) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2457 com.android.server.wm.WindowManagerService.removeWindowLocked:2436 com.android.server.wm.WindowState$DeathRecipient.binderDied:1780 android.os.BinderProxy.sendDeathNotice:688 
2020-06-15 14:10:36.247 2099-2366/system_process D/ActivityManager: cleanUpApplicationRecord -- 2603
2020-06-15 14:10:36.247 1795-1795/? I/Zygote: Process 2603 exited due to signal (11)
2020-06-15 14:10:36.247 2099-2366/system_process W/ActivityManager: Scheduling restart of crashed service com.air.test.app/com.addreality.player.boot.BootService in 1000ms
2020-06-15 14:10:36.247 2099-2116/system_process W/libprocessgroup: failed to open /acct/uid_10013/pid_2603/cgroup.procs: No such file or directory
2020-06-15 14:10:36.250 2099-2187/system_process W/WindowManager: Force-removing child win Window{dd1d5c8 u0 SurfaceView - com.air.test.app/com.air.test.app.AppEntry} from container Window{5f84ad6 u0 com.air.test.app/com.air.test.app.AppEntry}
2020-06-15 14:10:36.250 2099-2187/system_process I/WindowManager: Destroying surface Surface(name=SurfaceView - com.air.test.app/com.air.test.app.AppEntry) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2457 com.android.server.wm.WindowManagerService.removeWindowLocked:2436 com.android.server.wm.WindowState$DeathRecipient.binderDied:1780 android.os.BinderProxy.sendDeathNotice:688 
2020-06-15 14:10:36.253 2099-2187/system_process W/WindowManager: Force-removing child win Window{2171586 u0 SurfaceView - com.air.test.app/com.air.test.app.AppEntry} from container Window{5f84ad6 u0 com.air.test.app/com.air.test.app.AppEntry}
2020-06-15 14:10:36.253 2099-2187/system_process I/WindowManager: Destroying surface Surface(name=SurfaceView - com.air.test.app/com.air.test.app.AppEntry) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2457 com.android.server.wm.WindowManagerService.removeWindowLocked:2436 com.android.server.wm.WindowState$DeathRecipient.binderDied:1780 android.os.BinderProxy.sendDeathNotice:688 
2020-06-15 14:10:36.256 2099-2187/system_process I/WindowManager: Destroying surface Surface(name=com.air.test.app/com.air.test.app.AppEntry) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.WindowManagerService.removeWindowLocked:2436 com.android.server.wm.WindowState$DeathRecipient.binderDied:1780 android.os.BinderProxy.sendDeathNotice:688 <bottom of call stack> 
2020-06-15 14:10:36.259 2099-2111/system_process W/WindowManager: Failed looking up window
    java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@9094157 does not exist
        at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9106)
        at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9097)
        at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1777)
        at android.os.BinderProxy.sendDeathNotice(Binder.java:688)
2020-06-15 14:10:36.259 2099-2111/system_process I/WindowManager: WIN DEATH: null
2020-06-15 14:10:36.260 2099-2110/system_process W/WindowManager: Failed looking up window
    java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@b238444 does not exist
        at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9106)
        at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9097)
        at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1777)
        at android.os.BinderProxy.sendDeathNotice(Binder.java:688)
2020-06-15 14:10:36.260 2099-2110/system_process I/WindowManager: WIN DEATH: null
2020-06-15 14:10:36.261 2099-2557/system_process W/WindowManager: Failed looking up window
    java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@104392d does not exist
        at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9106)
        at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9097)
        at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1777)
        at android.os.BinderProxy.sendDeathNotice(Binder.java:688)
2020-06-15 14:10:36.261 2099-2557/system_process I/WindowManager: WIN DEATH: null
2020-06-15 14:10:36.262 2099-2366/system_process I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10000100 cmp=android/com.android.internal.app.ResolverActivity} from uid 0 on display 0
2020-06-15 14:10:36.270 2099-2121/system_process I/WindowManager: Destroying surface Surface(name=Starting com.air.test.app) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.WindowManagerService.removeWindowLocked:2436 com.android.server.wm.WindowManagerService.removeWindowLocked:2305 com.android.server.wm.WindowManagerService.removeWindow:2300 com.android.server.wm.Session.remove:193 
2020-06-15 14:10:36.272 2618-2618/org.videolan.vlc W/VLC/VLCApplication: onTrimMemory, level: 80
2020-06-15 14:10:36.275 1785-1785/? I/hwc: HISI_HWC gpu compose for layer=0
2020-06-15 14:10:36.291 1785-1785/? I/hwc: HISI_HWC gpu compose for layer=0
2020-06-15 14:10:36.304 2559-2559/system:ui W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:906 android.content.ContextWrapper.sendBroadcast:421 android.app.ActivityThread.performResumeActivity:3414 android.app.ActivityThread.handleResumeActivity:3450 android.app.ActivityThread.handleLaunchActivity:2713 
2020-06-15 14:10:36.308 1785-1785/? I/hwc: HISI_HWC gpu compose for layer=0
2020-06-15 14:10:36.325 1785-1785/? I/hwc: HISI_HWC gpu compose for layer=0
2020-06-15 14:10:36.332 2099-2821/system_process I/OpenGLRenderer: Initialized EGL, version 1.4
2020-06-15 14:10:36.332 2099-2821/system_process D/OpenGLRenderer: Swap behavior 1
2020-06-15 14:10:36.341 1785-1785/? I/hwc: HISI_HWC gpu compose for layer=0
2020-06-15 14:10:36.358 1785-1785/? I/hwc: HISI_HWC gpu compose for layer=0
2020-06-15 14:10:36.375 1785-1785/? I/hwc: HISI_HWC gpu compose for layer=0
2020-06-15 14:10:36.393 2099-2121/system_process I/ActivityManager: Displayed android/com.android.internal.app.ResolverActivity: +125ms
2020-06-15 14:10:36.398 1785-1785/? I/hwc: HISI_HWC gpu compose for layer=0
2020-06-15 14:10:36.869 2099-2111/system_process I/WindowManager: Destroying surface Surface(name=android/com.android.internal.app.ResolverActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.WindowManagerService.removeWindowLocked:2436 com.android.server.wm.WindowManagerService.removeWindowLocked:2305 com.android.server.wm.WindowManagerService.removeWindow:2300 com.android.server.wm.Session.remove:193 
2020-06-15 14:10:37.270 2099-2113/system_process I/ActivityManager: Start proc 2831:com.air.test.app/u0a13 for service com.air.test.app/com.addreality.player.boot.BootService
2020-06-15 14:10:37.270 2831-2831/? E/libprocessgroup: failed to make and chown /acct/uid_10013: Read-only file system
2020-06-15 14:10:37.270 2831-2831/? W/Zygote: createProcessGroup failed, kernel missing CONFIG_CGROUP_CPUACCT?
2020-06-15 14:10:37.340 2831-2831/com.air.test.app W/System: ClassLoader referenced unknown path: /system/priv-app/TestApp/lib/arm
2020-06-15 14:10:37.401 2831-2831/com.air.test.app I/com.addreality.player.boot.BootService: BootService onCreate
```

**Expected Result:**
Application shouldn't crash.

## Known Workarounds
none

**Comment by ajwfrost** [comment]
Hi - this isn't a supported use case, at least under the AIR SDK license (see restrictions in 6.1 of the license agreement, these are the same as in Adobe's version..).

We do have customers who are shipping AIR on Android as pre-installed/device UI use cases, but these are slightly different and handled on an OEM licensing model - so we can look at supporting this if we get a different license agreement in place.. I'll contact you separately.

thanks

**Comment by itlancer** [comment]
There is no such issues with latest AIR versions.
