### ISSUE TITLE
IOS - unable to compile

### ISSUE THREAD

**Issue by raresn** [airsdk/Adobe-Runtime-Support#3603]
We have updated to the latest air now, but when trying to compile on Windows, for iOS, I get this:
```
Started compiling...
Warning: MinimumOSVersion passed in app-xml is less than supported version, ignoring MinimumOSVersion value
ERROR:  ''
javax.xml.transform.TransformerException: java.lang.NullPointerException
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(Unknown Source)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(Unknown Source)
        at com.adobe.air.Plist.getXMLString(Plist.java)
        at com.adobe.air.ipa.IPAOutputStream.addInfoPlist(IPAOutputStream.java)
        at com.adobe.air.ipa.IPAOutputStream.addApplicationDescriptor(IPAOutputStream.java)
        at com.adobe.air.ApplicationPackager.addSpecialFiles(ApplicationPackager.java)
        at com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
        at com.adobe.air.ipa.IPAPackager.createPackage(IPAPackager.java)
        at com.adobe.air.ADT.parseArgsAndGo(ADT.java)
        at com.adobe.air.ADT.run(ADT.java)
        at com.adobe.air.ADT.main(ADT.java)
Caused by: java.lang.NullPointerException
        at com.sun.org.apache.xml.internal.serializer.ToUnknownStream.characters(Unknown Source)
        at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(Unknown Source)
        at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(Unknown Source)
        at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(Unknown Source)
        at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(Unknown Source)
        at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(Unknown Source)
        at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(Unknown Source)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transformIdentity(Unknown Source)
        ... 11 more
---------
java.lang.NullPointerException
        at com.sun.org.apache.xml.internal.serializer.ToUnknownStream.characters(Unknown Source)
        at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(Unknown Source)
        at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(Unknown Source)
        at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(Unknown Source)
        at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(Unknown Source)
        at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(Unknown Source)
        at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(Unknown Source)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transformIdentity(Unknown Source)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(Unknown Source)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(Unknown Source)
        at com.adobe.air.Plist.getXMLString(Plist.java)
        at com.adobe.air.ipa.IPAOutputStream.addInfoPlist(IPAOutputStream.java)
        at com.adobe.air.ipa.IPAOutputStream.addApplicationDescriptor(IPAOutputStream.java)
        at com.adobe.air.ApplicationPackager.addSpecialFiles(ApplicationPackager.java)
        at com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
        at com.adobe.air.ipa.IPAPackager.createPackage(IPAPackager.java)
        at com.adobe.air.ADT.parseArgsAndGo(ADT.java)
        at com.adobe.air.ADT.run(ADT.java)
        at com.adobe.air.ADT.main(ADT.java)
unexpected failure: PLIST generation failed due to transformer error:javax.xml.transform.TransformerException: java.lang.NullPointerException
java.io.IOException: PLIST generation failed due to transformer error:javax.xml.transform.TransformerException: java.lang.NullPointerException
        at com.adobe.air.Plist.getXMLString(Plist.java)
        at com.adobe.air.ipa.IPAOutputStream.addInfoPlist(IPAOutputStream.java)
        at com.adobe.air.ipa.IPAOutputStream.addApplicationDescriptor(IPAOutputStream.java)
        at com.adobe.air.ApplicationPackager.addSpecialFiles(ApplicationPackager.java)
        at com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
        at com.adobe.air.ipa.IPAPackager.createPackage(IPAPackager.java)
        at com.adobe.air.ADT.parseArgsAndGo(ADT.java)
        at com.adobe.air.ADT.run(ADT.java)
        at com.adobe.air.ADT.main(ADT.java)
```

@ajwfrost  Anything else that i need to update and i missed it?

**Comment by marchbold** [comment]
Can you try increasing your minimum version to at least 12 in your infoadditions:

```xml
  <iPhone>
    <InfoAdditions><![CDATA[

  <key>MinimumOSVersion</key>
  <string>12.0</string>
```

And try setting the platform sdk to point to the iOS SDK location on your machine. Easiest way to do this is via the air sdk manager:

![Screenshot 2024-12-13 at 12 43 57 PM](https://github.com/user-attachments/assets/4cd038c3-b1f0-48f5-aa92-2e040f7c5c01)

Set it to something like : `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/`

**Comment by raresn** [comment]
@marchbold thanks for this!
I managed to move on to a next error :))
WARNING: GL pipe is running in software mode (Renderer ID=0x1020400)
Error during native code-signing. Output of codesign tool is:
Warning: unable to build chain to self-signed root for signer "Apple Development: RARES-LUCIAN NEAMTIU (YPF7Q48796)"
/var/folders/qr/3nm0rgyd379g5wrgkpp_0ycm0000gn/T/1e0f12a9-2aa8-401c-888f-9e9a72921728/Payload/On Time Agenda.app: errSecInternalComponent

![image](https://github.com/user-attachments/assets/998c40d7-8e76-44c8-b7a1-5c36153f2ebd)

Any clue what i can try in this step?

**Comment by ajwfrost** [comment]
Have you downloaded the intermediate/root certificates from Apple?
https://www.apple.com/certificateauthority/

The only other time I've seen that error is if you're running code-signing from a shell command or remote terminal access, you would need to unlock the keychain manually before running the signing command:
`security unlock-keychain -p PASSWORD login.keychain`
See e.g. https://stackoverflow.com/questions/24023639/xcode-command-usr-bin-codesign-failed-with-exit-code-1-errsecinternalcomponen

**Comment by raresn** [comment]
I did not - had no idea i have to do that.
From the certificate authority, what do i need to download/install? quite a few things there.

I am running my os version is ventura 13.6 - not sure if this si relevant in this case.

**Comment by ajwfrost** [comment]
I just looked properly on there, there's a lot more versions now! You basically have to find the "issuer" of your certificate, and get that one. It would be one of the "Worldwide Developer Relations" ones on the right hand side which I can see in your screenshot. And then those would be signed by the Apple Root CA, probably the G3 one?

How did you generate the certificate though? I actually thought you had to have the issuer on your machine already (it may be under the "System" certificates list?)

Maybe it's worth right-clicking your certificate and doing "Get Info", which will show you the full details and may also give a hint as to why it's not trusted..

**Comment by raresn** [comment]
Generated the certificate on Windows si open SSL, made the p12, then copied it to the mac & install.
Writing this, it might be stupid and i need to do the whole process on a MAC?

**Comment by raresn** [comment]
installing the G3 Root, made the certificate installed go from not trusted to:
![image](https://github.com/user-attachments/assets/dc6f6417-dbed-4846-a9d6-701e1e5330a8)
After this, the compile went through without issues.
@ajwfrost thanks a lot! I had no chance to fix this without your help.

**Comment by ajwfrost** [comment]
Great, glad you got it sorted, and impressed you managed to create a suitable certificate via OpenSSL, I always use the Apple tools/website..

**Comment by raresn** [comment]
I created some bat files ages ago when i first created a p12 from apple, and keep using those. 
Gonna drop them here in case anyone needs them.
From start to finish, named the accordingly.
[AppleCertificateGenerateUsingOpenSSL.zip](https://github.com/user-attachments/files/18148623/AppleCertificateGenerateUsingOpenSSL.zip)

**Comment by raresn** [comment]
@ajwfrost also updated to the latest MacOS, and ios SDK (18.2), and i get this while compiling:
2024-12-18 15:27:27.474 java[1379:48752] +[IMKClient subclass]: chose IMKClient_Modern
2024-12-18 15:27:27.475 java[1379:48752] +[IMKInputSession subclass]: chose IMKInputSession_Modern
The compile is succesful, not sure if i should be worried about this or not.
What do you think?

**Comment by ajwfrost** [comment]
Those lines have been coming out from the new macOS version whenever we do anything AIR-related... the code doesn't actually explicitly use "IMKClient" or "IMKInputSession" so I'm not 100% sure what's causing them - but they seem harmless!

thanks
