### ISSUE TITLE
vivo phone AIR SDK 33.1.1.476 license is used crash

### ISSUE THREAD

**Issue by a9848840** [airsdk/Adobe-Runtime-Support#875]
Hi,

Some customers reported that when they upgraded vivo phone (Y12) to Android 11, the app would crash after opening the app.

After the test, I was found that if the AIR SDK license is used, the crash will occur, and no use the AIR SDK license will not be crashed.

The test also found that opening the APP 6 times on the vivo phone Android 11 (use AIR SDK license ) succeeded onlyonce.

has added <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

AirSdk : 33.1.1.476

Attach vivo crash log.

05-26 10:52:09.598 30779 30779 D NetworkSecurityConfig: Using Network Security Config from resource (name removed) debugBuild: false
05-26 10:52:09.603 30779 30779 D NetworkSecurityConfig: Using Network Security Config from resource (name removed) debugBuild: false
05-26 10:52:09.649 30779 30779 W CrashLoopRemedyLog: unable to delete remedy log, instaCrash: false
05-26 10:52:09.650 30779 30779 W CrashLoopRemedyLog: unable to delete remedy log, instaCrash: true
05-26 10:52:09.657 30779 30779 W ErrorReportingAppInit: Errorreporting: Lacrima
05-26 10:52:09.672 30779 30779 W lacrima : FbErrorReportingConfig.earlyInit
05-26 10:52:09.678 30779 30779 E RiskyStartupConfig: Failed to read risky config, some values left unset
05-26 10:52:09.678 30779 30779 E RiskyStartupConfig: java.io.FileNotFoundException: /data/user/0/com.facebook.katana/files/risky_startup_config: open failed: ENOENT (No such file or directory)
05-26 10:52:09.678 30779 30779 E RiskyStartupConfig:    at libcore.io.IoBridge.open(IoBridge.java:492)
05-26 10:52:09.678 30779 30779 E RiskyStartupConfig:    at java.io.FileInputStream.<init>(FileInputStream.java:160)
05-26 10:52:09.678 30779 30779 E RiskyStartupConfig:    at X.0bj.A00(:48)
05-26 10:52:09.678 30779 30779 E RiskyStartupConfig:    at com.facebook.katana.app.FacebookApplication.A04(:267)
05-26 10:52:09.678 30779 30779 E RiskyStartupConfig:    at X.0iX.attachBaseContext(:74)
05-26 10:52:09.678 30779 30779 E RiskyStartupConfig:    at android.app.Application.attach(Application.java:368)
05-26 10:52:09.678 30779 30779 E RiskyStartupConfig:    at android.app.Instrumentation.newApplication(Instrumentation.java:1209)
05-26 10:52:09.678 30779 30779 E RiskyStartupConfig:    at android.app.LoadedApk.makeApplication(LoadedApk.java:1256)
05-26 10:52:09.678 30779 30779 E RiskyStartupConfig:    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7156)
05-26 10:52:09.678 30779 30779 E RiskyStartupConfig:    at android.app.ActivityThread.access$1500(ActivityThread.java:265)
05-26 10:52:09.678 30779 30779 E RiskyStartupConfig:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2152)
05-26 10:52:09.678 30779 30779 E RiskyStartupConfig:    at android.os.Handler.dispatchMessage(Handler.java:106)
05-26 10:52:09.678 30779 30779 E RiskyStartupConfig:    at android.os.Looper.loop(Looper.java:239)
05-26 10:52:09.678 30779 30779 E RiskyStartupConfig:    at android.app.ActivityThread.main(ActivityThread.java:8179)
05-26 10:52:09.678 30779 30779 E RiskyStartupConfig:    at java.lang.reflect.Method.invoke(Native Method)
05-26 10:52:09.678 30779 30779 E RiskyStartupConfig:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
05-26 10:52:09.678 30779 30779 E RiskyStartupConfig:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
05-26 10:52:09.678 30779 30779 E RiskyStartupConfig: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
05-26 10:52:09.678 30779 30779 E RiskyStartupConfig:    at libcore.io.Linux.open(Native Method)
05-26 10:52:09.678 30779 30779 E RiskyStartupConfig:    at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
05-26 10:52:09.678 30779 30779 E RiskyStartupConfig:    at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
05-26 10:52:09.678 30779 30779 E RiskyStartupConfig:    at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
05-26 10:52:09.678 30779 30779 E RiskyStartupConfig:    at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8062)
05-26 10:52:09.678 30779 30779 E RiskyStartupConfig:    at libcore.io.IoBridge.open(IoBridge.java:478)
05-26 10:52:09.678 30779 30779 E RiskyStartupConfig:    ... 16 more
05-26 10:52:09.864  6053  6053 W GoogleInputMethodService: GoogleInputMethodService.onConfigurationChanged():1635 onConfigurationChanged() : NewConfig = {1.0 ?mcc?mnc [zh_TW] ldltr sw360dp w703dp h332dp 320dpi nrml long land finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1544, 720) mAppBounds=Rect(54, 0 - 1460, 720) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_90} s.36209 themeId=2 nightModeLevel = -1}
05-26 10:52:09.865  6053  6053 I NormalModeController: NormalModeController.getKeyboardBodyViewHolderPaddingBottom():114 currentPrimeKeyboardType:SOFT systemPaddingBottom:4
05-26 10:52:09.868  6053  6053 I KeyboardViewUtil: KeyboardViewUtil.getKeyboardHeightRatio():166 systemKeyboardHeightRatio:1.000000; userKeyboardHeightRatio:1.000000.
05-26 10:52:09.870  6053  6053 I AbstractOpenableExtension: AbstractOpenableExtension.maybeDestroyExistingKeyboardGroupManager():516 Destroy existing keyboard group manager in fcr

[Y12.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/6543697/Y12.txt)

**Comment by ajwfrost** [comment]
Thanks for the log, I can't see anything obvious there where there's a crash. The only odd thing I think are the lines such as:
```
05-26 10:53:41.119 32587 32599 I winner.bwmj16t: Thread[6,tid=32599,WaitingInMainSignalCatcherLoop,Thread*=0x732ee38000,peer=0x141800e8,"Signal Catcher"]: reacting to signal 3
05-26 10:53:41.119 32587 32599 I winner.bwmj16t:
05-26 10:53:41.384 32587 32599 I winner.bwmj16t: Wrote stack traces to tombstoned
```
which are happening in the AIR process, and may be an ANR. But there should be no difference really between the cases where there is a commercial license vs when there isn't.

The one thing I'm wondering is whether adding in the splash screen gives the runtime time to process any other events that had been sent following the app start-up, prior to it then kicking off the loading in of the main application SWF and all of the dependencies and ANEs that are then being created. So it might just be that too much is happening during the start-up that causes the OS to think it's just gone unresponsive.

Would it be possible to get a build of your APK done using "apk-debug" to check this out here?

thanks

**Comment by NikosLaskaridis** [comment]
We are having complaints too about our app crashing in vivo Y12 with Android 11.
