### ISSUE TITLE
MacOS problem in different SDKs

### ISSUE THREAD

**Issue by myflashlab** [airsdk/Adobe-Runtime-Support#900]
I'm not sure about windows but on a **M1 Mac**, my flex project compilation happens differently as follow:

### SDK 33.1.1.300 ###
- [x] compiles fine
- [x] captive .app packaging works (app installs and runs normally)
- [ ] file browse works normal on all mac OS versions

### SDK 33.1.1.444 ###
- [x] compiles fine
- [ ] captive .app packaging works
- [x] file browse works normal on all mac OS versions

The captive packaging happens but when running the app, nothing shows up.

### SDK 33.1.1.476 ###
- [ ] compiles fine
- [ ] captive .app packaging works
- [ ] file browse works normal on all mac OS versions (_we don't know_)

The captive packaging happens but when running the app, nothing shows up.

When compiling, I see:
```
WARNING: The Player that you are using does not support all fdb commands.
```
```
Exception in thread "DJAPI message listener" java.lang.OutOfMemoryError: Java heap space
	at flash.tools.debugger.concrete.DMessage.<init>(DMessage.java:221)
	at flash.tools.debugger.concrete.DMessageCache.alloc(DMessageCache.java:63)
	at flash.tools.debugger.concrete.DProtocol.rxMessage(DProtocol.java:435)
	at flash.tools.debugger.concrete.DProtocol.listenForMessages(DProtocol.java:267)
	at flash.tools.debugger.concrete.DProtocol.run(DProtocol.java:182)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

increasing the heap size, removes the java error but the app does not start anyway.
```xml
<option name="HEAP_SIZE_MB" value="2048" />
```

**Comment by myflashlab** [comment]
Ah, that was a `EncryptedLocalStore` problem between different SDKs!
