### ISSUE TITLE
mob swf build crashes related to font embeds in high cpu usage cases

### ISSUE THREAD

**Issue by pis0** [airsdk/Adobe-Runtime-Support#980]
i'm facing build crashes in high cpu usage cases..  
the first case was in a virtual machine (aws, trash processor), but it happens in machines with a good setup as well.. the unique pattern i figure out is the architecture.. all cases were in machines with AMD chipset, 64bits, in high cpu usage cases, as I said before...

BUT, removing all the font embeds, the build works fine..

stack:
```
Internal error: java.lang.NullPointerException: can't not add null to SWF frame
        at com.adobe.flash.swf.SWFFrame.addTag(SWFFrame.java:77)
        at com.adobe.flash.compiler.internal.units.requests.SWFTagsRequestResult.addToFrame(SWFTagsRequestResult.java:114)
        at com.adobe.flash.compiler.internal.targets.SWFTarget.addCompilationUnitsAndDependenciesToFrame(SWFTarget.java:398)
        at com.adobe.flash.compiler.internal.targets.SWFTarget$FramesInformation.createFrame(SWFTarget.java:838)
        at com.adobe.flash.compiler.internal.targets.SWFTarget$FramesInformation.createFrames(SWFTarget.java:875)
        at com.adobe.flash.compiler.internal.targets.AppSWFTarget$AppFramesInformation.createFrames(AppSWFTarget.java:386)
        at com.adobe.flash.compiler.internal.targets.SWFTarget.build(SWFTarget.java:243)
        at com.adobe.flash.compiler.clients.MXMLC.buildSWFModel(MXMLC.java:686)
        at com.adobe.flash.compiler.clients.MXMLC.buildArtifact(MXMLC.java:672)
        at com.adobe.flash.compiler.clients.MXMLC.compile(MXMLC.java:553)
        at com.adobe.flash.compiler.clients.MXMLC.mainNoExit(MXMLC.java:242)
        at com.adobe.flash.compiler.clients.MXMLC.mainNoExit(MXMLC.java:196)
        at com.adobe.flash.compiler.clients.MXMLC.staticMainNoExit(MXMLC.java:167)
        at com.adobe.flash.compiler.clients.MXMLC.main(MXMLC.java:144)
```

I've been testing it with some air 33.* sdks.. many jdk versions (8 to 16, 32 and 64 bits).. many font embed params variations.. using command line or IDE, like Intellij IDEA... trying different compiler modes, like amxmlc or built-in compiler 2.0 ... no success.. same error..

thinking in a possible workaround, like load fonts externally by swf files, I remember that it doesn't work for iOS devices 'cause you can't load swf files with code blocks inside..

**Comment by pis0** [comment]
SOLVED.. it was something related to the font file.. for some reason, the font files become invalid after the git clone instruction triggered by the git actions service
